### ISSUE TITLE
Blog cards have unnecessary top dotted border

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1004]
Go to snapcraft.io/blog, look at the blogpost cards:

<img width="806" alt="screen shot 2018-08-09 at 12 56 29" src="https://user-images.githubusercontent.com/83575/43894878-c6f7adbc-9bd3-11e8-8120-155a2bdaedf2.png">

They all have a dotted border at the top.

### Expected behaviour

There should be no unnecessary border

**Comment by therealjuan** [comment]
Fixed
