### ISSUE TITLE
Some images use Ubuntu color scheme on Snapcraft.io

### ISSUE THREAD

**Issue by gjsman** [canonical-websites/snapcraft.io#101]
https://assets.ubuntu.com/v1/74bd0daf-interfaces-+plugs-and-slots.svg
https://assets.ubuntu.com/v1/143dff64-Update-Snapcraft%28dot%29io-architecture_v2.svg
https://tutorials.ubuntu.com/src/codelabs/create-your-first-snap/img/3fd9411611ea92b2.png

**Comment by bartaz** [comment]
@carlaberkers These are images on current https://snapcraft.io site.

Do we need to address this now, that new home page is in work?

**Comment by carlaberkers** [comment]
thank you for raising an issue @gjsman. 

with the new homepage in work there is no need to change them now @bartaz
