### ISSUE TITLE
 Releases tab shows "a few seconds ago" for all releases

### ISSUE THREAD

**Issue by popey** [canonical-websites/snapcraft.io#1010]
https://snapcraft.io/account/snaps/get-iplayer/release

There are a number of releases listed, all of them show "a few seconds ago" in the "Submission date" column. Hovering over them shows the date/time when I loaded the page, not when the releases were done.

Looks like you're displaying the date/time when the page was refreshed, not the date/time when the release was made.

![screenshot_20180810_114457](https://user-images.githubusercontent.com/1841272/43955260-367122cc-9c97-11e8-8980-28fedaa9c4af.png)

**Comment by bartaz** [comment]
I thought I fixed that, but apparently mistyped the field name. Should be fixed in #1012
