### ISSUE TITLE
tldr last updated in the future

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1043]
### Steps to reproduce the problem

* Visit https://snapcraft.io/tldr
* Note that "Last updated" says "Nov 18"
* Actual last updated was 2018-06-04

**Comment by bartaz** [comment]
The date is not in future, it's November 18th. Stable version was updated 9 months ago (which makes it last November), it was edge that was released in June.

<img width="1063" alt="screen shot 2018-08-27 at 22 31 56" src="https://user-images.githubusercontent.com/83575/44684434-5dedcc00-aa49-11e8-8341-f4f715035827.png">

But maybe we can improve messaging around the dates to make it less confusing.

**Comment by evandandrea** [comment]
Sorry about that.
