### ISSUE TITLE
snapcraft.io/blog is much too heavy

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#1067]
1\. Go to [snapcraft.io/blog](https://snapcraft.io/blog).
2\. Open your browser’s network monitor (e.g. Chrome “Tools” > “Developer Tools” > “Network”).
3\. Shift+Reload, to simulate someone arriving on this page for the first time.

What happens: The page is 20.5 MB.

![snapcraft io-blog-size-summary](https://user-images.githubusercontent.com/19801137/45262566-01a78680-b411-11e8-925b-9de836cf83a2.png)

What should happen: The page is less than, say, 300 KB.

The biggest culprits:

- Card images of 5.2 MB, 3.5 MB, 3.1 MB, 3.1 MB, 2.8 MB etc. These images could be thumbnailed to less than 20 KB each, and still look just fine:

  ![fish compressed](https://user-images.githubusercontent.com/19801137/45262333-b8edce80-b40c-11e8-903c-cefa819e2b07.jpg)

- 358 KB of Ubuntu font files are downloaded, even though I already have the Ubuntu font installed on my computer. Perhaps there’s a way to avoid downloading the Web font if you have it locally. (Or, since snapcraft.io is not an Ubuntu-specific site, perhaps we could stop using Web fonts altogether.)

  ![snapcraft io-blog-font](https://user-images.githubusercontent.com/19801137/45262538-657d7f80-b410-11e8-81aa-3a120bcb6e9c.png)

- [The style sheet](https://snapcraft.io/static/minified/styles.css?v=c4ccd2c) is 112 KB, but only 16.8 KB is actually used.

  ![snapcraft io-blog-css-used](https://user-images.githubusercontent.com/19801137/45262451-c7d58080-b40e-11e8-8fef-f3a97f5d4296.png)

**Comment by Lukewh** [comment]
This is related to https://github.com/canonical-websites/blog.ubuntu.com/issues/405 and I've temporarily removed the images in https://github.com/canonical-websites/snapcraft.io/pull/1070

**Comment by matthewpaulthomas** [comment]
I don’t think this should be closed, if the problem is valid, it isn’t fixed, and there’s no work already tracked to fix it. For it to be valid, you don’t need to agree with the 300 KB target, just to set a target that is less than 20.5 MB. There doesn’t seem to be any open issue on thumbnailing the images, but if removing them altogether really is temporary, then that isn’t a long-term solution. And the page is still 535 KB without images, so if your target is less than that, thumbnailing isn’t a complete solution either. That’s why I identified not one culprit, but three, and probably there are more I don’t know about.

**Comment by therealjuan** [comment]
I would encourage to divide this issue into the different "culprits" as it might need some investigation on the different areas and might not be all related to just the blog?

**Comment by matthewpaulthomas** [comment]
Sure, it’s not just about /blog, that was just the worst I saw. It would be good to consider the site as a whole, not just because many improvements will slim the site as a whole, but also because slimming an individual page the wrong way could fatten a multi-page journey (for example, by inlining CSS or modularising it the wrong way).

I’ve reported #1104 on the font issue in particular, and mailed Ant about whether we have size benchmarks or targets for sites in general.

**Comment by Lukewh** [comment]
Fixed by https://github.com/canonical-websites/snapcraft.io/pull/1122
