### ISSUE TITLE
Store icon cannot be set

### ISSUE THREAD

**Issue by janoskk** [canonical-websites/snapcraft.io#1076]
### Expected behaviour
When saving the store icon I get the following message:
`KeyError: u'icon'`

![image](https://user-images.githubusercontent.com/1554533/45351354-3f91df80-b5b6-11e8-970b-4c0fe20641fd.png)

### Steps to reproduce the problem
Maybe because I set a too large icon first, but after that I set *any* icon and press the Save button I'll get the error above.

### Specs

- _URL:_ https://snapcraft.io/account/snaps/hello-janoskk/listing
- _Operating system:_ Windows 10
- _Browser:_ Chrome 68

**Comment by tbille** [comment]
Thank you for reporting this bug @janoskk 

It seems the problem comes from the snapstore API. A bug has been reported: https://bugs.launchpad.net/snapstore/+bug/1792404

**Comment by tbille** [comment]
Fixes on snapstore side.
