### ISSUE TITLE
Snap search - styling with Vanilla patterns

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#109]

**Comment by carlaberkers** [comment]
Design review actions:

- Footer: ask Ant about the Yocto notification - ideally replace with generic notification if required (PR:https://github.com/canonical-webteam-archive/snapcraft.io-static-pages/pull/162)
- Footer: disable the wrapping rule in the footer
- Footer: make footer design in line with other footers
- Remove grey background on quotes
- Remove "or" between buttons in the header

We have suggestions from @evandandrea, which we will address in the next iteration.
