### ISSUE TITLE
Research snap search API

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#111]
Docs here: https://search.apps.ubuntu.com/docs/

Come up with a very basic plan for how to wire up this app to talk to that API.

**Comment by tbille** [comment]
# Report

Here is the Snapcraft enpoints documentation: https://search.apps.ubuntu.com/docs/#snap-specific-endpoints

I am going to add an endpoint to the backend:
```
GET /search?q={searched_string:string}&limit={limit:int}&offset={offset:int}
```

It will have 3 parameters

- **q** *string*: searched string
- **offset** *int*: number of snaps already searched
- **limit** *int*: number of snaps 

**Returns:** The endpoint will return a template with `limit` snaps.

The snapcraft search endpoint doesn't provides the `offset` and the `limit` parameters. I will develop a small algorithm to convert `offset, limit` to `page, size` already provided by the snapcraft search endpoint. This is to get the same type of endpoint as we have on https://www.ubuntu.com/search?q=snap&limit=10&offset=20

**Comment by bartaz** [comment]
@tbille 

Probably @nottrobin can comment on that, but I'm not sure we need to convert `page` and `size` into `offset` and `limit`. Both are rather technical implementation details and don't matter much from front-end or user perspective.

Or course if there is a particular reason for using `offset` and `limit` (other then just to be the same as on ubuntu.com search), I'm fine with that.

But snapcraft.io pages will use snap store APIs, so I suppose they all will use `page` `size` consistently, so maybe it would be better to stick with what API provides.

**Comment by nottrobin** [comment]
@bartaz I asked @tbille to use `offset` and `limit`.

Interfaces are important and shouldn't be chosen lightly. I suggested `limit` and `offset` precisely to fit in with the www.ubuntu.com search and the standard suggested in [this book](https://pages.apigee.com/rs/apigee/images/api-design-ebook-2012-03.pdf), which I find very sensible. This was carefully considered at the time.

I think standardisation in our URL interfaces across our websites is certainly useful - our developers and the users of our sites (who will be far greater in number than the users of the Snap Store API) will appreciate the consistency.

I actually also think there's a small benefit to being different from the Store API to indicate that this is an independent service. People shouldn't assume it provides all the features of the API, which it definitely won't, or that it even returns exactly the same data from the features that it does share, which it probably won't. Also, not being closely tied to that API's standards leaves the Store API to iterate freely. If they change that interface in v2, we won't have to play catch-up.

Since we have that independence, I think we should in every case pick what we consider to be the best interface, rather than copying the Store API. And I personally like the loose standard provided by Apigee. If you think `page` and `size` are better than `limit` and `offset` for a specific reason, I'm happy to discuss it based on its merits, but not simply because it copies the API.

**Comment by bartaz** [comment]
@nottrobin Thanks for comment. No, I don't have any particular reason to prefer `page`/`size`. I was just wondering why we implement it differently instead of just passing parameters to snap search API. Your explanation clarifies that :)
