### ISSUE TITLE
Make the featured category stand out

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1138]
The featured section looks exactly like any other category on snapcraft.io/store:

<img width="1140" alt="screenshot 2018-09-24 at 13 44 09" src="https://user-images.githubusercontent.com/1523179/45952776-074fbf80-c000-11e8-87a7-e38a08774bf8.png">

We should make this more prominent. For example:

![store copy](https://user-images.githubusercontent.com/1523179/45952735-d5d6f400-bfff-11e8-9794-8e2482361c7a.png)

**Comment by therealjuan** [comment]
[Closing as this problem will be solved through the Magazine View feature](https://github.com/CanonicalLtd/snap-squad/issues/851)
