### ISSUE TITLE
Allow maintenance mode to be set

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/snapcraft.io#1142]
### Expected behaviour
When the store is under maintenance, the snapcraft.io front-end should be able to be flipped into maintenance mode to a) help protect the upstream services b) advise users that their snaps are still there, even if they can't see them

### Specs

- _URL:_ https://snapcraft.io/store
- _Operating system:_ Ubuntu 18.04 LTS
- _Browser:_ Firefox 62.0.2 (64-bit)

**Comment by tbille** [comment]
# ideas from discussion with Celso 
- Implement some kind of circuit breaker in the app at a request level.
- Question: should I use a library that implements this: https://pypi.org/project/circuitbreaker/
