### ISSUE TITLE
Circle CI python tests fail if dashboard is down

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1144]
Circle CI python test seem to be failing if dashboard.snapcraft.io is down:

<img width="744" alt="screen shot 2018-09-26 at 13 44 48" src="https://user-images.githubusercontent.com/83575/46077830-7d842b80-c192-11e8-89fc-8f01c01a02a6.png">

I believe we mock API responses, but is seems some real API is still being called in test.

**Comment by tbille** [comment]
Notes for me: [Example that could help](https://github.com/ecordell/pymacaroons/blob/master/tests/functional_tests/functional_tests.py)
