### ISSUE TITLE
Snapcraft.io should support HTTPS

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/snapcraft.io#115]
## Context

HTTPS provides increased security for our users, the site should redirect to https://snapcraft.io by default
## Expected result

I should be able to navigate to https://snapcraft.io and connect securely.
## Current result

The browser currents times out when attempting to securely connect.

**Comment by sigmavirus24** [comment]
So it seems that `https://snapcraft.io` works, but HSTS is not enabled yet.

**Comment by anthonydillon** [comment]
Seems to be working fine now. All traffic is redirected to a valid Https connection.
