### ISSUE TITLE
External link to Tutorials unfiltered

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#116]
_From @Greggless on October 3, 2017 9:43_

## Summary

The primary navigation link to the external [Tutorials site](https://tutorials.ubuntu.com/) should ideally lead to a filtered view of Snap/Snapcraft related tutorials.

This is just a UX recommendation! 👯 

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#393_

**Comment by nottrobin** [comment]
_From @matthewpaulthomas on October 6, 2017 15:37_

I thought this would be a one-line fix, but it’s currently impractical because [the search form is not a real submitted form](https://github.com/canonical-websites/tutorials.ubuntu.com/issues/357).

**Comment by shivjoshi1996** [comment]
Not in the header anymore, so issue irrelevant @nottrobin
