### ISSUE TITLE
Store entry error: ValueError: Single '}' encountered in format string

### ISSUE THREAD

**Issue by Thomas101** [canonical-websites/snapcraft.io#1161]
### Expected behaviour
Added a `}` character to the app store description. Now every time we try to update the store entry we see the error `ValueError: Single '}' encountered in format string`

![screen shot 2018-10-01 at 12 31 39](https://user-images.githubusercontent.com/103586/46286153-f958ec00-c575-11e8-8831-9f8b98c36248.png)

### Steps to reproduce the problem

It was after we added a `}` to the store description

### Specs

- _URL:_ https://snapcraft.io/wavebox
- _Operating system:_ macOS
- _Browser:_ Chrome 68

**Comment by Lukewh** [comment]
Thanks for the report, this is currently being tracked on launchpad:
https://bugs.launchpad.net/snapstore/+bug/1795416

I'll update this issue when the bug is fixed.

**Comment by Thomas101** [comment]
Thanks - is there anything we can do in the meantime to change our store entry?

**Comment by Lukewh** [comment]
You can change it on the old https://dashboard.snapcraft.io/ site.

**Comment by Thomas101** [comment]
Thanks - worked perfectly :)

**Comment by sparkiegeek** [comment]
https://github.com/snapcore/snapcraft/pull/2316

**Comment by Lukewh** [comment]
Confirmed the fix is live, closing.
