### ISSUE TITLE
Fullscreen screenshots are not centered

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1168]
### Expected behaviour

Screenshots on snap details page used to be centered horizontally and vertically in the middle of the screen.
It seems that with some style changes it got broken again and screenshots are displayed at the top of the screen.

### Steps to reproduce the problem

- go to snap details page (for example skype)
- open screenshot full screen

<img width="1709" alt="screen shot 2018-10-03 at 08 37 58" src="https://user-images.githubusercontent.com/83575/46394000-e5cd9280-c6e7-11e8-9962-25c182b4d671.png">

**Comment by Lukewh** [comment]
This appears to be fixed on production
