### ISSUE TITLE
Front page leads to instructions for installing snapd but not snapcraft

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#117]
_From @matthewpaulthomas on September 25, 2017 19:40_

1\. Go to snapcraft.io.
2\. Click any of the operating system buttons.
3\. Try to find how to install Snapcraft.

What happens:
2\. You are taken to instructions for installing snapd.
3\. Snapcraft isn’t even mentioned on the page.

What should happen: Ideally, the page describes how to install both snapd _and_ snapcraft.

It might save time to fix #315 (Need concise snapcraft install instructions) at the same time as this bug.

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#388_

**Comment by Greggless** [comment]
@matthewpaulthomas will this be resolved by the First Time flow you're doing?

**Comment by matthewpaulthomas** [comment]
@Greggless Unfortunately not. The first-snap flow design covers only part of the front page. So it doesn’t include OS logos on the front page, but it doesn’t exclude them either.

Meanwhile, though, I reported this issue before we had any Store pages. OS logos would serve different purposes on Store pages vs. publisher pages:
- on Store pages, it‘s about how to get your system set up to install any of these snaps
- on publisher pages, it’s about credibility of snaps being useful things to publish.

So, _one_ way of resolving this issue would be to have clickable OS logos on the Store front page, and unclickable (greyed-out) logos on the publisher front page.

**Comment by therealjuan** [comment]
The idea for the operating system section is to let you know that your system can be get ready for snaps but snapcraft only comes to play when you want to publish so not sure why are we referring this to be an issue.
