### ISSUE TITLE
Release UI: HTML errors result in JSON parse error

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1171]
Sometimes API calls for release return HTML instead of JSON (for example in case of gateway timeout, etc). This causes release UI to show weird and unhelpful JSON parse error.

<img width="1663" alt="screen shot 2018-10-03 at 12 58 45" src="https://user-images.githubusercontent.com/83575/46406577-4a024d80-c70c-11e8-9f32-3541e573779f.png">

### Expected behaviour

We should show better error message when HTML error is returned.

**Comment by popey** [comment]
I just had this, so confirming.

![image](https://user-images.githubusercontent.com/1841272/49669683-04d70080-fa5a-11e8-9403-e43dc543b50a.png)
