### ISSUE TITLE
Update supported operating systems 

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#118]
_From @evandandrea on September 15, 2017 15:25_

Please add the following operating systems to the front page:

- Ubuntu MATE
- Manjaro
- Kubuntu
- KDE Neon
- Linux Mint

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#380_

**Comment by nottrobin** [comment]
_From @evandandrea on September 15, 2017 15:28_

Typo: "Ubuntu MATE"

**Comment by nottrobin** [comment]
_From @evandandrea on September 21, 2017 14:7_

Worth checking with @popey and @wimpress to see if Antergos can be added when the rest of these are.

**Comment by nottrobin** [comment]
_From @evandandrea on September 26, 2017 15:45_

See also https://github.com/canonical-websites/snapcraft.io-static-pages/issues/387

**Comment by nottrobin** [comment]
_From @caldav on October 4, 2017 13:24_

@evandandrea @wimpress @popey
Which one of MATE, Kubuntu, KDE Neon, ~Mint~ ship snapd by default in their respective latest stable release?
Which one need extra steps? Such as rebooting or enabling snapd through systemctl

**Comment by nottrobin** [comment]
_From @Lukewh on November 6, 2017 10:56_

@evandandrea @caldav what's the status of this? Mint and Manjaro have been added but what of the others?

**Comment by evandandrea** [comment]
Hi @caldav,

KDE Neon (works out of the box):
* [Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Neon-logo.svg/2000px-Neon-logo.svg.png)
* [snapd 2.27.5](http://ftp.acc.umu.se/mirror/kde.org/files/neon/images/neon-useredition/20171026-1018/neon-useredition-20171026-1018-amd64.manifest)

Kubuntu 17.10 (works out of the box):
* [Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Kubuntu_logo.svg/2000px-Kubuntu_logo.svg.png)
* [snapd	2.28.5](http://cdimage.ubuntu.com/kubuntu/releases/17.10/release/kubuntu-17.10-desktop-amd64.manifest)

Ubuntu MATE (works out of the box):
* [Logo](https://ubuntu-mate.org/gallery/Artwork/design-guide/Circle_of_MATEs.png)
* [snapd 2.0.2 (16.04.3)](http://cdimage.ubuntu.com/ubuntu-mate/releases/16.04.3/release/ubuntu-mate-16.04-desktop-amd64.manifest) and [snapd 2.28.5 (17.10)](http://cdimage.ubuntu.com/ubuntu-mate/releases/17.10/release/ubuntu-mate-17.10-desktop-amd64.manifest)

@popey and @flexiondotorg, can you confirm that no additional steps are needed?

**Comment by popey** [comment]
Confirmed!
