### ISSUE TITLE
api.snapcraft.io/ page is unhelpful

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#1182]
snapcraft.io does not seem to mention api.snapcraft.io anywhere.

However, every page of [snapcraft.io](https://snapcraft.io/) links to [status.snapcraft.io](https://status.snapcraft.io/), which lists “api.snapcraft.io” as the first service.

So, it’s quite likely that someone would discover the existence of an API only by the presence of api.snapcraft.io on status.snapcraft.io.

Unfortunately, if they copy and go to [api.snapcraft.io](https://api.snapcraft.io/), they will see only this:

![api snapcraft io](https://user-images.githubusercontent.com/19801137/46531029-af347b00-c893-11e8-964b-c390328d78c2.png)

This page could be much friendlier, for example any combination of:
- linking to the API docs ~~(once [they are published in context](https://github.com/canonical-docs/snappy-docs/issues/344))~~
- using the snapcraft.io global navigation
- using the same font, spacing etc as the rest of snapcraft.io.

**Comment by sparkiegeek** [comment]
The API docs for dashboard.snapcraft.io do not, and will not document the API available at api.snapcraft.io.

There are other API docs that we are in the process of creating and publishing.

**Comment by matthewpaulthomas** [comment]
I didn’t know the APIs were separate, thanks for the correction. Given how long the new API docs are taking, there’s no need to block on that. We could still add the snapcraft.io styling and global navigation.

**Comment by matthewpaulthomas** [comment]
This issue still exists exactly as reported.

**Comment by therealjuan** [comment]
No one visits this page so closing as it is not relevant
