### ISSUE TITLE
Fix Get Crafting section

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#120]
_From @Ads20000 on September 7, 2017 13:18_

## Summary

Get Crafting section on the snapcraft.io homepage has problems.

## Process

Go to snapcraft.io and scroll down to the Get Crafting section.

## Current and expected result

Current:

```
Snaps have a very simple internal structure — you can easily craft them by hand.

But if your code is on GitHub, the easiest way to build a snap is with our auto-build service. Every commit is auto-built, and every successful build is released to the “edge” channel.

Otherwise, you can use Snapcraft, which allows building from source and from existing packages. Snapcraft also handles releasing your snaps to the world.

Read how to create a snap and join the snap-crafting community — we hang out in the #snappy channel on Freenode or snapcraft@lists.snapcraft.io.
```

Expected:

Snapcraft should have a lower-case 's' (third paragraph), also the auto-build service uses snapcraft so 'otherwise' in the third paragraph doesn't make much sense. @matthewpaulthomas [said](https://github.com/canonical-websites/snapcraft.io/issues/311#issuecomment-303977023) that the auto-build service won't need snapcraft in the future but I'm pretty sure that at the moment it does require a `snapcraft.yaml` to build from? When will this change, if ever? If not in the near future then this paragraph seems misleading.

'Read how to create a snap' should link to https://tutorials.ubuntu.com/tutorial/create-first-snap#0 , I think (currently there is no link for this passage), that would make sense as per the merged PR linked below.

'snap-crafting' should be 'snapcrafting', I think (since snapcraft is the build tool, so it would make sense that snapcrafting is the activity of creating a snap, I don't think I've actually seen this term used much elsewhere though)?

The snapcrafting community links needs to be updated to `we have a fun crowd of people who hang out on <a class="external" href="https://rocket.ubuntu.com/channel/snapcraft">Rocket Chat</a> and on the <a class="external" href="https://forum.snapcraft.io/">snapcraft forum</a>.</p>` as per [this merged PR](https://github.com/canonical-websites/www.ubuntu.com/pull/1779) for www.ubuntu.com.

Perhaps someone like @evandandrea has more ideas on how this section should read.

## Screenshot

![screenshot from 2017-09-07 13-43-05](https://user-images.githubusercontent.com/3178485/30163877-8200a204-93d2-11e7-875e-a5ecf69ea85a.png)

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#368_

**Comment by bartaz** [comment]
@carlaberkers @evandandrea Do we need to address this on current snapcraft.io home page, or does work on new home page makes this unnecessary?

**Comment by evandandrea** [comment]
I think the new work on the homepage makes this unnecessary.

**Comment by matthewpaulthomas** [comment]
> @matthewpaulthomas said that the auto-build service won't need snapcraft in the future but I'm pretty sure that at the moment it does require a snapcraft.yaml to build from?

What I have said is that if nothing goes wrong (or if any problems are easily fixed), a _person_ using the auto-build service never needs to use `snapcraft` the command-line utility. Similarly, it’s possible — and I hope it happens! — that third-party IDEs grow the ability to let you build snaps without ever using `snapcraft` the command-line utility (in the same way that most Windows developers make `.appx` packages using Visual Studio, not using the `MakeAppx.exe` command-line utility). These are two of the reasons to scale back the “Snapcraft” brand as time goes on: publishing snaps is much more than just Snapcraft.

**Comment by nottrobin** [comment]
I really think we should make sure we check with some real developers of snaps about that plan. Linux is not like Windows, and I personally am not sure that the tendency of some Windows devs to expect a point-and-click way of building software is something that the Linux world should ever even try to emulate.

Much like with Juju, I feel that any mission to try to imply that the building of snaps can be a purely point-and-click affair that can be done from start to finish through a graphical interface will be doomed to failure. No matter how clever Snapcraft becomes, the development of snaps will always need a significant amount of debugging, and that will always be best done on the command-line.

As I say, if we genuinely want to explore whether a command-line-free experience is possible, we should make sure we talk to *a lot* of snap developers, and check that at least the majority of them also feel that would be a possibility.
