### ISSUE TITLE
Disable unavailable risk levels rather than hiding them

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#1204]
#1195 hides the “candidate” and “stable” items from the promotion menu in a snap’s “Releases” page, if that snap revision uses `devmode`.

From my review:
> I think it’s a little mysterious to hide the levels completely, rather than just greying them out. Unless great clutter is at stake, usual practice is to grey out items if they can’t be used now but could be used in future. That’s exactly the situation here: when you migrate your snap out of `devmode`, you’ll be able to use these levels again.

Reply by @bartaz:
> Good point. If possible I'd like to address this separately, as currently Vanilla context menu doesn't seem to support 'disabled' items, so I would need to add that.

**Comment by bartaz** [comment]
@therealjuan Why was this one closed? It was not implemented yet
