### ISSUE TITLE
When creating a link to another post, one has to choose either the Ubuntu blog or the Snapcraft blog

### ISSUE THREAD

**Issue by kyrofa** [canonical-websites/snapcraft.io#1222]
I have multiple blog series on both the Ubuntu blog as well as the Snapcraft blog. There is numerous inter-linking, there (a table of contents, or "as discussed in part1...", or "in the next part, we'll discus..."). The URLs of all the links are using Insights, since that's all that existed when they were written. What this means is that, if any of the links are clicked from the Snapcraft blog, one is taken to the Ubuntu blog instead of staying on the series on the Snapcraft blog.

### Expected behaviour

There should be a way to create a link to another blog post where, if the link is clicked from snapcraft.io/blog, the visitor should see the blog post in snapcraft.io/blog. If the link is clicked from the Ubuntu blog, the visitor should stay on the Ubuntu blog.

### Steps to reproduce the problem

Create a new post in wordpress that links to a blog post in the Ubuntu blog, but one that is also available in the Snapcraft blog. Publish that post on both the Ubuntu blog as well as Snapcraft. Note that if you click the link from the Snapcraft blog,  you're taken to the Ubuntu blog.

**Comment by matthewpaulthomas** [comment]
Example of the current URL structures:
- [snapcraft.io/blog/your-first-robot-the-driver-4-5](https://snapcraft.io/blog/your-first-robot-the-driver-4-5)
- [blog.ubuntu.com/2018/03/09/your-first-robot-the-driver-4-5](https://blog.ubuntu.com/2018/03/09/your-first-robot-the-driver-4-5)

You could use relative links to other posts, keeping visitors on the same site, if:
- blog.ubuntu.com URLs stopped including the date hierarchy,
  `<a href="../your-first-robot-the-controller-3-5">`, OR
- snapcraft.io/blog URLs started including the date hierarchy,
  `<a href="../../../../2018/02/11/your-first-robot-the-controller-3-5">`.

The second would be quite difficult to remember and to type correctly. So if it was left up to authors, it would be a tradeoff: the value of including dates in URLs as a hint of an article’s currency, vs. increased difficulty of creating relative links between posts.

An alternative would be some sort of plugin that automatically rewrites link URLs when posts are republished.

Whether done manually or automatically, a corner case would be ensuring that you _don’t_ use relative links when linking to posts that, for whatever reason, happen to be only on one of the two sites.

**Comment by kyrofa** [comment]
Thanks @matthewpaulthomas, that outlines the options nicely.

**Comment by nottrobin** [comment]
@pmahnke could we discuss this at some point?

**Comment by nottrobin** [comment]
We are discussing how we can ultimately eliminate the duplication of blog posts between blog.ubuntu.com and snapcraft.io/blog, but it would involve a fairly fundamental restructure, so won't arrive imminently.

For now, I think the best solution is to use relative links, as suggested by @matthewpaulthomas, and for this reason and others, the URL structure should be unified between the two platforms.

I've created a PR on blog.ubuntu.com to make it understand URLs of the form `blog.ubuntu.com/{slug}` - it will then redirect those URLs to its default URL form of `/{year}/{month}/{day}/{slug}`. This should allow you to add relative links in the form of `<a href="../your-first-robot-the-controller-3-5">`, which will work directly on snapcraft.io/blog, and be redirected to the correct place on blog.ubuntu.com. Hopefully this is an acceptable solution for the time being.

**Comment by kyrofa** [comment]
@nottrobin that sounds great, thank you.

**Comment by nottrobin** [comment]
@tbille actually I've created #1299 so you don't need to - but I'd appreciate reviews on both #1299 and https://github.com/canonical-websites/blog.ubuntu.com/pull/427 if you get a chance.

**Comment by nottrobin** [comment]
So once #1299 is merged as well, @kyrofa you'll have the option to use either relative URL form in your blog posts.

**Comment by kyrofa** [comment]
Excellent, I'm quite happy with this solution :) .

**Comment by nottrobin** [comment]
The blog.ubuntu.com redirect solution has been merged and released - so now URLs like e.g. https://blog.ubuntu.com/your-first-robot-the-driver-4-5 are supported.

The mirroring redirects on snapcraft.io/blog  will hopefully be merged and released tomorrow morning.

**Comment by nottrobin** [comment]
The solution for snapcraft.io/blog has now also been released. 

The best solution is to always use URLs of the form`<a href="../your-first-robot-the-controller-3-5">`. This will work on both sites.

**Comment by kyrofa** [comment]
@nottrobin I'm trying to use this. A URL like `<a href="../ros-production-our-prototype">ROS production: our prototype [2/5]</a>` works on blog.ubuntu.com, but on snapcraft.io it ends up taking me to `https://snapcraft.io/ros-production-our-prototype` which is a 404. Am I missing something?

**Comment by pmahnke** [comment]
@tbille or @b-m-f can you look at this as Robin is on holiday?

**Comment by tbille** [comment]
@kyrofa can't you use this instead?

`<a href="./ros-production-our-prototype">ROS production: our prototype [2/5]</a>`

which works on both sites.
