### ISSUE TITLE
Snap details title is horrible

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/snapcraft.io#1258]
### Expected behaviour
Nearby containers do not contain vomit after seeing the title of the snap details page.

### Steps to reproduce the problem
1. Visit a snap details page, e.g. https://snapcraft.io/core
2. Look at the <title>, see "Linux apps in seconds"
3. Find a nearby empty container to throw up in to.

### Specs

- _URL:_ https://snapcraft.io/core
- _Operating system:_ Ubuntu 18.04 LTS
- _Browser:_ Firefox 63.0

**Comment by therealjuan** [comment]
See #690 for fix
