### ISSUE TITLE
Replace favicon with S

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#126]
_From @evandandrea on May 8, 2017 9:43_

We should replace the current favicon with a version of the icon Tom Macfarlane made:
![snapcraft_s_800x800_hex](https://cloud.githubusercontent.com/assets/1523179/25798968/1e97a796-33db-11e7-812d-aea538c97744.png)

See also https://github.com/canonical-ols/build.snapcraft.io/issues/722

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#316_

**Comment by evandandrea** [comment]
We should close this out. (I don't have the power to do this myself.)

**Comment by bartaz** [comment]
We are rolling out new branding with new icon soon anyway: #284
