### ISSUE TITLE
releases UX unnecessarily truncates revision number

### ISSUE THREAD

**Issue by mitechie** [canonical-websites/snapcraft.io#1265]
### Expected behaviour
I'd expect it to type out 2.4.4 vs the 2....

It fits longer revision values that include a -sha on them in the non-stable channels but the stable channel is a 2.... which isn't helpful. 

### Steps to reproduce the problem
Visit the Juju releases UX

### Specs
![snap-revisions](https://user-images.githubusercontent.com/75915/47916427-957b5900-de7c-11e8-9458-e5f9a5330131.jpg)

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by bartaz** [comment]
Thanks for the bug report. It seems that formatting gets weird when version number is shorter then revision id below it. Will be fixed.
