### ISSUE TITLE
Developer website and contact links are quite misleading

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1270]
This is just an example but If you visit [conjure-up snap page](https://snapcraft.io/conjure-up), there is a link to a Developer site that links to a product information page and contact developer is misleading information as well as it points out to a github repo.

There are many ways we can tackle this problem:

1. Just display whatever URL provided by the publisher in both fields
2. Include a relevant links section within the details page
3. Add labels beforhand 'Developer website: [link] | Contact: [link] ' 
4. A different alternative

**Comment by matthewpaulthomas** [comment]
If I understand the first three options correctly, they suggest we can change how we present the links to users, but we can’t change what developers provide in the first place. But maybe we can…

4. Provide better publisher UI labels/captions, such that publishers _more often_ provide appropriate links. (We could measure the effectiveness of the UI by picking 50 `stable` snaps at random, and measuring what proportion of them have accurate links. Then do the same for the first 50 new `stable` snaps created after any change to the UI.)

5. Introduce “Inappropriate Web link” or similar as one of the reasons for reporting a snap as inappropriate (also useful if it links to a spam site etc). If a moderator confirms the report, the link is removed and the publisher notified.
