### ISSUE TITLE
Hard to find install instructions for snapcraft

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#128]
There doesn’t seem to be any page devoted to installing Snapcraft for your OS.

[The “Build snaps” page](https://docs.snapcraft.io/build-snaps/) has a small section in the middle describing how to install it on “Ubuntu 16.04 LTS and above”.

Install instructions for Ubuntu 16.04 or 16.10 (but, curiously, not 17.04 or 17.10) are also hidden on [page 2 of the “Create your first snap” tutorial](https://tutorials.ubuntu.com/tutorial/create-your-first-snap?utm_source=snapcraft.io&utm_medium=buildsnapsindex&utm_campaign=tutorials#1).

But both of these are [hard to find](https://www.google.co.uk/search?q=install+snapcraft) — and there are no instructions for installing Snapcraft on Fedora, on Windows or macOS (with a VM), or anything else.

This causes problems [on the snapcraft.io front page](https://github.com/canonical-websites/snapcraft.io/issues/117) and [on build.snapcraft.io](https://github.com/canonical-websites/build.snapcraft.io/issues/1001).

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#166
