### ISSUE TITLE
error trying to run notepad-plus-plus

### ISSUE THREAD

**Issue by gwarah** [canonical-websites/snapcraft.io#1289]
### Description
After last ubuntu dist-upgrade, notepad-plus-plus doesn't run anymore

### Expected behavior
Run ok this snapped app

### Steps to reproduce the problem

```
luis@cygnusx1:~$ notepad-plus-plus
grep: /home/luis/snap/notepad-plus-plus/common/.wine/*.reg: No such file or directory
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 12
drwxrwxr-x 3 luis luis 4096 Nov 11 10:06 .
drwxrwxr-x 4 luis luis 4096 Nov 11 10:06 ..
drwxrwxr-x 3 luis luis 4096 Nov 11 10:06 windows

Registry info:
/home/luis/snap/notepad-plus-plus/common/.wine/*.reg:
------------------------------------------------------
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: WINEARCH set to win64 but '/home/luis/snap/notepad-plus-plus/common/.wine' is a 32-bit installation." 
------------------------------------------------------
wine: WINEARCH set to win64 but '/home/luis/snap/notepad-plus-plus/common/.wine' is a 32-bit installation.

```
### Specs

- _URL:_
- _Operating system:_  
`Linux 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`  
- _Browser:_

**Comment by Lukewh** [comment]
Hi,

This repository is for the snapcraft.io website. https://snapcraft.io/notepad-plus-plus links to [the notepad++ developer site](https://github.com/mmtrt/notepad-plus-plus) which happens to also be on Github, so you should raise the issue there :). Closing as it's not something we can fix.

Cheers!

**Comment by gwarah** [comment]
> Hi,
> 
> This repository is for the snapcraft.io website. https://snapcraft.io/notepad-plus-plus links to [the notepad++ developer site](https://github.com/mmtrt/notepad-plus-plus) which happens to also be on Github, so you should raise the issue there :). Closing as it's not something we can fix.
> 
> Cheers!

Tks for the information, by the way I believe this is the correct channel to post this issue

https://github.com/mmtrt/notepad-plus-plus
