### ISSUE TITLE
Explain that the examples are a snapcraft.yaml file in the root of the project

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1295]
From @MariadeAnton. We should show the path to the snapcraft.yaml (i.e. `./snapcraft.yaml`) where we say, "here's how offlineimap uses it:"

<img width="680" alt="screenshot 2018-11-09 at 09 57 22" src="https://user-images.githubusercontent.com/1523179/48255882-ddaef400-e405-11e8-881b-84a70aaba24e.png">

**Comment by therealjuan** [comment]
As part of this work we should add the link to what `offlineimap` is about rather than the github repo as at this stage the user might want to understand what is `offlineimap`. At a later stage, we provide them the github repo to clone so no need to do it upfront.
