### ISSUE TITLE
Snap selling points are too verbose

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1296]
From @mariadeanton. We should shorten these (first snap flow):

<img width="499" alt="screenshot 2018-11-09 at 10 02 53" src="https://user-images.githubusercontent.com/1523179/48256141-a260f500-e406-11e8-9fee-5f6bc1dc1377.png">

**Comment by therealjuan** [comment]
We probably need to reiterate this but we agreed to go with:

![image](https://user-images.githubusercontent.com/8167677/48542384-f3656300-e8b6-11e8-9e92-07e9805925ae.png)

```
Why are snaps good for Python projects?
- Easy to discover and install by millions using the Snap Store or command-line every day
- Automatically updated to the latest stable version of your app
- Revert to previous version if an update fails, preserving data
- Isolation ensures no conflicts between applications
- Identical behaviour across Linux distributions, even with C library dependencies

With PyPi you can distribute Python apps and virtualenv gives you a solution to app and system dependencies. Snaps combine these ideas offering a Linux app store experience for end users.
```

The idea is to put some quick facts at the top and further explanation about why below these points to help developers quickly scan the page to get the main points straight. If you need something more convincing we have the paragraph for further explanation.
