### ISSUE TITLE
Mention where to file bugs with `snap` (the application) on the site

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#130]
_From @nottrobin on August 30, 2016 7:11_

Nowhere on the site (that I could find) directs users to the correct place to file bugs with `snap` the application. The correct place is [on Launchpad](https://bugs.launchpad.net/snappy/+filebug).
## Process

Go to the [community page](http://snapcraft.io/community/). Behold that it doesn't mention the Launchpad bugs list.

I'm not sure whether this should be as a section within the community page or as an item in the footer, or both.

I've also [created a PR](https://github.com/snapcore/snapd/pull/1780) to mention this bugs list in the README for the `snapd` project.

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#191_

**Comment by nottrobin** [comment]
_From @barrymcgee on September 23, 2016 14:58_

@caldav Can you confirm the copy change here? Perhaps this should go in the site-wide footer?

**Comment by nottrobin** [comment]
_From @caldav on November 22, 2016 17:43_

I don't think reporting bugs for snapd itself should go in the site-wide footer. We have 4 bug reporting links we ideally want:

- Report a bug on this site (currently in footer)
- Report a documentation bug (https://bugs.launchpad.net/snappy/+bugs?field.tag=snap-docs)
- Report a snapd bug (https://bugs.launchpad.net/snappy/+bugs)
- Report a snapcraft bug (https://bugs.launchpad.net/snapcraft/+bugs)

For #2 I think we should follow what we are doing on docs.ubuntu.com (last item in the left nav)
#3 and #4 should probably go into the respective doc landing pages for snapd/snapcraft and on the community page.

**Comment by nottrobin** [comment]
_From @matthewpaulthomas on November 6, 2017 10:59_

In a design review recently, I suggested that the footer contain something like
> You can contribute to **snapd**, **snapcraft**, or **this Web site**.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.hctjdt68dor7) with text similar to my proposal above: “You can contribute to, or report problems with, **snapd**, **snapcraft**, or **this Web site**.”

**Comment by nottrobin** [comment]
On https://snapcraft.io/ it says "Fork snapd on GitHub". This should be updated to more generically point users at the snapd codebase, from where they can do many things - fork, file bugs, file PRs etc.
