### ISSUE TITLE
$EDITOR is not defined

### ISSUE THREAD

**Issue by popey** [canonical-websites/snapcraft.io#1304]
### Expected behaviour

Load snapcraft.yaml in a text editor

### Steps to reproduce the problem

Follow the tutorial linked in Linux Mint 19 (and indeed Ubuntu 18.04).
We (and Mint) don't set $EDITOR by default, so the step 2 line which is `$EDITOR snapcraft.yaml` plain doesn't work.

### Specs

- _URL:_ https://snapcraft.io/first-snap/python/linux/package
- _Operating system:_ Linux Mint 19
- _Browser:_

**Comment by therealjuan** [comment]
Proposed updated copy:

![image](https://user-images.githubusercontent.com/8167677/48479989-e25a1a80-e800-11e8-8863-f69a7d5b6eaf.png)

```
Open the snapcraft.yaml file in the root of the project.
Enter the snap/directory and you will find a snapcraft.yaml file. Edit this file with your preferred text editor.

cd offlineimap
vi snapcraft.yaml
```

**Comment by therealjuan** [comment]
Changed vi to nano as agreed with advocacy

![image](https://user-images.githubusercontent.com/8167677/48542310-bdc07a00-e8b6-11e8-9e76-c43ff3c36e1c.png)

```
Open the snapcraft.yaml file in the root of the project.
Enter the snap/directory and you will find a snapcraft.yaml file. Edit this file with your preferred text editor.

cd offlineimap
nano snapcraft.yaml
```
