### ISSUE TITLE
'Site feedback' button is blury

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1306]
New 'Site feedback' button (on first snap flow) is blurry compared to rest of the page.

(on MacOS)

<img width="816" alt="screen shot 2018-11-13 at 13 54 31" src="https://user-images.githubusercontent.com/83575/48414730-c9dbf880-e74b-11e8-94aa-c5a926333500.png">

**Comment by therealjuan** [comment]
fixed now!
