### ISSUE TITLE
Allow localization of snapcraft.io

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#131]
_From @Winael on June 15, 2016 10:0_

To promote snapcraft.io more, it would be great to allow localization. Users could read the information in their native languages, so we can reach more people.

For now the portal is only accessible for English-speaking people.

I begin to work on a translation of the portal into french. As soon it is ready I could pull request it.

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#13_

**Comment by nottrobin** [comment]
_From @anthonydillon on June 29, 2016 10:57_

@Winael Thank you very much. Internalisation is a highly desired feature for the site and we would love to support it. I will ask our translation team what would be the best way forward.

**Comment by nottrobin** [comment]
_From @anthonydillon on June 30, 2016 14:25_

@Winael I have created a launchpad project to translate the site into as many languages as possible. If you could please help translate to French there. That would be best as it will be kept up to date with site changes.
https://translations.launchpad.net/snapcraft.io

**Comment by nottrobin** [comment]
_From @Winael on July 3, 2016 21:39_

Hi Anthony,

It seems that strings wasn't well extracted. It seems to due to simple
quote characters inside strings. Some strings are very hard to translate

**Comment by nottrobin** [comment]
_From @matthewpaulthomas on June 19, 2017 10:50_

I see four main things to fix, in order:
1. As @Winael suggested, the strings are being split on apostrophes, and also inappropriately on inline markup. This is now reported separately as #39.
1. The strings are not being regenerated when the code changes. For example, in #340 I changed the front page to say “[the easiest way to build a snap is with our auto-build service … Otherwise, you can use Snapcraft…](https://github.com/canonical-websites/snapcraft.io/pull/340/files)”. But the translation template still says “[the easiest way to build a snap is with snapcraft](https://translations.launchpad.net/snapcraft.io/trunk/+pots/snapcraft.io/pt_BR/85/+translate)”.
1. The various CMSes need to generate and serve the localized versions to a defined URL schema (for example, `?lang=`_languagecode_).
1. There needs to be a language switcher to get to those localized versions, in a consistent place on the snapcraft.io page layout. (Maybe this could be accompanied by a link for people to help out with the localization.)

**Comment by therealjuan** [comment]
Not happening in upcoming cycles

**Comment by twang2218** [comment]
Is there any update on localization of snapcraft.io, especially the document? It seems https://translations.launchpad.net/snapcraft.io hasn't been updated for more than 5 years.

**Comment by cristinadresch** [comment]
We don't have this planned for the upcoming year, but we'll speak to the product manager about this to check if this is something we want to consider for the backlog.

**Comment by hbshrd** [comment]
@anthonydillon @Winael @nottrobin @cristinadresch

It seems, that project https://translations.launchpad.https://launchpad.net/snapcraft.ionet/snapcraft.io doesn't contain https://snapcraft.io/ website strings and outdated. Also @anthonydillon see the https://launchpad.net/snapcraft.io description,

>Snapcraft.io home for translations. The main site code and issues are managed in GitHub at https://github.com/ubuntudesign/snapcraft.io

no such github project now.

e.g. flathub already support for that https://hosted.weblate.org/projects/flathub/

Should i open new issue for take your (website team) attention?

**Comment by hbshrd** [comment]
Also, can someone tell me; why should we translate https://translations.launchpad.net/snappy? i mean, where is it in-use? it seems, it's not related to snap desktop or snapd
https://code.launchpad.net/~snappy-dev/snappy/snappy-moved-to-github

https://translations.launchpad.net/snap-store-desktop
https://translations.launchpad.net/snapd
