### ISSUE TITLE
Logos homepage not vertically centered on Firefox

### ISSUE THREAD

**Issue by tbille** [canonical-websites/snapcraft.io#132]
See archlinux logo:
![Screenshot-2017-11-6 snapcraft - Snaps are universal Linux packages.png](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/fdf211a8-5b19-4b2d-8172-35c8da5a2006)

**Comment by bartaz** [comment]
With new home page being released already is not relevant anymore.
