### ISSUE TITLE
Release UI - Table not displayed well for unreleased snaps on release page

### ISSUE THREAD

**Issue by tbille** [canonical-websites/snapcraft.io#1323]
# Problem

table not well displayed on releases page for unreleased snaps

# Step to reproduce

- On a snap unreleased.
- Go to releases pages

![screenshot_2018-11-16 releases and revision history for test-snap-toto](https://user-images.githubusercontent.com/2707508/48611035-57eaf580-e97d-11e8-8e14-12f52d460198.png)

**Comment by bartaz** [comment]
Good catch. Table displays well only when there is any architecture in releases. We need some better 'empty' state.

**Comment by bartaz** [comment]
@tbille please keep test-snap-toto unreleased for easier testing, thanks! ;)
