### ISSUE TITLE
"Autobuild from github" section - button too close to bottom edge

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/snapcraft.io#134]
The space between the button and the bottom edge should be the same as the top of the strip (4rem). It is overriden to let the image touch the bottom edge, but that puts rthe content too close to it. Could we have an alternative that doesn't override the . strip margin?

Curently:
![image](https://user-images.githubusercontent.com/2741678/32491548-02d3df0c-c3af-11e7-992b-eae1e1f14e81.png)

Ideally:
![image](https://user-images.githubusercontent.com/2741678/32491738-b0ba94b2-c3af-11e7-934a-ed9664dff80a.png)

**Comment by bartaz** [comment]
Already fixed in #98
