### ISSUE TITLE
Screenshots are missing the navigation arrows

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/snapcraft.io#1343]
If you visit: https://snapcraft.io/blender
The arrows on the screenshot section are disabled (hidden) because the slider init function is triggering before the images. 

Screenshot:
![screenshot_2018-11-21 install blender for linux using the snap store snapcraft](https://user-images.githubusercontent.com/1413534/48856211-bbc25380-edad-11e8-91a4-f4bc5da656a2.png)

**Comment by bartaz** [comment]
Can you give more details (OS, browser, network speed)?

I can see them just fine (tested Chrome, Firefox). Could this be a networking issue? Even on a slow network (when slider starts initializing before images are loaded) it works fine - images slowly appear, but slider has buttons and works.

**Comment by anthonydillon** [comment]
Ubutnu 18.04 Firefox Quantum 63. Fast internet.

**Comment by Lukewh** [comment]
Interesting, I can't see them on the same browser and OS.

Works in Chrome, however.

**Comment by Lukewh** [comment]
This seems to work for me now @anthonydillon can you check it again please?

**Comment by Lukewh** [comment]
Turns out it happens when the browser is over certain widths on desktop.

My browser, set to 2558px wide (weird size, I know, basically 1700px in normal dpi's) hide's the arrows. If I have the dev tools open to the side of the page, they load.

Resizing the browser always causes them to display.

**Comment by therealjuan** [comment]
Probably worth to add this to the piece of work belonging to adding video and media types layout as they are basically part of the same component.
