### ISSUE TITLE
Store should consider limiting media dimensions

### ISSUE THREAD

**Issue by popey** [canonical-websites/snapcraft.io#1346]
A developer has uploaded 'large' GIFs to the store which appears to trigger an out of memory error in GNOME Software when users view the application page.

https://gitlab.gnome.org/GNOME/gnome-software/issues/532

While this could certainly be a bug in GNOME Software rendering, perhaps we need some sane limits on pixel dimensions and size of media files being uploaded by developers.

The icon has a (ludicrously small) limit of 256x256, but the screenshots do not have limits. 

"One or more screenshots to display with your app. Use the Ctrl key to select multiple files. "

**Comment by therealjuan** [comment]
This will be covered by the media types and layouts work we are planning for this cycle.
