### ISSUE TITLE
Outdated package notifications make me do work

### ISSUE THREAD

**Issue by stub42** [canonical-websites/snapcraft.io#1367]
Snap packages are being built automatically for me by both Launchpad and build.snapcraft.io. The outdated package notifications are great, but would be even better if they actually triggered the build and pushed the snap to configured channels, rather than just nag me to do it manually (which gets pushed to the bottom of my queue, as step one is remembering where the source was setup).

**Comment by apolitech** [comment]
Yep it will be great to have something like this. We will have more secure snaps

**Comment by Lin-Buo-Ren** [comment]
It would be great if the versions in stable/candidate/beta channels can rebuild themselves with the respective configuration...

**Comment by therealjuan** [comment]
Thanks for bringing this to our attention, as this involves a wider conversation with other teams related to the snap development. Would you be able to post this as [a new thread in the forum](https://forum.snapcraft.io)?

**Comment by therealjuan** [comment]
Thanks for posting the message on the forum, we will make sure any decisions made that affects snapcraft.io will be taken in consideration to improve the platform.
