### ISSUE TITLE
Homepage branding refresh build

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#1391]
Implement the "slanted backgrounds" of https://github.com/canonicalltd/snapcraft-design/issues/545
Just the header for now (the issue says the footer isn't signed off).

We'd like to make this in a way that's reusable and purely aesthetic, so as little extra markup as possible. @anthonydillon and I discussed it a little and if we could use SVG's with masks and / or pseudo elements that would be ideal.

This is the first site to implement this so will help our decisions in how to implement for vanilla :)!

**Comment by bartaz** [comment]
@Lukewh what is the scope of this? Designs have quite many changes on them: 
- new 'slanted' background for top section
- new 'slanted' background for footer
- complete new layout for first snap flow language picker

**Comment by Lukewh** [comment]
Updated description @bartaz

**Comment by bartaz** [comment]
@Lukewh This looks like a pattern that was tried out in Vanilla, but didn't end up merged: https://github.com/vanilla-framework/vanilla-framework/pull/2051#event-2190529579

Could it be based on that?, seems like most CSS work was done there and initially reviewed.
