### ISSUE TITLE
Snap search result pages don't always have same size

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#140]
### QA

1. Go to snap search, for example:
https://staging.snapcraft.io/search?q=core&limit=10&offset=0

Because limit is set to 10 page size should be 10.
This link correctly shows first 10 results of the search and has links to next page at the bottom.

2. Go to next page of results:
https://staging.snapcraft.io/search?q=core&limit=10&offset=10

Limit is still set to 10, so 10 results should be shown but only 8 are on the page.
It would be fine if that was the last page of the results, but it's not. There is a link to next page.

3. Go to 3rd page of the results:
https://staging.snapcraft.io/search?q=core&limit=10&offset=20

Now only only 6 results are shown. There is still next page:

4. Go to last page of the results:
https://staging.snapcraft.io/search?q=core&limit=10&offset=30

This page is last page of the results and shows 2 snaps.

### Current behaviour

It seems like not all results are shown or page size differs from page to page.

### Expected

All snaps should be shown, every page of the results should have the same size defined by `limit` parameter (defaults to 10).

**Comment by tbille** [comment]
This seems to be a problem that comes from the snap search API. I opened [an issue](https://bugs.launchpad.net/snapstore/+bug/1731925) on their bug tracker. We wait for an answer, to see if they will fix it, otherwise we will do a "hack" to get more results and be sure to always have the `limit` of snaps in the response

**Comment by tbille** [comment]
Snap store made updates, now the search seems to work normally.
