### ISSUE TITLE
opera can not read usb drives with snap intall

### ISSUE THREAD

**Issue by nonoayay** [canonical-websites/snapcraft.io#1410]
### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by nonoayay** [comment]
i have a computer with all data on us drives. this is not possible to give a download directory to opera on an usb drive. This happens only with snap install. With a regularly install I can do it. Any idea?

**Comment by bartaz** [comment]
@nonoayay This repository if for tracking issues with snapcraft.io website, not snaps themselves.

For issues with particular snap you should reach out to the developer. If you think this may be an issue with snap 'ecosystem' you can ask on snapcraft forum (https://forum.snapcraft.io/categories),  where community should be able to help.

Thanks!
