### ISSUE TITLE
Release UI – the ‘Show all  revisions’ link should toggle to [x]

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/snapcraft.io#1427]
### Expected behaviour
Releases page: the ‘Show all  revisions’ link should toggle to [x]
Currently, The link remains visible and pushes down the heading and everything else. By design, it should look like this instead:
![image](https://user-images.githubusercontent.com/2741678/49799112-03e4ee00-fd3c-11e8-9483-3ec803dee05c.png)
### Steps to reproduce the problem
Click link; 

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by bartaz** [comment]
We removed 'Show all' link, as showing all revisions was moved to a dropdown, so this is not an issue anymore.
