### ISSUE TITLE
Store page suggestion: Search box on all sub-levels

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-websites/snapcraft.io#1444]
Search box is shown across the screen on all top-level pages.

If you select a specific snap, the search box is no longer shown, and the user needs to click the browser back button to go back to the category for search.

Expected behavior: the search box should be shown consistently on all pages. If the visual layout conflicts with showing the snap in the best way, an alternative options should be offered, e.g. a smaller search, a pop out search, etc.

![store-snap-no-search-shown](https://user-images.githubusercontent.com/43789966/49997679-2409ec80-ff8a-11e8-91db-58b7d78cb415.png)

**Comment by therealjuan** [comment]
That is a great suggestion, and we will have a look into it once we implement site-wide search which we will implement firstly localised in each section of the site: Store (for snaps), Docs (for documentation), Blog (for posts).

To have a site-wide search at the very top (menu) it will mean we need to find a way to search through various types of contents and display to the user so perhaps the easier solution will be to have a search bar underneath the top navigation:

![image](https://user-images.githubusercontent.com/8167677/50345272-bd0ea980-052e-11e9-894d-84575442baff.png)

Problem with this solution is that we have a global navigation, top navigation, search and then the content so probably we want to slim the header.

**Comment by therealjuan** [comment]
We will look into it as part of the Magazine View update.
