### ISSUE TITLE
Store page suggestion: Floating top menu

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-websites/snapcraft.io#1445]
When a user scrolls down, the top menu is no longer visible.

Optional behavior: the top menu would float (including search), to allow quicker navigation.

![store-no-floating-menu](https://user-images.githubusercontent.com/43789966/49997791-6df2d280-ff8a-11e8-8876-da751a30cbcb.png)

**Comment by therealjuan** [comment]
We are re-thinking the store homepage with the magazine view so we will consider this.
