### ISSUE TITLE
January 2019 snapcraft meetup tags and tracing

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-websites/snapcraft.io#1450]
Placeholder for the Snapcraft meetup tracing/tagging of store progress.

We want to profile the behavior of new devs from registration to snap publication, including language guides. We want to be able to fully understand their progress and difficulties.

This issue is a placeholder to make sure we have all the necessary tags to do so.

Due date: 11/01/2019

The suggested vectors to profile:

Registration process, step by step
First click after registration
Time spent on each page (including documentation)
Dead leads (users follow a trail then close the tab without snap action)
Use of language guides

**Comment by tbille** [comment]
meetup passed I am closing this issue
