### ISSUE TITLE
New [Edit] link on snap details page is misleading

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1453]
When you are signed in to snapcraft.io and visit snap details page of any snap you own you see a little Edit link next to your name (introduced in #1434)

![](https://user-images.githubusercontent.com/2707508/49950702-3a636a00-fef0-11e8-89be-a94ce64b10f5.png)

It looks a bit misleading - it looks like it's meant to edit publisher name when it's the one thing that you cannot edit in snapcraft.io directly. In any way it doesn't suggest that you are about to edit contents of the whole page.

### Expected behaviour

'Edit' link should be positioned and maybe labeled in a way that will better suggest that it's meant for editing contents of the snap listing.

Maybe a notification or a 'bar' over the top of the page?

**Comment by therealjuan** [comment]
A notification bar will make sense in this case with a message similar to:

```Ensure your snap stay always relevant and compelling. [You can update its listing information here](link to listing)```
