### ISSUE TITLE
Include self-serve categories on detail pages

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1496]
Now that publishers can include categories as part of the listing publisher page, we should showcase the selection somewhere on detail pages.

Most obvious candidate is next to the publisher username. On hover, the category will get underlined linking to the relevant category store page.

![Details.jpg](https://images.zenhubusercontent.com/56b0a0916caf56c9d38c2685/d9419758-fdda-4cb6-87ee-515b37baf84f)

**Comment by cprov** [comment]
We need to expose the `categories` field in the v2 APIs, the snap public page is using `/v2/snaps/info/$NAME.
