### ISSUE TITLE
[Repost] Footer on every non-snap page has text needed only for front page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#150]
1\. Go to snapcraft.io.
2\. Follow the link “Learn to craft your first snap” or “Install snapd”.
3\. Look at the page footer.

What you see: “Yocto Project and all related marks and logos are trademarks of The Linux Foundation. This website is not, in any way, endorsed by the Yocto Project or The Linux Foundation.”

What you should see: That noise should not be present, since it is relevant only to the single page where the Yocto logo is actually used.

In the original issue, Robin wrote:
> Will be fixed by [CanonicalLtd/snappy-design-squad#148](https://github.com/CanonicalLtd/snappy-design-squad/issues/148)

However, that issue has just been closed and this remains a problem.

[This is a reconstruction from memory of the previous snapcraft.io#385. That snapcraft.io repo was moved to snapcraft.io-static-pages, which was then marked as not using Issues, causing the original report to [disappear](https://github.com/canonical-webteam-archive/snapcraft.io-static-pages/issues/385).]

**Comment by matthewpaulthomas** [comment]
If the fix for #121 involves separate text for each logo, this will become more important because it will make the footer much longer.

**Comment by Greggless** [comment]
Will be resolved due to the outcome of these related issues:
- https://github.com/canonicalltd/snapcraft-design/issues/210
- https://github.com/canonicalltd/snappy-design-squad/issues/314
- https://github.com/canonical-websites/snapcraft.io/issues/177

**Comment by Lukewh** [comment]
Fixed
