### ISSUE TITLE
Release UI: Replace ⤴ with Promote

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1504]
Since a big majority of snaps have less than 3 architectures and the ⤴ character does not explain enough, we can replace it with `Promote…` with an ellipsis (character instead of 3 dots) to indicate a contextual menu will appear with options on which channel to promote to.

![image](https://user-images.githubusercontent.com/8167677/50903306-584fbc00-1415-11e9-8f4b-c4a55fb86eb9.png)

**Comment by bartaz** [comment]
Do we want it for all snaps or only for snaps with smaller number of architectures (and keep smaller button when there are 5-6 architectures)?

Because first column gets very large (seems like more than a third of the table) the buttons (especially when delete button is the only one) seem very detached from the channel name.

**Comment by matthewpaulthomas** [comment]
Ellipsis is a general-purpose symbol for “you’ll need to do something more to finish this”. For “this will open a menu” in particular, though, it’s much more common to use a downward triangle ▾ instead.

> Do we want it for all snaps or only for snaps with smaller number of architectures

A drawback of making the button look different, depending on the number of architectures, is that it could end up looking different for different snaps administered by the same person.

**Comment by therealjuan** [comment]
> Ellipsis is a general-purpose symbol for “you’ll need to do something more to finish this”. For “this will open a menu” in particular, though, it’s much more common to use a downward triangle ▾ instead.
That would mean that might be better to have a drop down and a button instead of just a button, but since we are talking about an action triggered by abutton I would suggest to use the word `Promote` with no extra chars.

> Do we want it for all snaps or only for snaps with smaller number of architectures
Probably will be better to have the same button for every snap regardless of number of architectures, it might be better to look at ways on improving the layout when dimensions are compromised.
