### ISSUE TITLE
Status.snapcraft.io errors with _ga parameter in URL

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-websites/snapcraft.io#1513]
(Copied from [Status.snapcraft.io errors with _ga parameter in URL - store - snapcraft.io](https://forum.snapcraft.io/t/status-snapcraft-io-errors-with-ga-parameter-in-url/9405))

I somehow encountered a gateway error page or some sort while editing the snap listings, it prompts me to access <https://status.snapcraft.io/?_ga=2.32817022.1556816414.1547176837-595180816.1528899914> for service status, but I subsequently encountered the following zh_CN localized error message while accessing the URL:

```
 当处理您的请求时遇到问题。请联系技术支持获得帮助。  
```

(Which is literally, "We encountered a problem while processing your request.  Please contact technical support for help.")

### Expected behaviour
Proper [Snap Store Status](https://status.snapcraft.io/) page

### Steps to reproduce the problem
1. Somehow trigger a server error page at snapcraft.io
2. Click the link to status.snapcraft.io in the error page

### Specs

- _URL:_ <https://status.snapcraft.io/?_ga=2.32817022.1556816414.1547176837-595180816.1528899914>
- _Operating system:_ ezgo 14(Based on Kubuntu 18.04)
- _Browser:_ Mozilla Firefox 64.0 AMD64

**Comment by tbille** [comment]
Since the update, I haven't run into the bug again.
Closing this issue since no one mentionned it since.
