### ISSUE TITLE
502 rather than 404 on unauthenticated attempt to view metrics

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1518]
If I try to load https://snapcraft.io/postman/metrics in a tab with my credentials, it works fine. If I go into a tab that doesn't have them, I see this:

<img width="769" alt="screenshot 2019-01-17 at 16 09 46" src="https://user-images.githubusercontent.com/1523179/51324040-5ec3e080-1a72-11e9-9224-b77212399a28.png">

**Comment by tbille** [comment]
@evandandrea yesterday we had a big upgrade of our k8s cluster. Authentication wasn't working but has been fixed now. :smile:
