### ISSUE TITLE
Unable to delete old screenshots from Snap store listing of Wekan

### ISSUE THREAD

**Issue by xet7** [canonical-websites/snapcraft.io#1535]
### Expected behaviour

When deleting old screenshots from Snap store listing, screenshots are deleted.

### What happens instead

Deleting does not delete all. Adding new screenshots makes duplicates. There is more than 5 images added at once.

### Steps to reproduce the problem

Checkmark images to delete. Adding new ones makes duplicates.

### Specs

- _URL:_ https://snapcraft.io/wekan/listing  , https://snapcraft.io/wekan
- _Operating system:_  Ubuntu 18.04
- _Browser:_ Chrome, newest

**Comment by xet7** [comment]
https://forum.snapcraft.io/t/unable-to-delete-old-screenshots-from-snap-store-listing-of-wekan/9696

**Comment by tbille** [comment]
@xet7 thanks for reporting this bug. We are currently fixing it in this issue #1526 . I will close the this one once the bug is fixed

**Comment by tbille** [comment]
This has been fixed now.
