### ISSUE TITLE
Unable to exclude multiple territories in distribution

### ISSUE THREAD

**Issue by tomleavy** [canonical-websites/snapcraft.io#1546]
### Expected behaviour

Our snap uses strong encryption and our US export compliance rules suggest we should block downloads from a few territories.

### Steps to reproduce the problem

1. Select snap and enter `settings` tab
2. Select the `Selected territories` option from `Distribution`
3. Select `Exclude these territories`
4. Select multiple territories
5. Click `Save`
6. Error appears (selected first 2 territories on the list) `Select a valid choice. AF,AX is not one of the available choices`

### Specs

- _URL:_ https://snapcraft.io/mysnap/settings
- _Operating system:_ macOS Mojave
- _Browser:_ chrome 71.0.3578.98

**Comment by Lukewh** [comment]
Thanks for this report @tomleavy, I'll get it fixed ASAP.

**Comment by tomleavy** [comment]
Thank you for looking into the issue. Looking to make my snap live on the 15th, so perfect timing
