### ISSUE TITLE
keyboard input method doesn't work properly on snap application

### ISSUE THREAD

**Issue by jjangga0214** [canonical-websites/snapcraft.io#1567]
Well, it seems this repo is just for snap.io website, 
but anyway I here report an undesirable behavior of snap applications 
as I couldn't find issue panel on snapcraft's repo and don't have much time to search where to go.

On ubuntu 18.10, I am using ibus as an keyboard input method system and use Korean.
When I install vscode as a snap application for example, I can't use Korean (can use only English).
What's more, fonts installed on system can't be used as well.
However, no similar issue occurs on vscode(of course with same version) installed by .deb file.

So the problem is keyboard input method (and probably access to some other system resources like fonts) does not properly work when using snap apps, at least on ubuntu 18.10. 

It would be thankful if somebody convey this issue to where it should be.

**Comment by therealjuan** [comment]
Thanks for bring this problem to our attention [jjangga0214](/jjangga0214). It will be great if you could post the problem you are describing in the [snapcraft forum](https://forum.snapcraft.io), this will help to redirect the question to the relevant team to looking at this issue.
