### ISSUE TITLE
Privacy policy URL

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#159]
Google Play and Apple App Store encourage — and in some cases, require — publishers to provide a privacy policy URL as part of submitting an app.

We should investigate whether we need to do the same thing for snaps, and if so, how this will affect the layout of the snap Market page.

Can we provide a field for the publishers to enter a link to their privacy policy doc - requires a meeting with the lawyer

**Comment by matthewpaulthomas** [comment]
[I’ve posted to the Snapcraft forum](https://forum.snapcraft.io/t/url-contact-fields-in-snap-metadata/3067) to propose this.

**Comment by matthewpaulthomas** [comment]
I’ve made [a URLs proposal](https://forum.snapcraft.io/t/url-contact-fields-in-snap-metadata/3067/6?u=mpt) in the forum thread, including a “Privacy policy” field.

**Comment by carlaberkers** [comment]
It was agreed in CapeTown to not include the privacy policy on the snap details page in the first instance. Publishers will have this info on their websites, which we will link to on the snap details page. Since this issue is solved for now, we'll close it
