### ISSUE TITLE
Improve media assets interface on snap listing page

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1609]
## Main objective

To provide a better alternative on how we handle media assets in owned snaps. This can include the way we handle Video, Snap Icon as well as general messaging to handle error messages when uploading / handling media assets.

## Background & context
As described in #413 and as part of the roadmap item [s-s#901](https://github.com/CanonicalLtd/snap-squad/issues/901), we can work on improving the way publishers can manage media assets of their published snaps.

* Right now the selection of media types is only visible on mouse hover

* Action bar requires you to discover first the mouse hover and then apply the action (full screen or delete)

* There is no way to understand what any of the icons is doing unless you trial-error

* If you upload an asset that does not conform with the agreed media restrictions, it does not tell you what is the problem with the media assets. See [agreed media restrictions in the snapcraft forum](https://forum.snapcraft.io/t/restrictions-on-screenshots-and-videos-in-snap-listings/3087/17) or [refer to the master epic for this GH issue](https://github.com/CanonicalLtd/snap-squad/issues/901).

![media-assets-listing](https://user-images.githubusercontent.com/8167677/52955421-e7dd7880-338c-11e9-8102-01fd62181e1b.gif)

## Spec
[Further details can be found on the spec here.](https://docs.google.com/document/d/1KgprCc1WiHbtCtTQ1vSP_EIpPaC44U7UAIwTcMSAkhE/edit?usp=sharing)

**Comment by hughesjordan** [comment]
- Deleting one by one is quicker than making selections and then deleting, also no need for a 'select all' function with only a max of 5 screenshots.
- Delete button on the image is explicit in terms of what the action will do.
- New preview listing functionality negates need for full screen button.
- Give visual indication that you can only upload 5 images.
- Include only most important image restrictions on page, more detail within a modal.
- Change label of 'Screenshots' to 'Images' as people may not actually upload a 'screenshot'... a GIF is not a screenshot, edited marketing images are not screenshots etc.

Empty state:
![1.png](https://images.zenhubusercontent.com/5c052434391a6f6357ada9f5/0b2eb26a-a3f2-4e80-a59d-6f208d30b3e2)

Image added:
![2.png](https://images.zenhubusercontent.com/5c052434391a6f6357ada9f5/3821a05f-20ad-46e3-86d7-cf9d56ba73d3)

Multiple images with different aspect ratios:
![3.png](https://images.zenhubusercontent.com/5c052434391a6f6357ada9f5/5652070d-6e6f-4e67-be88-25b7d74fd079)

Error messaging:
![4.png](https://images.zenhubusercontent.com/5c052434391a6f6357ada9f5/be2c9e60-0897-4d3f-9693-d636d503f6a1)

Image restrictions modal:
![5.png](https://images.zenhubusercontent.com/5c052434391a6f6357ada9f5/0ed3351f-3f5f-41f2-9291-ff496878cb0f)

**Comment by hughesjordan** [comment]
@Lukewh Are you able to take a quick look at the designs for this and check they are feasible please? Included the link to the spec above.

**Comment by Lukewh** [comment]
@hughesjordan a couple of comments in the spec, otherwise :+1:

**Comment by Lukewh** [comment]
@hughesjordan one thing that's a limitation and one of the reasons for the complicated interface at the minute is that we only upload/ delete images when the "Save" button is pressed. This means there are states for:
1. An image marked for deletion
2. An image that is new (not yet uploaded)
3. An image that was previously uploaded (just shown as a normal image)

This isn't something I think we'll change anytime soon as the API would require some kind of "upload, but mark as unpublished", but I'll talk to the store team and see what they think

**Comment by therealjuan** [comment]
Not to throw a spanner in the works but i just added all issues related to this behaviour to the Epic.
