### ISSUE TITLE
World map is smaller when Linux distributions are hidden

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/snapcraft.io#1625]
### Expected behaviour
World map should be 'full width'

### Steps to reproduce the problem

1. Go to a snap page which has Linux distributions hidden, but world map shown
2. Scroll down to the world map

### Specs

- _URL:_ http://snapcraft.io/snap-store-proxy
- _Operating system:_ Ubuntu 18.10 Cosmic Cuttlefish
- _Browser:_ Firefox Quantum 65

**Comment by therealjuan** [comment]
Thanks for bringing this into our attention Mr. Collard.
