### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#1649]
Spec: https://docs.google.com/document/d/1KgprCc1WiHbtCtTQ1vSP_EIpPaC44U7UAIwTcMSAkhE/edit#
Zeplin: http://zpl.io/aR1XlON

**Comment by therealjuan** [comment]
issue test

**Comment by Lukewh** [comment]
Related issue:
https://github.com/canonical-websites/snapcraft.io/issues/848
