### ISSUE TITLE
Unable to add screenshots to Snap store listing

### ISSUE THREAD

**Issue by xet7** [canonical-websites/snapcraft.io#1663]
## Expected behaviour
Adding new screenshots works.

## What happens instead
I deleted old screenshots and tried to upload new screenshots, but uploading with 1) + or Add 2) Save does not work, images do not get uploaded.

## Steps to reproduce the problem
Delete screenshots. Try to add new screenthot.

## Specs
URL: https://snapcraft.io/wekan/listing , https://snapcraft.io/wekan
Operating system: Ubuntu 18.04
Browser: Chrome, newest

**Comment by cprov** [comment]
@Lukewh I don't think we are surfacing the new API errors on media restriction as described in https://dashboard.snapcraft.io/docs/api/snap.html#get--dev-api-snaps-(snap_id)-binary-metadata
(particularly 415 and 422 ones).

@xet7 meanwhile, please, ensure your proposed screenshots comply with https://forum.snapcraft.io/t/restrictions-on-screenshots-and-videos-in-snap-listings/3087/10

**Comment by Lukewh** [comment]
@xet7 thanks for the report, can you provide the resolution and mime type of the image you tried?

@cprov we should be returning any error directly, but I'll check

**Comment by xet7** [comment]
@Lukewh 

I was trying to add these screenshots. Previous screenshots were same size as new screenshots. Uploading these does not work at all.

https://wekan.github.io/wekan-markdown.png

https://wekan.github.io/ifttt/rules.png

https://wekan.github.io/wekan-admin-panel.png

https://wekan.github.io/wekan-import-board.png

**Comment by Lukewh** [comment]
Thanks @xet7. It seems that a couple of the images don't conform to the new image restrictions that have been put in place, and the front-end isn't surfacing the errors.
When https://github.com/canonical-websites/snapcraft.io/pull/1712 lands it should give better visibility of any issues as you add images.

**Comment by Lukewh** [comment]
@xet7 if you try uploading again to https://snapcraft.io you should get relevant errors that you can address. Any files that don't have errors should be uploaded as before.

I'm going to close this issue, but please reopen it if you still experience problems.
