### ISSUE TITLE
[Suggestion] Update store page visual design to match the homepage.

### ISSUE THREAD

**Issue by mikeroyal** [canonical-websites/snapcraft.io#1718]
Current Homepage design
![store-front](https://user-images.githubusercontent.com/45159366/54642057-f46af480-4a50-11e9-9819-ee8b764726ec.png)

Current Store design 
![store](https://user-images.githubusercontent.com/45159366/54642177-34ca7280-4a51-11e9-83cc-1178fad7e4f1.png)

New design to match the homepage.
![store-design](https://user-images.githubusercontent.com/45159366/54642183-36943600-4a51-11e9-95ac-e9f211b308b2.png)

**Comment by kwm14** [comment]
Thanks, @mikeroyal next phase we're working towards updating this style on the storefront 👍

**Comment by Lukewh** [comment]
Done here https://github.com/canonical-websites/snapcraft.io/pull/1726 closing :)
