### ISSUE TITLE
Promote Snap Store snap in snapcraft.io

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1722]
We should be promoting the snap store snap in the store front-page so users in Linux will be able to manage software and install snaps using their desktop installed in their laptops.

Here is a candidate design:

![image](https://user-images.githubusercontent.com/8167677/54679374-073c0280-4aff-11e9-9c3e-f1c4c8b7a4fd.png)

![image](https://user-images.githubusercontent.com/8167677/54679355-fd1a0400-4afe-11e9-8425-cbb7bac5f2ed.png)

**Comment by kwm14** [comment]
LGTM 👍
