### ISSUE TITLE
Updated homepage styling

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1725]
Right now the paragraph introducing the homepage is pretty small compared to the headline:

**Old:**
![image](https://user-images.githubusercontent.com/8167677/54701034-0a011c80-4b2c-11e9-8dbc-0e896f1cebfd.png)

**New:**
![image](https://user-images.githubusercontent.com/8167677/54701015-feadf100-4b2b-11e9-9d31-c05c59e233a0.png)

**Comment by Lukewh** [comment]
Done as part of https://github.com/canonical-websites/snapcraft.io/pull/1726 closing
