### ISSUE TITLE
Dead link to snap manual review process

### ISSUE THREAD

**Issue by kreba** [canonical-websites/snapcraft.io#1739]
The documentation links to the manual approval process for a snap that wants to be published in "classic" confinement mode. Links found on:
https://docs.snapcraft.io/snap-confinement/6233
https://docs.snapcraft.io/releasing-your-app/6795

They link to:
https://docs.snapcraft.io/process-for-reviewing-classic-confinement-snaps/1460

But that's a 404.

### Expected behaviour
Get info about why a snap might legitimately require free reign on my machine.

### Steps to reproduce the problem
Klick on one of the links listed above.

### Specs
"Specifications"? Dunno what to say here.

- _URL:_ https://docs.snapcraft.io/process-for-reviewing-classic-confinement-snaps/1460
- _Operating system:_ Ubuntu (any)
- _Browser:_ Firefox (any)

**Comment by evandandrea** [comment]
It looks like https://docs.snapcraft.io/process-for-reviewing-classic-confinement-snaps/1460 got moved to the store category, breaking links. @degville would you agree that it should move back to docs?

**Comment by degville** [comment]
sorry for not responding to this earlier - I fixed the page category when this issue was raised but didn't update this issue: https://docs.snapcraft.io/process-for-reviewing-classic-confinement-snaps/1460 no longer returns a 404.

Thanks for flagging this @kreba, and for the hint @evandandrea.
