### ISSUE TITLE
Split the homepage markup into global templates used across the site

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#174]
The header and footer should be unified across the site, so all the wrapper markup should be in a central template used by the homepage, the discover and search pages and the snap details pages.

**Comment by shivjoshi1996** [comment]
Could @nottrobin @matthewpaulthomas @carlaberkers have a meeting about this

**Comment by bartaz** [comment]
Current home page navigation is as follows:

<img width="1077" alt="screen shot 2017-12-08 at 10 48 08" src="https://user-images.githubusercontent.com/83575/33760257-5fb525d2-dc05-11e7-903e-419da9f4bf30.png">

Other pages (discover, search, snap details) have only logo in header for now.

We could rather easily make the navigation common across all the pages.

**Comment by matthewpaulthomas** [comment]
I’d be delighted to have more consistent headers and footers.

As far as I know, snapcraft.io currently has six sets of headers and footers (not counting “Tutorials”):
1. [snapcraft.io/](https://snapcraft.io/)
1. [build.snapcraft.io](https://build.snapcraft.io/)
1. [docs.snapcraft.io](https://docs.snapcraft.io/)
1. [forum.snapcraft.io](https://forum.snapcraft.io/) (header only, no footer)
1. [status.snapcraft.io](https://status.snapcraft.io/) (header only, no footer)
1. [snapcraft.io/discover](https://snapcraft.io/discover/) and snap pages.

I propose that we work towards having two sets:

1. a header and footer for all developer-facing pages

    ![header](https://user-images.githubusercontent.com/19801137/33761661-bf493d70-dc01-11e7-8714-efb87dc1d623.png)

    ![footer](https://user-images.githubusercontent.com/19801137/33761687-d1b6b9b0-dc01-11e7-926b-b28e51afa491.png)

1. a header and footer for the directory.

    ![header](https://user-images.githubusercontent.com/19801137/33761354-9ebb54c2-dc00-11e7-898b-ac361db81c71.png)

    ![footer](https://user-images.githubusercontent.com/19801137/33762755-a5e0c886-dc05-11e7-8d63-70b232329ef4.png)

Why two, and not just one? So that:
- publishers aren’t annoyed that the search field returns other people’s snaps, rather than just information about publishing snaps (and maybe about their own published snaps)
- the forum isn’t flooded with posts from end users
- end users aren’t shown a “Sign in” link that couldn’t take them anywhere coherent (we know what snaps a device has installed, but we don’t know what non-paid snaps an end user has installed)
- the directory footer doesn’t imply that we hold the copyright over individual snaps, logos, descriptions etc
- end users don’t think that “Report a bug” is a place to report a bug about a snap or its listing
- end users aren’t surprised that the social channels are all geeky developer stuff, rather than suggestions of interesting snaps ([comparison 1](https://twitter.com/appstore), [comparison 2](https://twitter.com/GooglePlay)).

As @nottrobin said yesterday, directory users should be able to find their way to developer info. But there are many ways to do that without introducing these problems. The “Publish your own snaps” link I show in the footer above is just one possibility.

Further, I propose that the footer contain a slot for inserting page-specific legal statements. This would allow fixing #150, where snapcraft.io/ and every page on docs.snapcraft.io currently includes a statement about Yocto merely because we mention Yocto on two pages.

**Comment by bartaz** [comment]
Is http://snapcraft.io developer facing or "directory"? Or both?

It seems that both developer facing pages and directory are (and will be) part of the same application (snapcraft.io). So it seems we will need to have two separate layouts in there anyway?

**Comment by nottrobin** [comment]
I think there should be one navigation on snapcraft.io (the main domain). Other subdomains should have distinct navigations. I think whether we can unify things under one header should be the rationale by which we decide to split things into subdomains or not. If a "domain" means anything it should mean a set of related pages for a similar audience achieving a similar goal.

So to be more specific, I think it's absolutely fine at this point to acknowledge that the snapcraft.io, the top level domain (let's ignore build., forum. etc. for now) is somewhat build-focused. This is why the homepage mostly talks about building snaps. And I don't see why users of the website wouldn't understand that.

I don't think we should act as if we're building play.google.com or the Apple Store, because firstly users of Linux software *are* much more geeky and are much more likely to care about building software, or filing bugs, and will be much more used to finding "geeky" forums etc. And secondly because at this stage in its development, we simply are very deliberately and understandably focusing on communicating how easy it is to build snaps, and getting as many people to give it a go as possible.

We of course have absolute freedom to change this in the future, remove more build-specific navigation items, or move them somewhere else. But for now, I really think we should let the "two worlds" overlap, by using a single unified header across https://snapcraft.io.

> Further, I propose that the footer contain a slot for inserting page-specific legal statements. This would allow fixing #150, where snapcraft.io/ and every page on docs.snapcraft.io currently includes a statement about Yocto merely because we mention Yocto on two pages.

This is definitely over-engineering. The Yocto-specific disclaimer was never a good idea. We can and definitely should choose generic wording and disclaimers that can apply across the board.

**Comment by nottrobin** [comment]
> end users don’t think that “Report a bug” is a place to report a bug about a snap or its listing

I thought we took care of this by making the footer slightly grey. I really don't think this needs to be made any more obvious, without clear evidence that people are confused. I doubt they are.

**Comment by matthewpaulthomas** [comment]
> I think whether we can unify things under one header should be the rationale by which we decide to split things into subdomains or not … How widely to draw those domains can be debated, but once we've decided to make a domain it should then have a unified navigation.

As shown in the “Snappy URLs” proposal, I _also_ think developer pages should be on a separate subdomain from directory pages — so if we did both, we’d both be happy ;-) — but I think that’s mostly irrelevant to what global navigation they should have.

Perhaps the most common example is checkout pages. On many sites — for example, [buy.ubuntu.com](https://buy.ubuntu.com/) — checkout pages reduce, or almost completely omit, global navigation despite being on the same domain. You can agree or disagree about whether that’s a good idea, without caring or even knowing whether checkout pages have a subdomain to themselves.

A more pertinent example is [Docs](https://docs.snapcraft.io/). It’s absolutely “for a similar audience achieving a similar goal” as [snapcraft.io/](https://snapcraft.io/), and its header navigation is exactly the same as snapcraft.io/, except for inconsistent layout which is obviously unintentional. If “other subdomains should have distinct navigations”, then moving Docs from snapcraft.io/docs to docs.snapcraft.io was a mistake. Again, I think the domain is irrelevant: their headers should be identical _regardless_ of whether Docs has its own subdomain.

> I thought we took care of this by making the footer slightly grey.

That wasn’t the reason I wireframed a grey footer. Instead, I took care of it by specifying that the link in the directory footer should be “Report a bug about the directory”. The copyright and social-media issues, which I listed above, I similarly handled by speccing a different footer for directory pages than for developer-centric pages.

**Comment by nottrobin** [comment]
> As shown in the “Snappy URLs” proposal, I also think developer pages should be on a separate subdomain from directory pages — so if we did both, we’d both be happy ;-) — but I think that’s mostly irrelevant to what global navigation they should have.

Yes, your preferred domain model of putting developers in a separate domain from consumers can certainly fit domain rules. I just disagree with you that this is how we should draw our domains - I think for the time being we could consider one domain containing both developers and consumers, because not only is there significant overlap, but for the time being we want to *encourage* overlap.

> A more pertinent example is Docs

This is indeed a pertinent example. 

> It’s absolutely “for a similar audience achieving a similar goal” as snapcraft.io/

As I said, we can probably will argue over where the domains are drawn. I would say that the although the *audience* for docs.snapcraft.io certainly overlaps signficantly with the audience for snapcraft.io, the *goal* is quite different. snapcraft.io is a place for managing your snaps (whether ones you've built or ones you've installed), and the goal of visiting docs.snapcraft.io is to learn about the snap system. In fact we could expand the definition slightly here to say that a service solving a different problem but for the same audience is an ideal case for a subdomain. But as I say, where we draw the distinction between domains is nuanced and up for debate, all I really care about is that we try to remain true to the domains once we've drawn them.

> and its header navigation is exactly the same as snapcraft.io/, except for inconsistent layout which is obviously unintentional

The inconsistent layout was intentional. It may we something that we change our mind about, but it was deliberately done because we believed people expect a different experience when reading documentation than they do when reading a brochure site or browsing a store - a left-aligned, wider experience is more consistent with other documentation. Anyway, this is neither something I feel strongly about or relevant to this discussion, but I just wanted to point out it wasn't unintentional.

> If “other subdomains should have distinct navigations”, then moving Docs from snapcraft.io/docs to docs.snapcraft.io was a mistake.

The navigation you're talking about actually purely contains the homepages of separate domains - build, docs, tutorials, forums. It's a list of the different services we provide that are all related to snaps. It makes absolute sense to me that this list would be propagated across all the separate domains, similar to the global nav on https://www.ubuntu.com and related sites, or the one on https://www.bbc.co.uk (although they of course haven't used subdomains - they designed and built their site in "domains", without using domains). But, just like on those sites, there can be differences in look and feel between domains. And absolutely this list should exist right across the domain.

The important point is that the unified header across a domain should be *considered independent* to some extent - in that:

- consistency across the domain
- structure inside the domain can be changed in one place and that change will apply across the domain
- pages within one domain know their place in that domain and how they link to other pages in the same domain

Without these guidelines we end up in a world where changes and links can come from any direction, which is confusing for both us and the users.

(The navigation of docs.snapcraft.io does need looking at and will change)

> Perhaps the most common example is checkout pages. On many sites — for example, buy.ubuntu.com — checkout pages reduce, or almost completely omit, global navigation despite being on the same domain. You can agree or disagree about whether that’s a good idea, without caring or even knowing whether checkout pages have a subdomain to themselves.

This is definitely an interesting exception to the rule. I don't agree that we can have opinions about the checkout flow *regardless* of domain. In terms of domain thinking, the checkout flow is an interesting grey area, but that doesn't mean considerations about its domain are irrelevant. (Personally I'm not a big fan of the idea, I find it very annoying that I can't choose to return to my basket or suddenly decide to search for something else half way through checkout)

> That wasn’t the reason I wireframed a grey footer. Instead, I took care of it by specifying that the link in the directory footer should be “Report a bug about the directory”. The copyright and social-media issues, which I listed above, I similarly handled by speccing a different footer for directory pages than for developer-centric pages.

Okay so either way it's solved. Good.

**Comment by matthewpaulthomas** [comment]
I listed five specific problems above which are avoided by us deliberately giving developer-facing and end-user-facing pages a different header and footer. To “just roll the existing global nav across all the existing pages” (which, if we’re disregarding subdomains, really means “the subset of pages that are currently provided by the snapcraft-flask codebase”) would introduce the first problem as soon as a snap search field is placed in the header, and it would introduce the other four problems immediately.

If I understand correctly, the argument for doing this is that the second and fifth problems are not problems, but actually desirable. Even if that was true, it doesn’t address the other three.

**Comment by nottrobin** [comment]
My opinion on why each of those isn't much of an issue:

> publishers aren’t annoyed that the search field returns other people’s snaps, rather than just information about publishing snaps (and maybe about their own published snaps)

If the site is known to be a unified portal for snaps, and the search box is labelled as place to search for snaps, I don't see why this would be either surprising or annoying for publishers.

> end users aren’t shown a “Sign in” link that couldn’t take them anywhere coherent (we know what snaps a device has installed, but we don’t know what non-paid snaps an end user has installed)

This will be a temporary problem - we could absolutely show users a list of snaps they have installed fairly easily. If this was a serious blocker, we could wait until we have implemented this. However, as we are aiming to suggest to all users that they could also become publishers, it seems reasonable to allow them to log in and then just inform them that they haven't yet published any snaps. If they log in 'cos they're curious then maybe they're curious enough to try publishing something.

> the directory footer doesn’t imply that we hold the copyright over individual snaps, icons, descriptions etc

Reduce it to simply "Ubuntu and Canonical are registered trademarks of Canonical Ltd."?

> end users don’t think that “Report a bug” is a place to report a bug about a snap or its listing

This is already solved by more specific wording.

> end users aren’t surprised that the social channels are mostly geeky developer stuff, rather than suggestions of interesting snaps ([comparison 1](https://twitter.com/appstore), [comparison 2](https://twitter.com/GooglePlay)).

Yes, I'm saying "surprising" them in this way at this point in snap's evolution is no bad thing.

**Comment by matthewpaulthomas** [comment]
Progress from today’s meeting:

> - end users aren’t shown a “Sign in” link that couldn’t take them anywhere coherent (we know what snaps a device has installed, but we don’t know what non-paid snaps an end user has installed)

It’s possible that a single “Sign in” link, across developer and end-user pages, could take you to a single “Account” page that showed (a) what snaps you’ve published, if any; (b) what stores you admin, if any; and (c) what non-paid snaps you’ve _purchased_ (though not all snaps you’ve installed). This would need a bit of design work to see if it makes sense (for example, balancing the use cases of “The store I was admin of yesterday isn’t showing up today, why?” vs. “I’ve never been a store admin, never will be, and don’t even know what that is”).

> - the directory footer doesn’t imply that we hold the copyright over individual snaps, icons, descriptions etc

This may not be a problem after all: Google Play’s footer says simply “©2017 Google”, while itunes.apple.com says “Copyright © 2017 Apple Inc.” (though it also has “© {publisher name}” in the body of the page).

> - end users don’t think that “Report a bug” is a place to report a bug about a snap or its listing

This could be fixed with the same non-Canonical report-a-bug text on developer and end-user pages (as specced for #130 anyway).

That leaves the two other problems for discussion next month. We also discussed domains/subdomains, and I’ve reported [snapcraft-design#205](https://github.com/CanonicalLtd/snapcraft-design/issues/205) about that.

**Comment by bartaz** [comment]
Splitting template and reusing common layout across pages in snapcraft.io is done already.

Consistent navigation is discussed and implemented separately already as well.
