### ISSUE TITLE
"Latest release" column shows "Not Released" for all snaps (https://snapcraft.io/snaps)

### ISSUE THREAD

**Issue by Roadmaster** [canonical-websites/snapcraft.io#1749]
### Expected behaviour
The "Latest release" column should show when a snap's latest release was made.

### Steps to reproduce the problem

- Visit https://snapcraft.io/snaps
- Confirm "Latest release" shows "Not Released" for all snaps (see attached screenshot)

### Specs

- _URL:_ https://snapcraft.io/snaps
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox 65.0.1
![Screenshot_2019-03-26  My published snaps — Linux software in the Snap Store ](https://user-images.githubusercontent.com/15329/55029092-9a81a600-4fdf-11e9-9303-2025b982d22d.png)

**Comment by bartaz** [comment]
@Roadmaster @cprov 

Did something change in the API?
We are checking if snap status is "Published", but now it says "Approved" instead.

**Comment by Roadmaster** [comment]
From Celso:

https://dashboard.snapcraft.io/docs/api/account.html#get--dev-api-account, look for `status`
there might be a confusion between the `snaps[].status` and `latest_revisions[].status` 
the doc is not explicit about the differences

**Comment by bartaz** [comment]
Thanks, yes it seems that we used to read `latest_revisions[].status` and it was changed to `snaps[].status` by mistake at some point.
We will get back to reading status of revision.

**Comment by cprov** [comment]
@bartaz 
For future reference:

*  `.snaps[].status` is one of `["Approved", "Revoked", "DisputePending"]`
*  `.latest_revisions[].status` is one of `["Published",  "ReviewPending", "Rejected"]`
