### ISSUE TITLE
“Legal information” is completely irrelevant

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#177]
1\. Follow the “Legal information” link in the footer of any snapcraft.io page that has one.
2\. Try to find any information about snaps or Snapcraft on the linked page.

What happens: It doesn’t mention snaps or Snapcraft at all. And neither does any of its subsidiary pages.

What should happen:
- If there is no legal information relevant to snaps or Snapcraft, the link should not be present.
- If there is, the link should go to the right place.

**Comment by shivjoshi1996** [comment]
Related to the yocto disclaimer

**Comment by Greggless** [comment]
### Relevant legal information 
- [Ubuntu developer legal info](https://www.ubuntu.com/legal/terms-and-policies/developer-terms-and-conditions) Although this is not specific to snaps and only refers to the 'Developer site'
- [Canonical contributor license agreement](https://www.ubuntu.com/legal/) Again not mention of snaps, but is probably relevant...

**Comment by Greggless** [comment]
Developers, if so inclined, will need to look for the relevant legal information [ [1](https://www.ubuntu.com/legal/terms-and-policies/developer-terms-and-conditions) , [2](https://www.ubuntu.com/legal/contributors) ]

**Comment by matthewpaulthomas** [comment]
@Greggless you dug more thoroughly than I did, well done. But I think it’s still a problem that the page _seems_ completely irrelevant, because the relevant information is far too deep (and because it’s Ubuntu branded). Instead it looks like a copy-paste error.

> - [Ubuntu developer legal info](https://www.ubuntu.com/legal/terms-and-policies/developer-terms-and-conditions) Although this is not specific to snaps and only refers to the 'Developer site'

To find this you need to choose “Legal information”, then “Terms and policies” (1st of 5 items), then “Terms and conditions for developers” (7th of 10), and then guess that it’s referring to dashboard.snapcraft.io though it doesn’t say so!

> - [Canonical contributor license agreement](https://www.ubuntu.com/legal/) Again no mention of snaps, but is probably relevant...

To discover the relevance you need to choose “Legal information”, then “Contributor agreement” (3rd of 5 items), then “open source projects” (which takes you to a separate Web site, with its own cookie warning), and then find “Snapcraft” and “Snappy” in the list (30th and 31st of 60). The chance of anyone doing that is remote.

One way of improving this would be to flatten ubuntu.com/legal so that the various “Terms and policies” (at least) are listed on that page rather than on a secondary page. But I think the best solution is for snapcraft.io to have its own legal page. This would also fix the problem of ending up at Ubuntu-branded pages.

**Comment by Greggless** [comment]
As a solution, 'legal information' will point to the new Trademarks section. Developers have to confirm T&Cs of the developer agreement before creating an account. So if they are so inclined, they have the opportunity to read it there too. 

It's not pretty, but it's a solution. Maybe this is an issue to take up with T&Cs that live on Ubuntu.com?

**Comment by therealjuan** [comment]
Closing as we urgently require snapcraft.io to have links to our Legal Information and Data Privacy pages. There will be future updates on content
