### ISSUE TITLE
Store tab is highlighted on snapcraft.io/first-snap

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1771]
### Expected behaviour

No tab is highlighted on https://snapcraft.io/first-snap

### Steps to reproduce the problem

1. Go to https://snapcraft.io/first-snap
2. The Store tab is highlighted on https://snapcraft.io/first-snap

**Comment by hughesjordan** [comment]
I've also just spotted this occurring when you are within the 'Releases' or 'Publicise' tab of a snap you own.
