### ISSUE TITLE
FSF improvements - update styling of breadcrumb

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1782]
<img width="496" alt="Screenshot 2019-04-05 at 08 31 04" src="https://user-images.githubusercontent.com/83575/55607706-2bddde80-577d-11e9-98ae-2a5095e07b25.png">

**Comment by hughesjordan** [comment]
@bartaz I don't think we need this one anymore, the breadcrumbs/steps should remain disabled until you have progressed past that step.

**Comment by bartaz** [comment]
@hughesjordan Right, I noticed the decision in the comments. I'll use this issue to update the style of breadcrumb (give it a 'snapcraft' background').

**Comment by hughesjordan** [comment]
👍🏻👍🏻
