### ISSUE TITLE
FSF improvements - show publisher pages screenshots

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1784]
<img width="592" alt="Screenshot 2019-04-05 at 08 38 19" src="https://user-images.githubusercontent.com/83575/55608164-30ef5d80-577e-11e9-8a34-72a68ed390a9.png">

**Comment by bartaz** [comment]
@hughesjordan Do we have screenshots that we want to show? The second screenshot in the design shows functionality that is not yet implemented (graph on snaps list page).

Also, we need real copy to put under 'Publish now'

**Comment by hughesjordan** [comment]
@bartaz If you check the Zeplin project it now has copy, but the middle image is still an issue, I'll see if I can find a suitable replacement for now.

**Comment by hughesjordan** [comment]
@bartaz here is an image i've thrown together until we have the shiny new dashboard:

https://drive.google.com/open?id=1niUAWaCsYRl1NS71i0Bxe8KlaYPNfs0z
