### ISSUE TITLE
Ubuntu logo is squashed on front page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#179]
1\. Go to [snapcraft.io](https://snapcraft.io/).
2\. Look at the Ubuntu logo.

What you see: The logo is slightly too tall or too narrow.

![179-ubuntu-logo](https://user-images.githubusercontent.com/19801137/33769799-71f0fe56-dc23-11e7-9caa-3f09196f49c3.png)

What you should see: The logo is not squashed. Something like this:

![179-ubuntu-logo-fixed](https://user-images.githubusercontent.com/19801137/33770397-4de38338-dc25-11e7-9fd3-d6bce1773973.png)

[Originally noticed by @carlaberkers.]

**Comment by lyubomir-popov** [comment]
@bartaz I've update the file and uploaded it to the asset manager:
https://assets.ubuntu.com/v1/4e18e57c-logo-ubuntu--in-card.png
