### ISSUE TITLE
Investigate unified “Account” page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#183]
Today’s discussion of snap developer pages vs. snap end-user pages produced the idea of a single “Account” page, that would list:
1. what snaps you’ve published, if any;
2. what stores you administer, if any; and
3. what paid snaps you’ve purchased, if any.

We need to investigate whether this page would be practical, catering for users with very different levels of involvement in and knowledge of snaps. For example:
- an app developer who, over the years, has published 60 snaps and purchased 71;
- an enterprise admin who administers two stores, but doesn’t purchase any snaps on their own account;
- an end user who has purchased a few snaps, but who will never know or care what it means to admin a store.

**Comment by carlaberkers** [comment]
We'll investigate this as part of the snapcraft vision work.

Closing this for now and we can include it in the workshop

**Comment by matthewpaulthomas** [comment]
We haven’t had time to investigate this as part of the Snapcraft vision work. But it came up again just now with the store team reviewing the prototype.

One issue is that a developer will almost always have installed their own snaps for testing. (This fits with my example above of “an app developer who, over the years, has published 60 snaps and purchased 71”.) Showing both lists on the same page would be quite repetitive. (This is masked by the prototype currently showing a publisher who hasn’t installed _any_ of their own snaps.)

Another issue is that if the empty state for published snaps, or for stores, was anything more than _extremely_ subtle then it could be confusing to end users.
