### ISSUE TITLE
Build your first snap leads to tutorials.ubuntu.com

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#194]
### What currently happens:
- The `[build your first snap]` btn leads to https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0
### What should happen:
- As spec'd in the [copy doc](https://docs.google.com/a/canonical.com/document/d/1f0JLEcM3d9eAbM-adKaN96E9wWYGCyUSsmjQDbTa0l8/edit?usp=sharing) the `[Build your first snap]` btn should lead to [the language guide overview](https://docs.snapcraft.io/build-snaps/)

**Comment by shivjoshi1996** [comment]
check staging as it might be fixed already

**Comment by caldav** [comment]
@Greggless shouldn't it lead to https://docs.snapcraft.io/build-snaps/languages?

**Comment by Greggless** [comment]
My mistake @caldav, forgot the `/languages` off the end.

Staging has it correct so when we can next deploy, it'll be fixed.

Closing.
