### ISSUE TITLE
Problem with Alsa in Snap version of Spotify

### ISSUE THREAD

**Issue by g3t0r** [canonical-websites/snapcraft.io#210]
I'm using Xubuntu 16.04, on xfce spotify plays songs, but on i3-wm it throws:
Cannot access file /usr/share/alsa/alsa.conf

Debian-packaged version of spotify doesn't have this problem

**Comment by evandandrea** [comment]
@g3t0r this is a place for tracking problems in the snapcraft.io website, not for individual snaps. You can use https://forum.snapcraft.io for user-to-user support, or Spotify's own forum: https://community.spotify.com/t5/Desktop-Linux/bd-p/desktop_linux
