### ISSUE TITLE
Support connecting to the staging API for local development

### ISSUE THREAD

**Issue by tbille** [canonical-websites/snapcraft.io#218]
We need developers to use staging urls for dashboard ans snapcraft so that they can have dumb data for their snaps.

This is so that we can fake the statistics for certain snaps, for the purpose of testing out the metrics pages.

We should keep the application defaulting to use the main API, but allow the API locations to be overridden if certain environment variables are present.

**Comment by shivjoshi1996** [comment]
Opened in the wrong repo (epics should be in snappy-design-squad repo). Epic moved here https://github.com/CanonicalLtd/snappy-design-squad/issues/324
