### ISSUE TITLE
How to handle user authorization in a backend-first architecture

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#22]
In this application, we've opted at the moment to put the core application functionality for building the Markup for presentation in the Flask application and the related templates on the server-side, rather than pushing that responsibility to a Single Page Application (SPA) in the client browser by using a frontend framework like React - which is how [build.snapcraft.io](https://github.com/canonical-websites/build.snapcraft.io) was built.

@cprov raised some concerns about this choice, partly in https://github.com/canonical-websites/snapcraft-flask/pull/11#pullrequestreview-60035167. Here I'll first explain the decision and then discuss the one downside that I don't quite know how to address yet.

## Benefits of a backend-first architecture

There are a few reasons that we've made this decision:

- Our experience with build.snapcraft.io has taught us that it is difficult to encapsulate and manage complexity in a SPA. Seemingly simple additions or removals require changes in many parts of the application.
- Similarly, it is difficult to keep track of the application's state. It is easy to end up with subtle bugs where very specific flows through the application lead to a broken state.
- The webteam at large has more experience building traditional back-end focussed applications, and so we believe we have successful patterns for doing so
- Similarly, as we have many applications that use a similar architecture, this structure makes it easier to share knowledge, modules and patterns with other projects

The choice between this traditional architecture vs a SPA architecture certainly depends on the type of application. For an application that is for, the most part, an interactive experience with complex flows and interactions (like, for example, [the Juju GUI](https://jujucharms.com/new/)) an SPA is definitely the way to go. In contrast, an app that is mostly made up of pages/views - where the user moves from one view to the next - is probably more suited to a traditional architecture. We believe that, as snapcraft.io is intended to be the home of the snap store, this would certainly fits closer to the latter type of application.

Neither is this a binary choice. An SPA will certainly push certain bits of functionality to the server, and similarly, a backend-first architecture can push as much interactive functionality to the client as makes sense.

## User authentication and authorization

The most significant downside to this architecture that I'm aware of is that of how to manage permissions for users when talking to the API.

In the traditional server-first model, the server-side application would simply be given fairly permissive access to the API, allowing it to access all the data it could possibly need. The application itself would then be responsible for authenticating users and managing their permissions.

An SPA model offers the benefit that the user's browser (the client) can communicate directly with the API, which allows the API to be the one that verifies end-users directly and delegates permissions for accessing data etc. This is particularly beneficial for cases like the Snap Store, because it means these permissions can be more easily managed in the same way and the same place for users of the website as they are for users of the CLI.

We would certainly want to continue this pattern here - to delegate management of user permissions to the Store. However, our architecture choices do mean that we would like the server-side application, rather than the client's browser, to be retrieving the data from the API and crafting it into a response.

I believe this is eminently possible, that [macaroons](http://evancordell.com/2015/09/27/macaroons-101-contextual-confinement.html) should help us to manage this delegation of authentication from the user to the backend application. We should continue to discuss how this solution could look, here and elsewhere.

**Comment by bartaz** [comment]
@nottrobin Does it makes sense to keep it around as part of https://github.com/CanonicalLtd/snappy-design-squad/issues/165 authentication API epic?

**Comment by nottrobin** [comment]
@bartaz yes I would say so. Good shout.

**Comment by nottrobin** [comment]
This will be fleshed out in the authentication work:
https://github.com/CanonicalLtd/snappy-design-squad/issues/165

We know the rough shape of what we're implementing, and further issues can be filed after the first pass is implemented.

Closing here.
