### ISSUE TITLE
Why is cache only 5 seconds?

### ISSUE THREAD

**Issue by tbille** [canonical-websites/snapcraft.io#224]
@nottrobin 
Do you know why the cache has been setted at 5 seconds? It seems pretty useless...

```python
# The cache expires after 5 seconds
cached_session = requests_cache.CachedSession(expire_after=5)
```

**Comment by nottrobin** [comment]
Because we don't want to serve stale data (so we don't want a long cache) but there is a huge benefit to caching for a short period, because it means 1000 requests in a second *don't* result in 1000 API calls.
