### ISSUE TITLE
Missing link to dashboard from home page

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/snapcraft.io#235]
There's no link to the dashboard from the snapcraft.io homepage. Steps to reproduce:

1. Visit https://snapcraft.io/
2. Look for link to "my snaps" or other link to https://dashboard.snapcraft.io/
3. Close browser tab with :cry: after not finding it.

**Comment by Greggless** [comment]
Hey @sparkiegeek 

I'm going to close this as we're actively working on a solution to this issue. There are a few moving parts that we need to take into consideration before adding a link to the navigation. Thanks! 😄
