### ISSUE TITLE
blacklist keybase.txt name

### ISSUE THREAD

**Issue by setharnold** [canonical-websites/snapcraft.io#249]
Hello, I'm not sure where this bug should be filed, and it's a bit involved.

The backstory: https://twitter.com/EdOverflow/status/954093588362809345

"I claimed ownership of http://liberapay.com  on Keybase by creating a user called "keybase.txt" and placing the verification snippet in the profile's description."

It looks like snapcraft.io/<snapname> loads user-supplied content: https://snapcraft.io/hello/ https://snapcraft.io/slack/ and so on.

So I suspect someone could pull the same trick on our snap store and thus claim snapcraft.io in keybase via this url: https://snapcraft.io/keybase.txt

Hopefully the keybase team will modify their tooling to require text/plain responses or something similar. But in the meantime it might be worth blacklisting snaps with the name keybase.txt.

Perhaps other similar magic file names from other service providers should also be blacklisted.

Thanks

**Comment by cprov** [comment]
Hi Seth, thanks for reporting this potential problem.

`keybase.txt` is not a valid snap name, DOT is not allowed. That rules out many problems, but not all. The store also has a huge set of reserved (read currently blacklisted) names, which no user can claim.

Please, let us know if you can think of any possibility of unexpected behavior.
