### ISSUE TITLE
Wrong organization and license shown for HTMLDOC snap!

### ISSUE THREAD

**Issue by michaelrsweet** [canonical-websites/snapcraft.io#252]
Hi,

I finally found a way to get HTMLDOC's GUI working when installed as a snap, and just released it to the snap store, but it is showing up as coming from the ISTO Printer Working Group with a proprietary license.

It should show me (Michael R Sweet) as the originator with the GPL2 as the license.

How do I fix this?

**Comment by Greggless** [comment]
Hi Michael!

Congrats on snapping your app and getting it to the store 🚀 👏 

It looks as though your snap is displaying correctly in the [snap store](https://snapcraft.io/htmldoc)

Could you point us to, or provide and screenshot of, where you're seeing the error, please?

**Comment by michaelrsweet** [comment]
I was able to track down the proper place to fix my "vendor" information as well as the license, icon, and screenshots for htmldoc - might be nice to include a direct link to the registration page on snapcraft.io ("register or update your snaps").

**Comment by Greggless** [comment]
Aha, duly noted. Thanks for providing feedback!

I'll close this issue now.

Happy snapping
