### ISSUE TITLE
icon field so far is not working

### ISSUE THREAD

**Issue by liu-xiao-guo** [canonical-websites/snapcraft.io#264]
http://snapcraft.io/docs/build-snaps/metadata

==================================================
Package icon

Providing an icon for your snap is important, even for command-line applications, if for nothing else than discoverability from management interfaces such as store fronts like snapweb.

To use an icon to represent the snap, just declare a PNG or SVG in snapcraft.yaml through an icon entry with a path relative to the icon inside the snap.
===================================================

icon is not working. the correct icon should be in the directory setup/gui/xxx.png

**Comment by caldav** [comment]
The icon field bug has been fixed.
