### ISSUE TITLE
[Website] "Learn More" links sending non-Ubuntu users to Ask Ubuntu for snap support.

### ISSUE THREAD

**Issue by teward** [canonical-websites/snapcraft.io#271]
For the record, [I am a moderator on Ask Ubuntu](http://askubuntu.com/users/10616/thomas-ward).  Currently, the snapcraft.io website has the Ask Ubuntu website listed under the "Learn More" section like so:

> **Learn more**
> 
> Want to know more about snaps, snapd, Snapcraft and Ubuntu Core?

**Ask Ubuntu, as a policy, does not support non-Ubuntu operating systems or non-official variants (Mint, Kali, etc.).**  That said, due to the policy, we are pushing towards not providing support for snaps, snapd, etc. on non-Ubuntu systems on Ask Ubuntu, and only support the Ubuntu operating system here.

We would like the links updated, such that:

1. A comment next to the Ask Ubuntu link states "(Ubuntu systems only)".

2. (If Unix & Linux mods approve) Add a link below the Ask Ubuntu link to [Unix and Linux](https://unix.stackexchange.com) with a comment next to it saying "(Non-Ubuntu systems)" or similar.

3. Worst case, the Ask Ubuntu link is removed completely from the "Learn More" section.

I will have to check with the Unix and Linux mods on number 2 here, but number 1 or number 3 should be acted upon faster.

**Comment by teward** [comment]
[Related Ask Ubuntu Meta post](http://meta.askubuntu.com/q/16672/10616), and [my response to the inquiry on the site as a Moderator](http://meta.askubuntu.com/a/16689/10616) with the affirmation that this is a discussion that, at its core, is regarding "whether we support other operating systems than Ubuntu", which we don't on Ask Ubuntu.

**Comment by teward** [comment]
@caldav made a proposal on the PR that will be satisfactory and should be included.  thanks!

**Comment by teward** [comment]
@caldav Any progress on this?

**Comment by matthewpaulthomas** [comment]
This is fixed now: “Learn more” links to forum.snapcraft.io, rocket.ubuntu.com, and stackoverflow.com.
