### ISSUE TITLE
Map on directory page is unedifying for a brand-new snap

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#279]
When a snap has been released for only a few minutes or hours, the directory page still ends with a world map. Unsurprisingly, it’s a wasteland.

![snap-page-map-empty](https://user-images.githubusercontent.com/19801137/35692584-9f66b672-0730-11e8-9342-2df60e1fa9dc.png)

Probably we should not show the map until there is data to show.

**Comment by Lukewh** [comment]
This was fixed when the metrics toggles were added :+1:!
The map won't be shown if:
a) The territories toggle is off
b) The territories toggle is on and there are 0 users
