### ISSUE TITLE
Clarify devmode snaps to not get refreshed daily

### ISSUE THREAD

**Issue by lutostag** [canonical-websites/snapcraft.io#281]
## Summary

Clarification for https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1665102/comments/1 would be great to have in the docs. I was thinking a good place might be in https://snapcraft.io/docs/core/usage under 'Developer mode'

Not sure if this is the right repo or if there is a docs repo this bug should be moved to (where the actual content of this repo lives)...

Thanks!

**Comment by anthonydillon** [comment]
Thank you for bring this up @lutostag. @evilnick would you mind taking a look at this?
