### ISSUE TITLE
Implement opening screenshots in lightbox

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#287]

**Comment by anthonydillon** [comment]
The gallery we are considering for Vanilla is the one maas.io used, For example: https://maas.io/tour.

It use's [venobox](http://veno.es/venobox/). Here is an [example of its usage](https://github.com/canonical-websites/maas.io/blob/master/templates/tour.html#L23) on maas.io and has some [modifications to the styling](https://github.com/canonical-websites/maas.io/blob/master/static/sass/_patterns_modal.scss). All of which have been signed of by UX and design.

**Comment by Lukewh** [comment]
I agree with @bartaz, I'd like to avoid adding a jQuery dependency generally (it seems like all lightboxes rely on jQuery!?) to snapcraft.io, we don't need it for anything else currently. 
I also don't imagine our lightbox requirements (and Vanillas) would be out of scope for rolling our own, that we could publish to npm.
