### ISSUE TITLE
"GitHub builds" button

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#288]
Hi,

Can we please have a button on snapcraft.io for "GitHub builds" (I'm open to name suggestions) that points to https://build.snapcraft.io?

Can we set that up but not land it on production until we're ready to publicly launch https://build.snapcraft.io?

Thanks

**Comment by pmahnke** [comment]
@evandandrea I assume this is the 'going live' moment.

**Comment by evandandrea** [comment]
Yes

**Comment by matthewpaulthomas** [comment]
This looks fixed now: right next to the “Learn to craft your first snap” button is a link, “or Auto-build and publish from your GitHub repos”.

(I would have made the button a link, and the link a button, but anyway, it’s there.)
