### ISSUE TITLE
'measure' page OS graph is hard to interpret

### ISSUE THREAD

**Issue by thomir** [canonical-websites/snapcraft.io#290]
On the 'measure' page of the new publisher dashboard, the 'By OS' graph is hard to interpret, especially for snaps with a large install base. 

For example, here's the core snap (with numbers removed):

![image](https://user-images.githubusercontent.com/372783/35949994-258ec1ec-0cd9-11e8-8fef-ad58fc0fcbe1.png)

The colours in the graph are too similar to each other, and it becomes impossible to differentiate one OS from another.

Additionally, the tooltip entries appear to be sorted by colour, but I think they should be sorted in the same order as the stacking order on the graph (i.e.- from largest to smallest).

Finally, on our internal metrics we've started grouping non-Ubuntu operating systems by family (essentially stripping the '/<version>' part of the OS name). This has made these graphs much easier to interpret. You may want to consider doing the same.

**Comment by thomir** [comment]
Hi @Lukewh 

I think there's been a regression in the publisher dashboard - now whenever I attempt to load the `measure` page for core (or any other snap I have viewer rights on) I get an `HTTP 500` response.

Are these new systems hooked up to sentry? I couldn't see them in the snap-store sentry, but maybe you have a separate instance somewhere?

Cheers,

**Comment by lyubomir-popov** [comment]
@Lukewh 
How about using the [sequential colorbrewer scales](http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=9) - you get up to 9 colours per OS, 6 distinct scales.

> Additionally, the tooltip entries appear to be sorted by colour, but I think they should be sorted in the same order as the stacking order on the graph (i.e.- from largest to smallest).

The order should definitely match, the question is what makes more sense - sorted by OS version or by relative size. 

1) Sorting OSs by share and then versions within OS by version number seems most straightforward to me - share of OS version is clearly indicated by the surface area, and colours will be banded together by hue. I think the fact that the biggest ones aren't on top is less of an issue than the next alternative bellow.

2) Not grouping versions by OS will allow vertically sorting by size, but will inevitably lead to confusion as with lighter shades you can't always tell which scale a colour belongs to, take for example the lighter shades of these two - 

![image](https://user-images.githubusercontent.com/2741678/36255566-7378b0e8-1247-11e8-92b7-1401ff2df9f5.png)

**Comment by Lukewh** [comment]
@thomir we'll look in to that regression thanks for finding it.

**Comment by thomir** [comment]
Hi,

This bug shouldn't be closed in my opinion. Here's a sample 'by-os' graph from production with the numbers removed:

![image](https://user-images.githubusercontent.com/372783/36329900-8341f512-13cc-11e8-8953-937de570e179.png)

The regions that aren't labelled are really hard to see, and to my eye the colours are all identical.

**Comment by thomir** [comment]
Here's another example of the by-version map:

![image](https://user-images.githubusercontent.com/372783/36330100-3cb87494-13cd-11e8-8a6d-b1f72313818c.png)

The colours are just too similar to be able to distinguish them. 

I'm no designer, but perhaps a thing dark border around every area would help? Or perhaps using colours that are less similar to each other? 

You might use grafana as inspiration. The exact same graph on grafana looks like this:

![image](https://user-images.githubusercontent.com/372783/36330238-c523dce2-13cd-11e8-9977-2a8eaf5f422f.png)

**Comment by Lukewh** [comment]
@thomir I agree, I forgot github auto closed issues linked to in PRs. As the PR was a partial fix I'm reopening. Thanks for catching this.

**Comment by thomir** [comment]
Ah! I didn't know it did that either 😀

**Comment by matthewpaulthomas** [comment]
> The colours are just too similar

On Wednesday, @cprov suggested using one of the palettes provided by [Google’s Colour Palette Generator](https://github.com/google/palette.js) ([demo](https://google.github.io/palette.js/)).

**Comment by Lukewh** [comment]
Updated in https://github.com/canonical-websites/snapcraft.io/pull/357
