### ISSUE TITLE
The 'past year' option on the 'measure' should not be shown.

### ISSUE THREAD

**Issue by thomir** [canonical-websites/snapcraft.io#291]
On the 'measure' page of the new publisher dashboard. there 'past year' drop-down option probably should not be shown, as we don't have close to one year's worth of data. 

We have data from 2017-10-31.

I can think of a few strategies we could employ here:

1) We could change this to say "For all time", which would show data from 2017-10-31 until we have one year's worth of data, at which point we could change it back to say "Past year".

2) We could remove this option altogether, until we have 6 months of data, at which point we could add the '6 months' option. When we have one year of data we could add the 'one year' option.

**Comment by Lukewh** [comment]
Hey @thomir I've put in a PR to address this. I've removed the 1 year option. Adding a 'For all time' and then switching it back could cause some friction with users, so I think your option 2 is a far better solution - add specific periods when it makes sense.

**Comment by thomir** [comment]
Works for me - can you let me know when it's live please, and I'll do some further testing.

Cheers,
