### ISSUE TITLE
Encourage people with an account, but no snaps to do something

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/snapcraft.io#296]
currently if you login via /account and HAVE an SSO account, you get an empty page

![image](https://user-images.githubusercontent.com/441217/36037780-a90de8f4-0db5-11e8-8375-8089034c69c1.png)

this would be a good null state to encourage people create, learn about and install snaps?

**Comment by Lukewh** [comment]
This should be fixed with the latest set of functionality!
