### ISSUE TITLE
Snapcraft landing page content can improve.

### ISSUE THREAD

**Issue by nitos** [canonical-websites/snapcraft.io#303]
## Summary
I found the landing page of snapcraft confusing. I think the first part is okay, but then it talks about how to create a snap. Which is not at all the best part of what to tell about snapcraft. 

<img width="541" alt="screenshot 2017-04-17 15 41 43" src="https://cloud.githubusercontent.com/assets/289089/25105983/6128aab8-2384-11e7-9775-e9d1512d4ac7.png">

### Changing the approach:
The main users you want are developers, but I think from a conceptual model of a developer, it first needs to understand what it is, if it's worth to know more about the project, what things they can or can't do, if it's going to improve their process, how is it better, etc.

I would start by describing the benefits of Snapcraft on any project and communities rather than how to use it. Here's a sketch concept of this:

![snap](https://cloud.githubusercontent.com/assets/289089/25106406/81e0cea0-2386-11e7-878f-34e56e23d295.jpg)

**Comment by nitos** [comment]
I would love to contribute. But would need guidance to create this change. 
This is the first open source project I'll be contributing regarding UX/Usability/Content. Be nice :)

**Comment by caldav** [comment]
Thank you for the detailed suggestion, and welcome to the project! I think most people working on the snapcraft and on the snapcraft.io domain agree with the gist of it. There are changes coming this week and the next to the landing page, which will incorporate a lot of what you just illustrated. I'd suggest you subscribe to the pull requests of the project and see where you can contribute and discuss as they are proposed.
