### ISSUE TITLE
snapcraft branded 404

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#307]
### :owl: 404: Page not found
**Snap not found: <query>**

## What you should see
A more helpful 404, maybe with a search field for searching snaps

**Comment by Lukewh** [comment]
Related https://github.com/canonical-websites/snapcraft.io/issues/305

**Comment by Lukewh** [comment]
Use Snapcraft branding on current 404 page:

:bird: 404: Page not found

**Comment by Lukewh** [comment]
First version implemented at https://github.com/canonical-websites/snapcraft.io/pull/374
