### ISSUE TITLE
Wording for snap details page title

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#31]
We should define how HTML `<title>` for snap details page should look like.

Currently it simply says: {{ snap_title }} snap details

As snap details page is meant to be part of snapcraft.io site we should probably have a consistent titles. Snapcraft.io currently appends `Snaps are universal Linux packages.` to the title of every page.

So maybe title of snap details page should be: `{{ snap_title }} - Snap details - Snaps are universal Linux packages.`

Do you have any suggestions @matthewpaulthomas?

**Comment by matthewpaulthomas** [comment]
The Mac equivalent is “{App name} on the Mac App Store - iTunes - Apple”

The Android equivalent is “{App name} - Android apps on Google Play”

The Windows equivalent is “Buy {app name} - Microsoft Store” (even if the app is free!)

I suggest: “{snap_title} — Linux software in the Snap Store”

There’s nothing to be gained from making the titles of user-focused pages similar to developer-focused pages.

**Comment by anthonydillon** [comment]
Did you look at how jujucharms.com does it?

**Comment by matthewpaulthomas** [comment]
@anthonydillon I did not.

The jujucharms.com equivalent is either “{charm/bundle name} | Juju” or “{charm/bundle name} (#{some number}) - Juju GUI”, depending on how you get to the page. If I was working on that site I’d suggest changing the title to [better attract search visitors](https://www.google.com/search?client=ubuntu&q=how+to+deploy+mysql+on+ubuntu). But the page as a whole doesn’t seem geared to search visitors anyway.

**Comment by anthonydillon** [comment]
Thanks Matthew,

Fair point, I think we should try and align the experiences.
