### ISSUE TITLE
Politically incorrect region name "Taiwan, Province of China"

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-websites/snapcraft.io#310]
![The problematic section](https://user-images.githubusercontent.com/13408130/36272107-891f3dda-12bb-11e8-9433-c5d1a124080c.png)

The region name "Taiwan, Province of China" is politically incorrect and offending to Taiwanese users, please use the neutral name "Taiwan" instead.

If the website rely on the iso-codes package, please use the "common name" field when available instead as with this [patch](https://launchpadlibrarian.net/53161408/use_common_name_instead_when_it_exists.patch) did with the [Ubuntu LoCo Team Portal](http://loco.ubuntu.com/) site.

REF: [Bug #614236 “Wrong Country Name. (Taiwan)” : Bugs : LoCo Team Portal](https://bugs.launchpad.net/loco-team-portal/+bug/614236)

Thanks in advance!

**Comment by Lin-Buo-Ren** [comment]
This file seems to be the location: 
https://github.com/canonical-websites/snapcraft.io/blob/master/modules/public/views.py

However I don't speak Python so I don't know how to properly patch it.

**Comment by BlueT** [comment]
I know developers used to ref to the out-dated ISO-3166.
A correct and quick fix is to use `common_name` instead of `name` or `official_name`.

**Comment by kalifans** [comment]
Taiwan is Japan, not China

**Comment by Lin-Buo-Ren** [comment]
So sad I can't go to Okinawa without a pass ;)

**Comment by kalifans** [comment]
Taiwan is in the United States military occupation
The territory belongs to the Great Japanese Empire
The United States entrusted ROC administration

**Comment by Lin-Buo-Ren** [comment]
I've made a patch that is confirmed working on my local machine.  Please review.
