### ISSUE TITLE
Add Youtube to "follow-us" social links in footer

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#310]
Mirror https://github.com/canonical-ols/build.snapcraft.io/issues/654 on snapcraft.io

**Comment by evandandrea** [comment]
To be clear: this can be done before canonical-ols/build.snapcraft.io#654 lands.

**Comment by evandandrea** [comment]
https://www.youtube.com/snapcraftio

**Comment by evandandrea** [comment]
https://assets.ubuntu.com/v1/349a9e36-icon-social-snapcraft.svg

**Comment by matthewpaulthomas** [comment]
Wireframe:
![Twitter, Facebook, Google+, YouTube](https://cloud.githubusercontent.com/assets/19801137/25808573/6fdfb234-3402-11e7-9093-487cbe00eeaf.png)

**Comment by evandandrea** [comment]
https://assets.ubuntu.com/v1/6bfc3d6a-build.snapcraft.social.optimize.svg is the latest
