### ISSUE TITLE
Not obvious how to set/change banner artwork

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#342]
[The Snap Store counterpart of this issue is [LP#1750545](https://launchpad.net/bugs/1750545).]

[Robert Ancell writes on the Snapcraft Forum](https://forum.snapcraft.io/t/improve-method-for-setting-featured-snap-banner-image-in-store/1788):
> To [show snaps in the "Featured Application" section in GNOME Software](https://bugs.launchpad.net/bugs/1706478) we have used the screenshot functionality to do this.
>
> We currently look for a two screenshots uploaded with the name "banner.png" or "banner.jpg" and "banner-icon.png" or "banner-icon.jpg" and use these to promote this snap:
>
> ![Screenshot from 2017-08-21 14-58-16|690x487](https://snapforum.s3.amazonaws.com/original/1X/aedba4a96d1d93142a9060801bfd09cd19f42a28.png)
>
> This is using these images:
> <img src='https://snapforum.s3.amazonaws.com/original/1X/d71d2f216b7c8c9ced043d11e4a320a4880f5a7d.png'>
> <img src='https://snapforum.s3.amazonaws.com/original/1X/2e92f73e69e804cdc6dc7715380f713150e7900c.png'>
>
> When then hide these screenshots from the screenshots when viewing the snap details. Note that no other client would understand this and show these images as screenshots. GNOME Software is using a regular expression to match these files (since Django can add a suffix onto them):
>
> `^banner(?:_[a-zA-Z0-9]{7})?\\.(?:png|jpg)$`
>
> This is obviously pretty hacky... So we'd like to pay down some technical debt.
>
> What I propose we do:
>
> 1. Check if any other clients are going to make use of this feature, and if so check the format of the banner and icon are suitable for these.
> 2. Consider any additional information we would like to have for promoted apps. For example, the font colour is currently hard-coded to black but that would be probably be better configurable (as it is for existing promoted apps in GNOME Software).
> 3. Add two new database fields for the banner images and the associated web UI to set these (this would be a variation of the screenshot code). Add any other fields as determined in step 2.
> 4. Pass these banner URLs through snapd to the client.
> 5. Migrate any existing apps to the new database format.
> 6. Update GNOME Software to make use of the new format (synchronised with step 5).

**Comment by Greggless** [comment]
This will be solved by [snapcraft-design#316](https://github.com/CanonicalLtd/snapcraft-design/issues/316)

**Comment by matthewpaulthomas** [comment]
[snapcraft-design#316](https://github.com/CanonicalLtd/snapcraft-design/issues/316) was closed over two months ago, but this problem still exists as described.

**Comment by therealjuan** [comment]
This will be done as part of https://github.com/CanonicalLtd/snap-squad/issues/869
