### ISSUE TITLE
Account information source

### ISSUE THREAD

**Issue by cprov** [canonical-websites/snapcraft.io#348]
<img width="455" alt="screen shot 2018-03-06 at 9 57 28 am" src="https://user-images.githubusercontent.com/3610997/37023165-5779275a-2125-11e8-951d-9f6e24d71b4d.png">

In the https://snapcraft.io/account (screenshot above):

 * There is no reason to show `account-info.namespace` (*Namespace*) and `openid.username` (*Username*), they are the same
 * *Full name* seems to be the `openid.full_name`, we should expose `account-info.displayname` ([MP](https://code.launchpad.net/~nataliabidart/software-center-agent/add-displayname-to-account-info-handler/+merge/340837)) so the store is in control of this information and it will update more frequently.

**Comment by Greggless** [comment]
Thanks @cprov, you can find the work we're doing on account details in [this issue](https://github.com/CanonicalLtd/snapcraft-design/issues/292#event-1515788980)
