### ISSUE TITLE
'market' page validation issue with 'developer website' field

### ISSUE THREAD

**Issue by thomir** [canonical-websites/snapcraft.io#350]
To reproduce:

1) Upload a new snap to the store without setting a developer website in the yaml.
2) open a browser and go to: https://snapcraft.io/account/snaps/<snapname>/market
3) Edit the title field for the snap.
4) click 'apply'

At this point, I expect the title to be updated.

What actually happens is that I get an error message something along the lines of "URL must begin with http(s)'. The validation is complaining about the developer website field, which I haven't edited.

Further, if I repeat steps 3-4, the title is updated.

I suspect the issue here is that the validation on the new publisher dashboard is more strict than the validation on the backend services.

**Comment by bartaz** [comment]
It seems that empty `website` is returned as `None` form API, which causes error when we try to save it back.

We should properly treat `None` as empty value in the market form.

**Comment by bartaz** [comment]
Fixed by #489
