### ISSUE TITLE
'market' page validation issue on 'description' field

### ISSUE THREAD

**Issue by thomir** [canonical-websites/snapcraft.io#356]
I have a snap in production named 'pyconau-twitbot'. When I try to update the title field at:

https://snapcraft.io/account/snaps/pyconau-twitbot/market

I get an error:

`The 'description' field cannot contain control or private unicode characters.`

However, the description field does not contain any such unicode characters. I have unfortunately poked the description field and fixed the issue (so this is sadly no longer reproducible), but it seems like users can upload snaps with descriptions that then fail the validation on the frontend.

**Comment by bartaz** [comment]
Possibly related to #350.
We have seen this happening on newly uploaded snaps.

**Comment by bartaz** [comment]
It seems that it's caused by new lines being `\r\n` instead of `\n` when posted.
Not sure exactly why it happens (and why it happens for new snaps only) - need to investigate further.
