### ISSUE TITLE
Missing map due to JS error, unterminated string literal

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/snapcraft.io#358]
On the snap vanity pages that I've checked, I see no map

e.g. https://snapcraft.io/canonical-livepatch shows https://screenshots.firefox.com/qndJA4s0J28bFSaD/snapcraft.io in Firefox 58.0.2 on Ubuntu

SyntaxError: unterminated string literal canonical-livepatch:169:17

**Comment by Lukewh** [comment]
Fixed by https://github.com/canonical-websites/snapcraft.io/pull/362

Awaiting deployment

**Comment by Lukewh** [comment]
This is now deployed, closing.
