### ISSUE TITLE
Please list Solus as a supported distribution

### ISSUE THREAD

**Issue by btegs** [canonical-websites/snapcraft.io#359]
## Summary

The recent release of [Solus 3 added support for Snaps with AppArmor support](https://solus-project.com/2017/08/15/solus-3-released/) meaning that it should be listed on the https://snapcraft.io/docs/core/install page. Packages are now listed in the [official repositories](https://packages.solus-project.com/shannon/s/snapd/).

## Process

`sudo eopkg install snapd` [more on eopkg](https://solus-project.com/articles/package-management/basics/en/)

## Current and expected result

Snap package available with AppArmor

## Screenshot

![Image from Solus 3 press release](https://solus-project.com/imgs/posts/2017/08/snaps.jpg)

**Comment by jamiedbennett** [comment]
+1.

**Comment by caldav** [comment]
Fixed by #361
