### ISSUE TITLE
Screenshots - errors when user tries to upload same image twice

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#359]
- Go to market page
- Click add button and choose an image to add
- It shows up as new screenshot to be uploaded
- Click add button again and choose the same image to add
- It shows up again second time as second screenshot to be uploaded
- Click 'Apply'
- Error

We should either not allow to upload same image twice or not throw error when user attempts to do so.

**Comment by matthewpaulthomas** [comment]
As part of my Market page work, here’s [a draft design for this](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.zhlu2b48hwdh):
> In addition to [the general image error cases](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.leby91ua8xcu), whether detected client-side or server-side:
> - If one or more screenshots were identical, whether to current screenshots or to others in the same selection, the newer image(s) should be discarded and a [warning](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#bookmark=id.28a4o6im8tgc) should appear: “Identical images have been ignored.”

Does that seem reasonable?

**Comment by matthewpaulthomas** [comment]
[Draft design](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.zhlu2b48hwdh):
> In addition to [the general image error cases](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.leby91ua8xcu), whether detected client-side or server-side:
> - If one or more selected images were identical, whether to current screenshots or to others in the same selection, the newer image(s) should be discarded and a [warning](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#bookmark=id.28a4o6im8tgc) should appear: “Identical images have been ignored.”

**Comment by bartaz** [comment]
@matthewpaulthomas 

For sure we cannot (easily) compare newly added image to existing one. Existing ones are just URLs of screenshots we show in the browser, newly added are files chosen by user.
Unless we implement quite complicated reading of existing screenshots and pixel by pixel comparison ... but this seems a bit overkill for a benefit it could provide.

It should be much easier to compare 2 newly added images to tell that they are the same. And (as long as we allow user to only select one at a time) we can discard one that is duplicate.

And it's the second case (posting 2 new identical images) that is causing this bug.

**Comment by matthewpaulthomas** [comment]
@bartaz Even if someone knew that we detected duplicate screenshots, I doubt they’d ever _depend_ on us doing it. So I think it’s quite okay if, for now, we detect some duplicates (newly-uploaded vs. newly-uploaded) but not others (newly-uploaded vs. already-existing). I‘ve tweaked the text to convey that they can be implemented at different times.

(In the long run, I guess the way to avoid “pixel by pixel comparison” would be to get the store to calculate hashes for existing/applied images, and get the browser to calculate hashes for newly-uploaded images. But I’d understand that being very far down our to-do list!)
