### ISSUE TITLE
replace "suffixed" with "prefixed" in docs/build-snaps/parts

### ISSUE THREAD

**Issue by kwmonroe** [canonical-websites/snapcraft.io#364]
## Summary

When describing the "stage key", the documentation says:

```
...
       headers:
        - “*.h”
        - -include
...
$headers will include all the header files, except those from include as it is suffixed with -, indicating these files should be excluded.
...
```

That should read `... is prefixed with - ...` since the `-` is a *prefix*, not a *suffix*.

## Process

Go to https://snapcraft.io/docs/build-snaps/parts

## Current and expected result

Docs say *suffixed*; they should say *prefixed*.

**Comment by caldav** [comment]
Obviously. Thanks!
