### ISSUE TITLE
Useful 404 for snapcraft.io

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#387]
If we take a look at some other 404's from around the world wide web we can see that they have been actually designed. We should follow suit and help our users who end up at a dead end.

# 404's
## Github
A search? Hell yeh (maybe)!
- search snaps for now
- search docs when we can implement it

![github 404](https://user-images.githubusercontent.com/23459065/37396009-980bd8a8-276f-11e8-9623-677c27d0d9c0.png)

## Heroku
Useful links? Hoorah!
- browse snaps (snapcraft.io/store)
- documentation
- snapcraft.io

![heroku 404](https://user-images.githubusercontent.com/23459065/37396010-9822d594-276f-11e8-9bef-e7628e1b2fe5.png)
## Digital ocean
Short page to expose an extensive footer? 👣  Great!
![digital ocean 404](https://user-images.githubusercontent.com/23459065/37396007-97cdcf9a-276f-11e8-8601-258f33578d34.png)

## Docker
I just like the whale.
![docker 404](https://user-images.githubusercontent.com/23459065/37396008-97e3089c-276f-11e8-84bb-7e3c63ae8730.png)

**Comment by bartaz** [comment]
Some comments from on 404 in #397

**Comment by Greggless** [comment]
> * "404: Page not found" is confusing. This page has useful content.
> * "Snap 'azure-iot-edge' (snap id)". Snap is redundant and grammatically odd as the first word. The snap ID is meaningless to anyone but the developer of this application. I don't think it should be shown on this page.
> * "… has no published revisions in the given context." This is unnecessarily technical. Do we think end users will know what a "published revision" is? What context is "this context"?
> How about dropping the 404 and instead saying:
>> azure-iot-edge is not available in the stable channel, but may be available in the candidate, beta, or edge channels. Run `snap info azure-iot-edge` on a [snap enabled system](https://docs.snapcraft.io/core/install) to review the installation options.

**Comment by Greggless** [comment]
![snapcraft 404](https://user-images.githubusercontent.com/23459065/42460308-6f962fea-8395-11e8-9761-973a7e88e810.jpg)

Puns are MVP

**Comment by matthewpaulthomas** [comment]
> Ah, snap!

Perhaps “Aw, snap!” would better express the disappointment. (To me, “Ah, snap!” seems delighted.)

> Try searching for the snap

For any given 404, often it will be an end user trying to visit a snap’s directory page. But not always, for example:
- end user visiting a bookmarked publisher page, when the publisher has changed their ID
- end user visiting the standalone page for a review that was deleted while they were reading the snap page
- publisher in a hurry [mistyping `/account`](https://snapcraft.io/acount)
- publisher visiting a bookmarked snap admin page, unaware that a collaborator deleted the snap yesterday

So, probably we shouldn’t assume you are looking for the end-user page for “the snap”. Perhaps pose it as a question: “Looking for a snap? Try searching:”

**Comment by Greggless** [comment]
Roger roger, I concur will all of the above.

To summarise:

> ## Aw, snap! We couldn't find that page.
> Looking for a snap? Try searching:
> | ________________________________________________ | Search |
> Or browse the Snapcraft [Forum](https://forum.snapcraft.io) or [Docmentation](https://docs.snapcraft)
