### ISSUE TITLE
Get schema for market page fields & make document

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#390]

**Comment by matthewpaulthomas** [comment]
@bartaz says “Get schema” = getting documentation from store team about the limits (maximum length etc) for each item.

**Comment by matthewpaulthomas** [comment]
Gustavo proposed yesterday that the store should be able to tell the front end the limits for each item. That way we get to have both client-side validation (for speed) and server-side validation (for trustworthiness) without worrying about them getting out of sync.

**Comment by bartaz** [comment]
Doc created: https://docs.google.com/document/d/1Cri2RRs71IKY4leeoW7LJFU8hiPVB0DpNpK9_YjPB4I/edit#

**Comment by bartaz** [comment]
We can continue discussion and any necessary specification in the doc above.
