### ISSUE TITLE
Confusing 404

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#397]
<img width="540" alt="screen shot 2018-03-15 at 10 58 43" src="https://user-images.githubusercontent.com/1523179/37459457-0b72ff1c-2840-11e8-9b7a-69961770114f.png">

* "404: Page not found" is confusing. This page has useful content.
* "Snap 'azure-iot-edge' (snap id)". Snap is redundant and grammatically odd as the first word. The snap ID is meaningless to anyone but the developer of this application. I don't think it should be shown on this page.
* "… has no published revisions in the given context." This is unnecessarily technical. Do we think end users will know what a "published revision" is? What context is "this context"?

How about dropping the 404 and instead saying:
>azure-iot-edge is not available in the stable channel, but may be available in the candidate, beta, or edge channels. Run `snap info azure-iot-edge` on a [snap enabled system](https://docs.snapcraft.io/core/install) to review the installation options.

**Comment by bartaz** [comment]
What we currently show is an error message directly from API.

We have an issue in backlog already to create more useful 404 page: #387
Any comments are welcome there.
