### ISSUE TITLE
Confusing 404 on invalid snap name

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#398]
<img width="331" alt="screen shot 2018-03-15 at 12 38 09" src="https://user-images.githubusercontent.com/1523179/37463850-604ff1ee-284e-11e8-97b8-9260bd2b7bc1.png">

Like in #397, "404: Page not found" is confusing. This page has useful content.

**Comment by bartaz** [comment]
What we currently show is an error message directly from API.

We have an issue in backlog already to create more useful 404 page: #387
Any comments are welcome there.
