### ISSUE TITLE
Market page validation UI (marking invalid fields)

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#399]

**Comment by matthewpaulthomas** [comment]
[Draft design](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.88kyurq00o04) for the text fields:
> Title, Developer Web site, and Developer contact are [editable only on this page](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.7g4zasx003xn), while Summary and Description are [also editable in snapcraft.yaml](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.7g4zasx003xn). For all five:
> - If you enter any disallowed character, it should be silently discarded.
> - Whenever the field contains more than the maximum number of characters, the excess characters should not be discarded (because the eventual value will likely include some of them). Instead, the field should be [highlighted as an error](https://docs.vanillaframework.io/en/base/forms#validation-classes), and the excess number of characters should be overlaid in the error color inside the end of the field. (The meaning of this number is obvious from how it changes after any edit.)
> - Whenever the field contains fewer than the minimum _or_ more than the maximum number of characters, the Apply button should be disabled.

Does this seem reasonable?
