### ISSUE TITLE
Spurious line spacing in Spotify description in Firefox

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#405]
1\. Read [Spotify’s description](https://snapcraft.io/spotify) in Chromium.
2\. Read the same description in Firefox.

What you see in Chromium: | What you see in Firefox:
-|-
![snapcraft io spotify description chromium](https://user-images.githubusercontent.com/19801137/37516792-40c21190-2907-11e8-9450-2f44b1592885.png) | ![snapcraft io spotify description firefox](https://user-images.githubusercontent.com/19801137/37516793-4123d93e-2907-11e8-803b-fa22cd963f89.png)

What you should see: The description in Firefox should not have all the extra line spacing.

Apparently this is a Vanilla problem.

**Comment by bartaz** [comment]
Yes, it seems Vanilla adds margin to `<br>` (which is used here extensively to format the description) and for some reason Firefox renders this margin when Chrome ignores it (as it's inline element).

Reported in Vanilla: https://github.com/vanilla-framework/vanilla-framework/issues/1627

But we should workaround that ourselves as well not to wait for Vanilla release.
