### ISSUE TITLE
Screenshots UI - marking for deletion not clear

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#410]
Marking a screenshot for deletion is not clear

### Screenshot 
![screen shot 2018-03-19 at 09 51 46](https://user-images.githubusercontent.com/23459065/37588803-384a445a-2b5b-11e8-9029-483c40fe352c.png)
# 

Triaged from https://github.com/canonical-websites/snapcraft.io/issues/365

**Comment by matthewpaulthomas** [comment]
[Draft design](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.3lul1pilhdjv):
> ![screenshots](https://user-images.githubusercontent.com/19801137/38092915-7180fc60-3361-11e8-8d6e-0ee6f63f69dd.png)
>…
> The screenshots themselves should behave as checkboxes: Tabbing should move focus between them, and Space should select/deselect them, with a checkmark overlaid in addition to any outline.

The checkmarks would both make the selection more visible, and wordlessly help explain how selection behaves.

**Comment by therealjuan** [comment]
Screenshots needs rework is over engineered
