### ISSUE TITLE
Screenshots - No multiple select and delete

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#411]
A user cannot multiple select images (🎖 enhancement)

To be decided if we implement this

# 
Triaged from #365

**Comment by bartaz** [comment]
Selecting multiple images would make sense for deleting.

But one feature that we haven't implemented yet is moving screenshots. When moving screenshots it would be very hard/confusing to move multiple screenshots at once.

So we need to decide how to implement selecting that will suit both deleting and moving.

**Comment by Greggless** [comment]
Agreed, if it causes more problems than solves, I am happy for single select and delete. There will only be a maximum of 5 screenshots after all

**Comment by shivjoshi1996** [comment]
Makes sense for deleting, but causes problems with moving, entering full screen.

**Comment by matthewpaulthomas** [comment]
[Draft design](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.3lul1pilhdjv):
> The screenshots themselves should behave as checkboxes: Tabbing should move focus between them (#414), and Space should select/deselect them, with a checkmark overlaid in addition to any outline.
>
> If you move multiple screenshots, they should be placed contiguously at the new position, even if they were previously interspersed with unselected screenshots. If you choose “Move Earlier”, the new position should be one earlier than the earliest selected; if you choose “Move Later”, the new position should be one later than the latest selected.
>
> Remove should be enabled whenever at least one screenshot is selected.

Does that make sense? Interaction-wise, I don’t think there’s really a problem with moving multiple items. The most surprising bit is that in a discontiguous selection, interspersed unselected items will jump out of the way. (FWIW, that’s also the behavior when dragging a discontiguous selection in LibreOffice.) But that will hardly ever happen anyway.

> causes problems with … entering full screen

Did you mean, showing only the selected ones? If so, the maximum screenshots are so few, and navigating between them is so quick, I think that would be more surprising than useful. _Maybe_ if some are selected, the first selected one should be the one that’s zoomed in initially — but you should still be able to navigate to the unselected ones.

**Comment by Lukewh** [comment]
This is no longer relevant as we move towards new screenshots functionality and design.
