### ISSUE TITLE
Screenshots - tabbing through images

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#414]
It'd be helpful if the user was able to tab through the screenshots individually, rather than skipping the whole section
### Before `tab`
![screen shot 2018-03-19 at 10 12 01](https://user-images.githubusercontent.com/23459065/37589714-02829856-2b5e-11e8-936f-918ac8dc5c6e.png)
### After `tab`
![screen shot 2018-03-19 at 10 13 03](https://user-images.githubusercontent.com/23459065/37589781-259efcbc-2b5e-11e8-8d19-a11ae3e36c9c.png)

#
triaged from #365

**Comment by bartaz** [comment]
I guess tabbing through images would only be useful if user would be able to do something with them while they are 'focused' using keyboard only.

This is a custom element, so we would need to make sure that these keyboard actions are easily discoverable and familiar.
I guess hitting `delete` button on keyboard when image is selected could mark it for deletion. But we would need an easy way to undo it, so users don't delete images by mistake.
Hitting `space` or `enter` could open image in lightbox - but I'm not sure if it's that useful in market page context.
We could later have some keyboard actions for moving screenshots (arrow keys?) but I'm also not sure if they would be easily discoverable and not lead to more problems then ease of use.

**Comment by matthewpaulthomas** [comment]
[Draft design](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.3lul1pilhdjv):
> The screenshots themselves should behave as checkboxes: Tabbing should move focus between them, and Space should select/deselect them, with a checkmark overlaid in addition to any outline.
> 
> Remove should be enabled whenever at least one screenshot is selected.

**Comment by Greggless** [comment]
🚀 👍 :shipit:

**Comment by matthewpaulthomas** [comment]
(Sorry, I should have specified that the “Review/QA” was just for the design, not the implementation.)

**Comment by Lukewh** [comment]
This issue seems to have been abandoned? Is it closed? Is it open? What epic is it part of? Should it be in the current iteration? Is this issue purely for the design/ UX? Should there be a follow up for the development?

**Comment by Lukewh** [comment]
Also - what's the estimate?

**Comment by Greggless** [comment]
1. It's an open issue
2. It could be a smol task 
3. bump it to next iteration
4. a code fix is required (use keyboard `tab` to nav between screenshots
5. 🦄
