### ISSUE TITLE
ReferenceError: Can't find variable: snapcraft

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#425]
A number o f visitors to https://snapcraft.io/skype (often referred from https://www.skype.com/en/get-skype/) are getting a JS error:

> Can't find variable: snapcraft (line 202)

https://sentry.io/canonical-bm/snapcraftio/issues/482677078/

```
ReferenceError: Can't find variable: snapcraft
  at None (/skype:202:16)
  at global code (/skype:201:18)
```

**Comment by Lukewh** [comment]
This doesn't appear to be happening anymore, so closing this issue.
