### ISSUE TITLE
Changing store account name doesn't update to snaps

### ISSUE THREAD

**Issue by pakastin** [canonical-websites/snapcraft.io#429]
I changed my store account name from `Juha Lindstedt` to `iDiD digital signage` couple of days ago and it hasn't been updated to here: https://snapcraft.io/idid

**Comment by bartaz** [comment]
Thanks for your report. We can confirm that there is an issue that we can reproduce.

Changing your account name process is as follows:
1. Go to https://login.ubuntu.com/
2. Change "Your name" and Save changes
3. Go to https://dashboard.snapcraft.io/
4. Sign out
5. Sign in again
6. You should see your new name in header
7. You should see your new name on account page: https://dashboard.snapcraft.io/dev/account/

This should also make the new name available through API and on public snap details page, but this doesn't work. Public snap details page still shows old user name.

We will look into the issue.

**Comment by pakastin** [comment]
That is exactly what I did. 6) and 7) works, but that doesn't update to the snap's page.

**Comment by cprov** [comment]
The instructions need to include, after step 7, some sort of snap update (summary, description, etc) to trigger the new Publisher name further propagation. Far from ideal ...

I've refreshed the data for `idid`.

**Comment by pakastin** [comment]
I also added screenshots and pushed few versions after changing the name, but no..

Thank you, now it changed! 👍

**Comment by Lukewh** [comment]
@pakastin I'm glad the steps worked for you.

To avoid the need for such random steps in the future this issue is now being tracked as part of the snap store API: https://bugs.launchpad.net/snapstore/+bug/1761500
