### ISSUE TITLE
Handle public `status: NO DATA` metrics on the front end

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#437]
Currently if the map doesn't load you still see the title, this should be handled.

**Comment by cprov** [comment]
@Lukewh The was a slightly change in the spec, we are simply reusing `status: NO DATA` instead of a new `FORBIDDEN` there is no reason to put publisher on the spotlight because they decided to not show a metric.

**Comment by Lukewh** [comment]
Thanks @cprov updated title!
