### ISSUE TITLE
Badly cached CSS (and possibly JS)

### ISSUE THREAD

**Issue by cprov** [canonical-websites/snapcraft.io#438]
Edited by @bartaz:

Currently our static resources (such as CSS and JS bundles) are simply cached by the browser.
When we release new version to production most often browsers will have old version of CSS and JS cached and will not request a new one.

This leads to a broken experience. Such as recent issue with CLI instructions:

<img width="576" alt="screen shot 2018-03-22 at 9 03 02 am" src="https://user-images.githubusercontent.com/3610997/37769504-f8dfbc30-2daf-11e8-8be8-0b5f994bfde7.png">

Full browser reload is needed to fix this from user side, but this should not be accepted as a workaround.

We need to make sure browsers request new versions of files when new version is deployed.

**Comment by cprov** [comment]
Using Chrome on Mac OSX

**Comment by bartaz** [comment]
Old CSS cached. Full reload should fix that.

There must be something wrong with cache headers that browser didn't detect the change in CSS.

**Comment by cprov** [comment]
@bartaz right, full reload solved it, thanks. Any ideas for improving the CSS caching ?

**Comment by bartaz** [comment]
Files affected are CSS bundle:

`<link rel="stylesheet" href="/static/minified/styles.css" />`

Our JS bundles:
`<script src="/static/js/dist/public.js"></script>`
`<script src="/static/js/dist/publisher.js"></script>`

And quite possibly any 3rd party JS lib that we load (not included in the bundle). They don't update often, but if we update any of these at some point they may be affected as well:
Public snap details:
```
<script src="/static/js/modules/clipboard.min.js"></script>
<script src="/static/js/modules/d3.min.js"></script>
<script src="/static/js/modules/d3-geo.min.js"></script>
<script src="/static/js/modules/topojson-client.min.js"></script>
```
Measure page:
```
<script src="/static/js/modules/moment.min.js"></script>
<script src="/static/js/modules/d3.min.js"></script>
<script src="/static/js/modules/d3-geo.min.js"></script>
<script src="/static/js/modules/topojson-client.min.js"></script>
<script src="/static/js/modules/billboard.min.js"></script>
```

**Comment by Lukewh** [comment]
Could we also include the version in an environment var so we can pass it through to Sentry to tag by build?

**Comment by bartaz** [comment]
We have a `x-vcs-revision` header sent with build number which maybe could be used for sentry as well. But I don't see it anywhere in the app, so possibly it's handled by kubernetes.

**Comment by tbille** [comment]
> @Lukewh  Could we also include the version in an environment var so we can pass it through to Sentry to tag by build?

This was done in  in this PR: https://github.com/canonical-websites/snapcraft.io/pull/470 and this one https://github.com/canonical-websites/snapcraft.io/pull/466

> @bartaz  We have a x-vcs-revision header sent with build number which maybe could be used for sentry as well. But I don't see it anywhere in the app, so possibly it's handled by kubernetes.

Now the frontend receives the commit_id we can add it as @nottrobin said (`/static/css/global.css?COMMIT_ID`)

**Comment by nottrobin** [comment]
> Now the frontend receives the commit_id we can add it as @nottrobin said (/static/css/global.css?COMMIT_ID)

Well the solution we've used previously doesn't use the commit ID, but rather a hash of the contents of the file - see https://github.com/canonical-webteam/versioned-static. This way the URL will only change if the file's contents has actually changed, allowing users to continue to take advantage of their cached versions except when there has actually been a change to the file.

**Comment by Lukewh** [comment]
@notrobin yeah, I realised earlier the two things weren't related/ you didn't mean commit hash for static assets. The file hashing is a way better choice for static files.
