### ISSUE TITLE
Searching for “code” doesn’t find Visual Studio Code

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#452]
1\. [Search the snap directory for “code”](https://snapcraft.io/search?q=code).

What you see: The results don’t include [Visual Studio Code](https://snapcraft.io/vscode).

What you should see: It should be one of the top results.

**Comment by Lukewh** [comment]
Perhaps we should bump https://bugs.launchpad.net/snapstore/+bug/1734122 as this ball is in the snapstore court.

**Comment by Lukewh** [comment]
More specifically tracked here: https://bugs.launchpad.net/snapstore/+bug/1761738
