### ISSUE TITLE
Empty space and horizontal lines in market page top part

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#457]
With new 'condensed' header having line below it and buttons also have line below it.
But as buttons are right aligned it leaves this empty space on the left with 2 horizontal lines which looks a bit 'off'.

<img width="1050" alt="screen shot 2018-03-27 at 11 57 30" src="https://user-images.githubusercontent.com/83575/37960553-31d7ef3a-31b6-11e8-9f1a-cfa5ca328fd5.png">

**Comment by matthewpaulthomas** [comment]
How about this:

![screenshot tweaked](https://user-images.githubusercontent.com/19801137/38546897-bb1d1eb0-3ca5-11e8-8141-4a4d09570f12.png)

The text “Changes you apply will appear immediately in the public listing” serves three purposes, most important first:
1. provides a link to the public page for you to compare with
2. emphasizes that you have to click Apply (for now at least)
3. fills the empty space.

**Comment by therealjuan** [comment]
Fixed
