### ISSUE TITLE
Client side validation on market page

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#469]
From @matthewpaulthomas:

[Draft design](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.88kyurq00o04) for the text fields:
> Title, Developer Web site, and Developer contact are [editable only on this page](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.7g4zasx003xn), while Summary and Description are [also editable in snapcraft.yaml](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.7g4zasx003xn). For all five:
> - If you enter any disallowed character, it should be silently discarded.
> - Whenever the field contains more than the maximum number of characters, the excess characters should not be discarded (because the eventual value will likely include some of them). Instead, the field should be [highlighted as an error](https://docs.vanillaframework.io/en/base/forms#validation-classes), and the excess number of characters should be overlaid in the error color inside the end of the field. (The meaning of this number is obvious from how it changes after any edit.)
> - Whenever the field contains fewer than the minimum _or_ more than the maximum number of characters, the Apply button should be disabled.

Does this seem reasonable?

**Comment by bartaz** [comment]
@matthewpaulthomas 

Thanks for the proposal.

One thing that we were planning to do as part of #391 was to set max length limits on the text fields.
Meaning users would not be able to enter title or summary that is too long.

As I see in your proposal we shouldn't do it - instead we should allow users to enter longer values, but mark them as incorrect and prevent them from posting them (by disabling the button)?

**Comment by matthewpaulthomas** [comment]
Right. Not using `maxlength` allows much more humane behavior:
- typed text will still appear, instead of being suddenly ignored as if the browser has frozen
- pasted text won’t be weirdly truncated, making you think you miscopied it
- you can see exactly how many characters you need to trim
- when replacing a too-long word/phrase, you can enter the shorter replacement first if you want.

(Ideally browsers would do all these with `maxlength`, but they don’t.)
