### ISSUE TITLE
Footer: Text improvements

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#47]

**Comment by matthewpaulthomas** [comment]
Specifically:
- “Copyright Canonical” looks as if Canonical is claiming copyright on the snap.
- Trademark statement need not, and should not, mention Ubuntu.
- “Report a bug on this site” could be interpreted as reporting a bug about the snap.
- “Service status” could be interpreted as status of a service for which the snap is the client.
- Near position, and color scheme, of the footer accentuates all these problems.

**Comment by matthewpaulthomas** [comment]
Wireframe:
![footer.png](https://images.zenhubusercontent.com/59314abd51aa2c3057803bcd/78037a77-ed24-49c8-9038-7e97e1d763be)

Solutions to the above problems:

> - “Copyright Canonical” looks as if Canonical is claiming copyright on the snap.

Changed to “Directory © 2017 Canonical Ltd”.

> - Trademark statement need not, and should not, mention Ubuntu.

No trademark statement at all. (Canonical or Ubuntu won’t be mentioned on these pages except by an individual vendor.)

> - “Report a bug on this site” could be interpreted as reporting a bug about the snap.

Changed to “Report a bug about the directory”.

> - “Service status” could be interpreted as status of a service for which the snap is the client.

Removed. It isn’t useful for end users to see the status of developer services; and if the end-user directory is down they won’t be able to access this page in the first place.

> - Near position, and color scheme, of the footer exacerbates all these problems.

The footer is given a grey tint.

**Comment by bartaz** [comment]
@matthewpaulthomas @spencerbygraves 

Implemented suggestions will look like this:

![screen shot 2017-09-19 at 13 55 28](https://user-images.githubusercontent.com/83575/30591272-62fdedac-9d42-11e7-8d66-a54323ca5f83.png)

Note white space below footer.
Currently vanilla doesn't have support for more control over footer placement. Achieving grey footer means wrapping it into strip pattern (with paddings removed), which seems like a hack solution on it's own.

If we want background under footer we should prepare a visual design for it and propose a pattern update to Vanilla to avoid using patterns and utility classes where they are not intended.

@nottrobin Any thoughts on that?

**Comment by nottrobin** [comment]
I don't know if we have a grey footer anywhere else. But it doesn't feel *that* unprecedented since we do have `p-strip--light` for strips with a grey background. We could use that, or we could create a `p-footer--light`?
Thoughts @barrymcgee or @anthonydillon?

**Comment by barrymcgee** [comment]
`.p-strip--light` will give you [a white footer](https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_patterns_strip.scss#L31) - not a grey one. All of recent sites converted to Vanilla have the footer with a white background, even if they had a custom background before.

Rather than add more classes to achieve an edge case, I'd prefer to push back to design and see if we can't accommodate a white background here too?

**Comment by bartaz** [comment]
@barrymcgee As far as I see `.p-strip` is white (doesn't define background color) while `.p-strip--light` is light grey: https://docs.vanillaframework.io/en/patterns/strip

Which is a bit confusing now that `.p-navigation--light` is white.

**Comment by matthewpaulthomas** [comment]
Confession: I have been drawing a light grey footer in all my Snapcraft mockups this year, and I hadn’t paid attention to what colour the footer was in the implementation.

I do think greying snapcraft.io’s footer would help to separate it from the page contents. And even if not, I do think the snap directory’s visual design should be different from snapcraft.io (though that is still a matter for discussion). But neither of those are reasons to jump through hoops trying to implement a grey footer right here and now.

**Comment by barrymcgee** [comment]
@bartaz Sorry, my mistake, you're right - .p-strip--light is `#f7f7f7`

**Comment by nottrobin** [comment]
@barrymcgee: @spencerbygraves, @matthewpaulthomas, @bartaz and I discussed this in standup this morning, and we do feel that in this case a grey background is warranted.

It's not really very far from our general design philosophy, given we have grey strips. The logic seems to make sense to me too - a light grey footer is easier to visually separate from the main page content (which defaults to white). This is particularly important in this case (information in the footer *is not* linked to the specific snap you're looking at), but this is probably quite a useful concept in many cases.

I suggest we discuss it at the next working group.

**Comment by matthewpaulthomas** [comment]
Changes reviewed by @carlaberkers today.
