### ISSUE TITLE
Server error on market page with expired macaroon

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#476]
If I go straight to the market page for my snap - https://snapcraft.io/account/snaps/documentation-builder/market - I see "Internal server error". I believe the actual error behind the scenes was one about the macaroon being expired.

If I then go to https://snapcraft.io/account/, and then browse to https://snapcraft.io/account/snaps/documentation-builder/market, it works. Because I guess the macaroon is then fresh.

All pages should successfully refresh the macaroon if required.

Also, we should have tests to make sure all routes handle expired macaroons properly.

**Comment by tbille** [comment]
@nottrobin this case (refresh macaroon) has been added on `/account` endpoint. Now it needs to be added on the other endpoints and should be done when we refactor.

**Comment by nottrobin** [comment]
@tbille it's a live error, it should be fixed ASAP.

**Comment by kasiag** [comment]
@nottrobin @tbille guys could you estimate this issue pls

**Comment by nottrobin** [comment]
@kasiag behold! ^
