### ISSUE TITLE
.p-table-key-value causes overflow and horizontal scrollbar on narrow screens

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/snapcraft.io#511]
### Expected behaviour
No horizontal scroll
### Steps to reproduce the problem
Visit url below. Resize to screen width narrower than table width
### Specs
![image](https://user-images.githubusercontent.com/2741678/38726138-3d49232c-3f01-11e8-813d-18bbeac6e865.png)

- _URL:_ http://snapcraft.io-pr-495.run.demo.haus/account
- _Operating system:_ seen on MacOS but likely any
- _Browser:_ seen in Chrome but likely any

**Comment by bartaz** [comment]
It's not so much problem with key/value table. Email doesn't break a line - in here it happens to be in the table. If we put (long) email anywhere on the page if it gets longer then screen it will cause horizontal scroll.

Other bigger related issue is that account pages were not really designed and developed for mobile small screens and with current big tables/forms they don't work very well on small screens.

**Comment by Lukewh** [comment]
@lyubomir-popov suggested making this section a definition list during standup on Friday.

**Comment by bartaz** [comment]
This issue seems out of date. 
With new my snaps page `/account/snaps` and account details `/account/details` we don't use the key-value table to show long emails. So this shouldn't be an issue.
