### ISSUE TITLE
Account menu with long name makes page scroll horizontally

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#516]
1\. Register an Ubuntu One account with a very long full name.
2\. Sign in to snapcraft.io.

What you see:
- The account menu overflows off the edge of the header, with light grey text on white background.
- The whole page scrolls horizontally.

![snapcraft io-account-name-overflow](https://user-images.githubusercontent.com/19801137/38803928-925e871c-4168-11e8-8688-c9d3771f8d59.png)

What you should see:
- The account menubutton should have a maximum width.
- The page should not scroll horizontally.

**Comment by lyubomir-popov** [comment]
This seems a good addition to base vanilla. I'll make a pr.

**Comment by bartaz** [comment]
Fixed in https://github.com/canonical-websites/snapcraft.io/pull/498
