### ISSUE TITLE
Can choose more than five screenshots

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#518]
1\. Go to the “Market” (or equivalent) page for a snap.
2\. Click the “+” button and choose a screenshot, until there are five.
3\. Click “+” again and choose another screenshot.

What happens: You can choose one.

What should happen: the “+” button should be disabled.

**Comment by bartaz** [comment]
Oh, button is correctly disabled but still can be clicked. Thanks unexpected. Good catch!

**Comment by bartaz** [comment]
How did we miss this one when triaging QA? Moving it up now, as it's quite critical before go live.
