### ISSUE TITLE
Forum is a separate site, but snapcraft.io header doesn’t show it as one

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#522]
1\. Go to [snapcraft.io](https://snapcraft.io/).
2\. Look at the “My snaps” link.
3\. Look at the “Forum” link.

What you see:
2\. “My snaps” has the external-link icon, because it is a separate Web site: different header, color scheme, sign-in system, etc.
3\. “Forum” does not have the external-link icon, despite being a separate Web site: different header, color scheme, sign-in system, etc.

What you should see:
3\. “Forum” should have the external-link icon, the same as “My snaps” does.

We did not include this when the new header was implemented, because we thought the Forum was going to adopt the new header, and thereby become part of the same site. But that was abandoned as “not possible” in [snapcraft-design#276](https://github.com/CanonicalLtd/snapcraft-design/issues/276). So, we should continue showing it as an external site instead.

**Comment by matthewpaulthomas** [comment]
I mistakenly connected a PR that fixes this issue only in build.snapcraft.io. It still needs fixing in snapcraft.io.

**Comment by therealjuan** [comment]
Going to discuss with Gustavo on the next cross-team meeting

**Comment by Lukewh** [comment]
Fixed by canonical-websites/snapcraft.io#929
