### ISSUE TITLE
Two checkboxes for one map doesn’t make sense

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#524]
1\. Go to the “Market” page for any snap you admin.
2\. Scroll to the bottom of the page.

What you see:
> ☑ Display public popularity charts
> 
> ☑ Territories
> Displays where your snap is being used by country

What’s wrong with this: It’s two checkboxes controlling the visibility of a single map.

What you should see: either
- one checkbox (since there’s only one chart), or
- no checkboxes at all (since, to my knowledge, no publisher has ever asked to turn off the map, except because of #279, which we should fix anyway).

“Oh, but we might add more charts later!” If that ever happens, add checkboxes for them then. Users shouldn’t have to read our minds, or predict the future, to understand the current UI.

**Comment by Lukewh** [comment]
However, unchecking the initial checkbox will essentially allow publishers to 'opt-out' of any future metrics being added. A single checkbox requires those who are nervous to constantly check the page.

**Comment by matthewpaulthomas** [comment]
Yes, I know that’s what it’s for … but only because I’m on the snapcraft.io development team. To expand on my last paragraph, that the initial checkbox “will essentially allow publishers to 'opt-out' of any future metrics” is understandable to people who:
- have been a member of the snapcraft.io development team for some period longer than two weeks (as demonstrated by [the duplicate](https://github.com/CanonicalLtd/snapcraft-design/issues/376)); or
- have discussed this particular issue with one of those team members; or
- have read this bug report; or
- can read our minds or predict the future.

Right now, those four categories might cover all publisher page users. But very soon, those four categories will cover a tiny proportion of publisher page users. To everyone else, it will look like two checkboxes controlling one chart, which is just nonsense.

Now, a first attempt at making it not nonsense might add a caption to the initial checkbox. Something like this:
> ☑ Display public popularity charts
> Includes charts that may be added in the future.
>
> ☑ Territories
> Where the snap is being used across the world.

But that makes explicit the underlying problem: How on earth am I supposed to know whether it’s a good idea to opt out of charts that may be added in the future, when I have no idea what they will be? I can’t.

> A single checkbox requires those who are nervous to constantly check the page.

That logic would require dozens of checkboxes, to let nervous publishers opt out of other questionable things that we might do in the future: adding a graph of snap size over time, randomizing the background colour of the snap page, introducing a “Most uninstalls this week” leaderboard … I mean, we _probably_ won’t do any of those things. But who can say for sure?

I still have seen zero evidence that charts need to be optional at all. But if it is going to be a choice, it needs to be an informed choice, and this isn’t it.

So, here’s a simple and concrete proposal:
- Now: Drop the first checkbox.
- If+when we add another chart: Don’t show it by default. But the next time any collaborator visits any part of the publisher UI for a snap, present an interstitial: “Hi, would you like to add this chart to the public page for {snap title}?” And show _the actual chart for that snap_.

**Comment by Greggless** [comment]
Aha, I understand now. 

<hr>

### Public metric charts
> These display relative popularity, not exact numbers.
- [x] **World map** (displays where your snap is being used by territory)
- [ ] **Linux distributions** (displays where you snap is being used by distro)

<hr>
