### ISSUE TITLE
Show that snaps are real for 32 bit users

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#559]
### Expected behaviour
- Be me, using a 32 bit system
- Search for snapfoo_64bit
- See snapfoo_64bit in results
- click into page
- see that 
  - > This snap is not available for 32 bit architectures

### Current behaviour
- ...
- Search for snapfoo_64bit
- Search says `NO RESULTS`

**Comment by Greggless** [comment]
@tbille @therealjuan Should we create an issue for the UX and leave this as a backend issue?

**Comment by Lukewh** [comment]
@Greggless @tbille @therealjuan are we doing this issue this iteration? Should it have an estimate?

**Comment by Greggless** [comment]
No and yes

We should turn this into an epic and put some further investigation into it
