### ISSUE TITLE
Caption for Contact field says “Use include”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#578]
1\. Go to the “Market”/“Store Listing” page for a snap you are a collaborator on.
2\. Look at the caption below the “Contact…” field.

What you see: “Use include a valid http://, https:// or mailto: link”

![snapcraft io 578 contact field caption](https://user-images.githubusercontent.com/19801137/39189310-d75eaa60-47c9-11e8-8451-99302f6efda6.png)

What you should see: “https://, http://, or mailto:”

(Usual disclaimer: I don’t think it’s a good idea to allow a Web URL or a mailto URL in the same field.)
[Discovered while testing [snapcraft-design#380](https://github.com/CanonicalLtd/snapcraft-design/issues/380).]

**Comment by Greggless** [comment]
Correct copy ➡️ https://github.com/canonical-websites/snapcraft.io/pull/547#issuecomment-383033139

Relevant PR ➡️ https://github.com/canonical-websites/snapcraft.io/pull/574
