### ISSUE TITLE
/account/snaps page gives odd "congratulations" message

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#587]
The account page at https://snapcraft.io/account/snaps says:

> Congratulations!
> You've just released documentation-builder to the "stable" channel!

I actually released documentation-builder to the stable channel over a year ago.

This could be interpreted as patronising for someone who's been successfully using snaps for a long time, but is seeing this (beta) interface for the first time. I think the messaging should be tweaked.

**Comment by bartaz** [comment]
I think it's only shown for users with one snap.

But yes, having one snap is the only condition - so as long as you have one snap only you will always see this.

**Comment by nottrobin** [comment]
> We won't update the copy as the new logic put in should fix this issue

What's the new logic? Is it now based on the updated time?

> (you should publish some more, Robin grinning )

Because, this is not a good argument :stuck_out_tongue_closed_eyes:

**Comment by matthewpaulthomas** [comment]
When I wrote the current text:
- Lyubo and I were doing rapid prototyping of the first-use case, in a hurry
- I failed to consider the case where you come back later
- I did not yet know that outside of BSI, when you first push a snap, it is not released in any channel
- I intended the text to appear only when you had one snap in `edge`, definitely not in `stable`.

So I would be quite discombobulated if “We won't update the copy”.

I’ve suggested a short-term fix in #597:
> - Drop the words “Congratulations!” and “just”.
> - If the snap is public and released in any channel, it’s not classed as “new”.

Longer-term, I think the suggestions we show here should vary depending on whether the snap:
- is released in stable yet
- is public yet
- has screenshots etc yet
- has automated builds.

**Comment by Lukewh** [comment]
I've done a PR to try and address the immediate problem: https://github.com/canonical-websites/snapcraft.io/pull/597

@nottrobin the dumb logic for now https://github.com/canonical-websites/snapcraft.io/pull/597/files#diff-087e2aed723e3c7e3e9d5b69fbbab7eaR114

**Comment by Greggless** [comment]
> If the snap is public and released in any channel, it’s not classed as “new”.

Many of the language guides end with a publish snap so this would skip past the first time experience...

**Comment by therealjuan** [comment]
Merged so closed
