### ISSUE TITLE
Difficult to tell which header item is highlighted

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#591]
1\. Go to [the Store section](https://snapcraft.io/store).
2\. Go to [the Build section](https://build.snapcraft.io/).
3\. Try to notice a difference in the header (apart from the “Sign in with GitHub”).

What happens: The only deliberate difference is that the background is 8% darker (#111111 vs. #252525).

![snapcraft io-header-store](https://user-images.githubusercontent.com/19801137/39293919-2d804e08-4932-11e8-9c2a-742f40411a15.png)
![snapcraft io-header-build](https://user-images.githubusercontent.com/19801137/39293920-2d979bda-4932-11e8-8b45-a5fc9ca09ba1.png)

This difference is supposed to indicate what part of the site you are in. But on a sunny day, or if your screen is tilted up a little, the difference is practically invisible.

There are many ways the highlight could be more obvious. One is demonstrated by [maas.io](https://maas.io/):

![maas io-header-install](https://user-images.githubusercontent.com/19801137/39294313-565ad8ba-4933-11e8-89da-9599825a88fd.png)
![maas io-header-how](https://user-images.githubusercontent.com/19801137/39294314-56a17fa4-4933-11e8-87ed-6dff5b309535.png)

**Comment by fitojb** [comment]
This should be reopened; Vanilla Framework dropped this highlight for no good reason.
