### ISSUE TITLE
Header items placed inconsistently on different sections of the site

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#592]
The Snapcraft logo and header links have three different horizontal placements on [snapcraft.io](https://snapcraft.io/), [build.snapcraft.io](https://build.snapcraft.io/), and [docs.snapcraft.io](https://docs.snapcraft.io/). This is sloppy and disorienting.

The items are positioned the same if the window is narrow, but diverge as the window gets wider.

As [I wrote in snapcraft-design#294](https://github.com/CanonicalLtd/snapcraft-design/pull/294#issuecomment-369528129):
>There is a lot of left and right padding in the header, apparently to line up with the page content … But the page content of what? Currently:
> - snapcraft.io is `max-width: 1030px`
> - build.snapcraft.io is `max-width: 1070px`
> - forum.snapcraft.io is `max-width: 1110px;` … `padding: 0 8px`
> - docs.snapcraft.io is implicitly `width: 100%`, and explicitly `margin: 0;` … `padding: 0`
>
> Either the header shouldn’t try to line up with the page content; or the domains all need changes to their page layout to line up with the headers. I’d suggest the first, with the navigation links flush left and the sign-in/sign-out flush right. Not because it’s less work, though it is — but because, for example, it’s quite reasonable for a Snapcraft brochure page to have much bigger left and right margins than a page of snap download charts does.

See hat PR for discussion with @lyubomir-popov about whether to fix this by left-aligning the header, or by making all snapcraft.io pages the same width.

[Noticed again by @therealjuan in [snapcraft-design#410](https://github.com/CanonicalLtd/snapcraft-design/issues/410).]

**Comment by Lukewh** [comment]
maas.io, vanillaframework.io, landscape.canonical.com and jujucharms.com all have 'full width' navigation bars, so we should reflect this with snapcraft.io and build.snapcraft.io

**Comment by lyubomir-popov** [comment]
@Lukewh I may be unaware of some discussions, but I don't think an argument like "landscape or vanilla is full width, so snapcraft should also be" is a sound one.

To take that logic to an extreme, pls consider the following examples:
• In the cases of docs sites, including the snapcraft docs, the full width applies to the body of the site too. Does that mean we need to make the body of snapcraft.io and all other product sites full width?
• all of the above sites are on vanilla 1.6, does that mean we need to roll back any updates to vanilla 1.8/2.0?

On the other hand, the new ubuntu.com (staging.ubuntu.com) was just transitioned to fixed width nav. 
the argument in both cases has been about:
• managing white space 
• reducing mouse travel distance
• reducing visual noise created by staggered "keylines"

I think that together with snapcraft.io, they set a direction that has been well liked from all levels of stake holders so this feels like a step back.


Vanilla does allow individual sites to pick between fixed vs fluid, both when it comes to nav width and body width. Unfortunately it doesn't specify which should be used when. I think we've had a useful [discussion](https://github.com/CanonicalLtd/snapcraft-design/pull/294#issuecomment-369528129) on the pros and cons matching / missmatching width between header and site body in this issue with @matthewpaulthomas, and I think this merits a more thorough review before being changed.

**Comment by therealjuan** [comment]
Some sections of the site have different widths because they are using different codebases and currently the shortest path to achieving consistency across the whole site is to move to a fluid nav, there will be a greater consistency than what we have right now. 

The docs will have some facelifting coming soon which will allow us to have more control over the header width, and it will be easier to move to the new world as everything will have a consistent header.

If this is a step back...
* Why Vanilla allows you to choose between fixed or fluid without any further details? 
* Why not specifying when to use one or the other on Vanilla? Is this tracked on Vanilla somewhere?
* Is this issue from other sites being raised on other repos / products? 
* How do we keep track of those changes?
