### ISSUE TITLE
Puzzling claim that “Snapcraft.io is in Beta”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#596]
1\. Go to [https://snapcraft.io/account/snaps](https://snapcraft.io/account/snaps).

What you see:
![snapcraft io-beta](https://user-images.githubusercontent.com/19801137/39298268-a4333974-493d-11e8-923d-fb0bb2b00abe.png)

What’s wrong with this: If snapcraft.io ever was in beta, it was for a brief period in 2016. The site long since left that point.

What you should see: Something like “Thanks for trying these new pages. `Return to Dashboard` for other functions. `Bug reports welcome`.”

**Comment by therealjuan** [comment]
Here is a suggestion: 

> **Missing anything?** We are migrating functionality from the old version. 
> [Visit dashboard.snapcraft.io (external icon)](https://dashboard.snapcraft.io/snaps) or [report an issue (external icon)](https://github.com/canonical-websites/snapcraft.io/issues).

![image](https://user-images.githubusercontent.com/8167677/39995958-d99a4238-5775-11e8-95dd-85cd3dad02a7.png)

thoughts @matthewpaulthomas @Greggless ?
