### ISSUE TITLE
Hero strip seems tight to the congrats strip

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/snapcraft.io#598]
It looks to me that the hero strip on the account page is to tight to the Congratulates strip:
![screenshot-2018-4-26 my snaps linux software in the snap store](https://user-images.githubusercontent.com/1413534/39303051-ad674580-494c-11e8-8850-90eb992f4e60.png)

**Comment by shivjoshi1996** [comment]
Fixed
