### ISSUE TITLE
Single snap table looks like it has extra margin at the bottom of the row

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/snapcraft.io#599]
When you have a single snap the `<hr/ >` below the table looks like the bottom of the table:
![screenshot-2018-4-26 my snaps linux software in the snap store 1](https://user-images.githubusercontent.com/1413534/39303219-37eaa580-494d-11e8-8cf2-267a140ebc07.png)

**Comment by Greggless** [comment]
@anthonydillon the version is a string, typically it's some form of semantic versioning with `+git298347274`, so it'll stay left aligned.

**Comment by Lukewh** [comment]
Removing from the current iteration. To be addressed when Vanilla.1.7.* is applied to snapcraft.io (see https://github.com/canonical-websites/snapcraft.io/pull/681)
