### ISSUE TITLE
Improvement suggestions to screenshots section of account page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/snapcraft.io#600]
I have two suggestions for improvements:
- It would be nice to provide tooltips (or at least titles) to icon buttons to make it clear what they will do.
- Update the title from "Screenshots (up to 5):" to "Screenshots (2 of 5):"

![screenshot-2018-4-26 listing details for documentation-builder](https://user-images.githubusercontent.com/1413534/39303384-d163ce30-494d-11e8-95ed-76b081df36af.png)

**Comment by Lukewh** [comment]
We don't have the toolbar anymore, closing!
