### ISSUE TITLE
No indication of upload progress/state when saving changes - listing page

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#602]
When saving/applying changes I've made on the listing page I expect there to be so indication that the changes are being applied, maybe some kind of spinner in the 'Save' button:

![image](https://user-images.githubusercontent.com/23459065/39367498-ca974bd6-4a2e-11e8-9b8c-7de5ef58c16c.png)

**Comment by matthewpaulthomas** [comment]
![spinner in a button](https://user-images.githubusercontent.com/19801137/39466614-ca546b04-4d21-11e8-8e57-64a7c0c9ae0b.png)

**Comment by Greggless** [comment]
- Lyubo to Vanilla design it
- Bartaz to implement on snapcraft

**Comment by lyubomir-popov** [comment]
@bartaz If it takes very long maybe we need to keep a word in there, like:
[  O  Signing in...     ] (The "O" is a placeholder for the spinner)

But if it is a quick thing I think can remain as is.

**Comment by bartaz** [comment]
@lyubomir-popov In BSI we initially had [ O Signing in... ] kind of buttons, but they made layout move around as 'loading' button was significantly bigger then default one, so we moved to solution with just a spinner and no width change. But I understand your concern about user loosing context of what is in progress.

I will start with 'just a spinner' implementation from BSI and we will check how it works in practice.

**Comment by matthewpaulthomas** [comment]
The build.snapcraft.io change mentioned above was [build.snapcraft.io#662](https://github.com/canonical-websites/build.snapcraft.io/issues/662). But form submissions there don’t involve large uploads.

If an upload takes long enough that people start wondering whether it’s stalled, then static text (“Uploading…” or similar) wouldn’t really solve that problem. And dynamic text, precise enough to be reassuring, wouldn’t fit inside the button anyway: for example, “Uploading… (460 KB of 3.4 MB)”. Text like that could go alongside the buttons instead.

Just changing the button label to an indeterminate spinner would be a big improvement. The next step would be using a determinate spinner during uploads, switching to an indeterminate one while waiting for a response. The next step beyond that would be adding dynamic progress text alongside.

Whatever the presentation, though, please suppress it for the first two seconds (as in [build.snapcraft.io#661](https://github.com/canonical-websites/build.snapcraft.io/issues/661)), to avoid momentary flashing and making the site seem slower.
