### ISSUE TITLE
Add snap-categories or any possibilty to browse through all available snaps

### ISSUE THREAD

**Issue by 2a747** [canonical-websites/snapcraft.io#631]
Either I am blind or this really doesn't exist yet. I am thinking of something similar like how Flathub does it (https://flathub.org/apps).

**Comment by therealjuan** [comment]
Thanks for the feedback. 

We are constantly improving the Snap Store and adding categories is on our to-do list. We acknowledge that being able to browse different categories to find Snaps that are relevant to you is a high priority.

Stay tuned!
