### ISSUE TITLE
Map on directory page seems to show absolute, not relative numbers (?)

### ISSUE THREAD

**Issue by robert-ancell** [canonical-websites/snapcraft.io#632]
If I click though the 16 featured snaps they all (suspiciously) show the USA as being the dominant location where people are using these snaps. What this indicates to me is the map is constructed using the total number of installs - because the USA has a large population this dominates the statistics.

What would probably give a better indication is to show (number of snap installs) / (number of devices in that country) on the graph. That would better show in which countries a snap is popular (i.e. Germans are more likely to install this snap than Americans) rather than where the most users are (i.e. there are twice as many users of this snap in America, but with a population four times Germany that's not surprising).

**Comment by nottrobin** [comment]
Hi @robert-ancell, thanks for taking the time to contribute.

I agree that "snap installs as a percentage of active devices per country" would be interesting data to see mapped. However, it would be a fundamentally different graph from what we're currently showing, and I'm not sure it would be a better *default* map - total number of installs seems much more likely to be what people would intuitively expect from such a map.

We'll certainly keep this idea in mind, and perhaps add it as a new map or an enhancement to the existing one in the future.

However, for now we're going to leave the default map based on total installs. I'll update this ticket if we decide to do any work towards mapping relative numbers in the future.
