### ISSUE TITLE
When tracks are numbers, order in descending values

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#645]
1\. Go to [snapcraft.io/node](https://snapcraft.io/node)
2\. Click on 'Tracks' dropdown

### Expected behaviour
See Node's tracks listed like this:
- Latest
- 10
- 9 
- 8
- 6
### Current behaviour
![image](https://user-images.githubusercontent.com/23459065/39859318-6b58a662-5431-11e8-979d-50f3b5168632.png)

**Comment by matthewpaulthomas** [comment]
Most file managers sort filenames the way that we want here. For example, “blah(9)” < “blah(10)” < “blah(11)” etc.

Basically, any group of consecutive integers is treated as a number.
