### ISSUE TITLE
Unable to change license

### ISSUE THREAD

**Issue by michaelrsweet** [canonical-websites/snapcraft.io#647]
### Expected behaviour

The snap editing page used to have a way to change the license, but the new one is missing that functionality. I just published my latest snap (rasterview) and had to go to the old site to make the change (from the default "proprietary" to "Apache License 2.0")

### Steps to reproduce the problem

Edit a snap listing. Look for a control to change the license.

### Specs

- _URL:_https://snapcraft.io/account/snaps/rasterview/listing
- _Operating system:_macOS 10.13.4
- _Browser:_Safari (11.1.1)

**Comment by therealjuan** [comment]
Thanks for bringing this into our attention. We are currently working on moving functionality the ability to change a snap license using snapcraft.io. Please check again in the coming weeks as soon will be available. Stay tuned!
