### ISSUE TITLE
Screenshots' images are not optimized (don't have thumbnails)

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#649]
Publishers upload their screenshots to the store and what we show to users on public snap details page and publisher listing page is exactly the file uploaded by publisher (even if shown on much smaller size). This causes performance issues.

For example skype (https://snapcraft.io/skype) has 3 screenshots, each over 3MB big (5692x3200px).
Every time users visit snap details page they need to download over 10MB of screenshots even if they never open them fullscreen and only look at thumbnails (which currently on snap details page are displayed as 240px high).

### Expected behaviour:

Ideally store API should provide thumbnails (smaller versions of images), so we can display smaller versions of screenshots without the need to download original full size images

Or we should try to find some other way to reduce the size of screenshots downloaded.

**Comment by mattiamari** [comment]
The blog homepage should receive the same treatment.

**Comment by shivjoshi1996** [comment]
This has been solved by using Cloudinary.
