### ISSUE TITLE
Add "install" button for snap enabled Ubuntu

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#652]
Part of https://github.com/CanonicalLtd/snappy-design-squad/issues/471 epic

As discussed in review meeting we want to add top level 'Open in Gnome software' button for users that we know are on Ubuntu 16.04+ (which default Firefox installation should tell us).

Versions for users when we don't know if snaps are supported (same as current version, 'View in store' button will be added to channel map overlay as part of https://github.com/CanonicalLtd/snappy-design-squad/issues/471):
<img width="1061" alt="screen shot 2018-05-11 at 12 36 08" src="https://user-images.githubusercontent.com/83575/39920734-68bc65f0-5518-11e8-93e4-3f1d05a5ddf1.png">

When we know user is on supported Ubuntu version:
<img width="1048" alt="screen shot 2018-05-11 at 12 39 06" src="https://user-images.githubusercontent.com/83575/39920779-8fd66316-5518-11e8-81bb-f14d368d6d56.png">

### Copy as discussed in comments:

Install stable version | - | -
-- | -- | --
`[sudo snap install spotify]` | - | **`[Open in Gnome Software]`**
View all versions | - | [Install using snapd](https://docs.snapcraft.io/core/install)

**Comment by bartaz** [comment]
@therealjuan (cc @Greggless)

Could you confirm that naming of 'Open in Gnome software', and placement of 'show all versions' is fine with the direction that we want install instructions to go?

**Comment by Greggless** [comment]
I'd say that we should swap `show all versions` with `... you'll need snapd`

| Install stable version | - | - |
| :- | - | - |
| **`[sudo snap install spotify]`** | - | **`[Open in Gnome Software]`** |
| View all versions | - | [Get set up for snaps](https://docs.snapcraft.io/core/install) |

**Comment by therealjuan** [comment]
I agree with @Greggless points but perhaps we could change the copy below the GNOME button ...

Install stable version | - | -
-- | -- | --
[sudo snap install spotify] | - | [Open in Gnome Software]
View all versions | - | **_Install using snapd_**

**Comment by bartaz** [comment]
@Greggless @therealjuan Yes, thanks.

Shorter copy is good, as this button already barely fits into this part of grid.

Will show updated screenshots in PR when I have it implemented and we can iterate on in there.

**Comment by bartaz** [comment]
Unfortunately after a quick check and verifying with @nottrobin we found, that we **can't** reliably tell that user is on snap-enabled version of Ubuntu.

While default installation of Firefox does tell us that it runs on `Ubuntu` it doesn't tell on which version, which means we can't tell if users OS supports `snap://` protocol or not.

And because we can't assume that all Ubuntu users (or even vast majority) have snaps enabled, we cannot show install button by default to anyone.

/cc @Greggless @therealjuan

**Comment by Greggless** [comment]
![image](https://user-images.githubusercontent.com/23459065/39924872-6ee196a4-5521-11e8-8620-e14c31d608db.png)
