### ISSUE TITLE
Failure mode talking to api causes resource starvation

### ISSUE THREAD

**Issue by jayk-canonical** [canonical-websites/snapcraft.io#661]
API calls from snapcraft.io to api.snapcraft.io can hang when api.snapcraft.io is responding slowly.  

Because the worker is waiting for a response from the api, it can not service further requests.  Once this happens a few times the snapcraft.io has no workers left to service new requests.

### Expected behaviour
Expected behavior is for calls to error out and leave the application running, so that when the API recovers, the site recovers as well.

### Steps to reproduce the problem
Slow down the api.snapcraft.io response time, send lots of traffic to snapcraft.io URLs that hit the API.

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by shivjoshi1996** [comment]
Fixed
