### ISSUE TITLE
How to report snaps?

### ISSUE THREAD

**Issue by Podesta** [canonical-websites/snapcraft.io#662]
What is the standard procedure to report snaps that violate the terms and conditions, or for any other reason? I could not find a single report button in the snapcraft.io.

For example, the snap [acestreamplayer](https://snapcraft.io/acestreamplayer) is distributed with a proprietary license, despite being built on the [VLC](https://www.videolan.org/legal.html), which uses GPL. Using this snap as example, how would one go to report it, since it is in violation of the [terms and conditions set by canonical](https://www.ubuntu.com/legal/terms-and-policies/developer-terms-and-conditions)?

**Comment by bartaz** [comment]
@Podesta Thanks for your report.
At the moment the best place for such report would be store section of snapcraft forum: https://forum.snapcraft.io/c/store

We will try to make it more clear from snapcraft.io website how to report such issues.

**Comment by Podesta** [comment]
Thanks for clarifying. I'll make future reports over there.

**Comment by Podesta** [comment]
Was it fixed? I don't think there are any links in the snaps pages linking to the froum as the place for reports. Or was it deemed not necessary?

**Comment by shivjoshi1996** [comment]
Hi @Podesta, thanks for the issue, since this needs some UX input,  we've created an issue on the design repo and we will be triaging and working on it shortly. Thank you!
