### ISSUE TITLE
Make Install more prominent and remove duplication

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#666]
This is an iteration from #620 and #653 and based on [this design](https://github.com/CanonicalLtd/snapcraft-design/blob/master/public-facing/install-button/Snap%20details%20with%20install%20button.png)

## Current status

![image](https://user-images.githubusercontent.com/8167677/40164612-f8337078-59b1-11e8-85ee-1a45422dfa29.png)

On the top section of a Snap details page, we are directing users to either install using Command line or View All versions. We recently added the ability to install with one button using a Desktop store with snap support (i.e. GNOME Software).

![image](https://user-images.githubusercontent.com/8167677/40164630-01195a4a-59b2-11e8-8969-480e97e4abfe.png)

As it currently stands the command line stays on the top of the page and if a user clicks on Install, we are showing the same information again as well the ability to install from the store (and visit all versions).

## How to iterate the current solution?

- Move `command-line instructions` from the header to below the snap description
- Make `Install` a primary call to action
- Reduce copy from `Show All Versions` to `All Versions`
- `Install` and `All versions` open their relevant tabs on the Channel map

![image](https://user-images.githubusercontent.com/8167677/40164793-6a832e0c-59b2-11e8-9616-26b9484834fb.png)

**Comment by evandandrea** [comment]
I think this is absolutely a step in the right direction, +1. We want the desktop install button to feel like the obvious choice and for there to be few steps to reach it. I understand the latter to be dealt with in a later cycle, but reducing the prominence of the CLI instructions over the desktop ones is tractable now.

**Comment by evandandrea** [comment]
I would drop the CLI instructions from the landing page altogether, rather than move them below the description.

**Comment by Podesta** [comment]
While I agree that making the install action more prominent is great, especially for new users, I don't think hiding the CLI too much is great either, otherwise you will be alienating other users. 

The gone-software is fairly sluggish. It takes at least a solid minute before I can interact with it.

While I feel that it fits in the header while still looking clean, moving it to the bottom of the description is a decent compromise and far better than removing it from the landing page altogether.
