### ISSUE TITLE
Unnecessary horizontal line when no screenshots

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#673]
Go to snap details that doesn't have screenshots: https://staging.snapcraft.io/core

New updated layout (with horizontal lines) doesn't work well if there is no screenshots. There should be no line on top.

<img width="1066" alt="screen shot 2018-05-17 at 13 41 25" src="https://user-images.githubusercontent.com/83575/40175533-b20183ac-59d8-11e8-8bae-e2d5b2a517d3.png">

**Comment by Lukewh** [comment]
Fixed by https://github.com/canonical-websites/snapcraft.io/pull/683
