### ISSUE TITLE
A lone `<hr>` wanders the wild on a snap details page with no screenshots

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#675]
### Expected behaviour
- there not to be a `<hr>` at the top of the page when there are no screenshots for a snap

### Steps to reproduce the problem
- go to https://snapcraft.io/node
- look at a page with no screenshots
- see a `<hr>`...
- _**see a `<hr>`?!**_

### Screenshot
![image](https://user-images.githubusercontent.com/23459065/40228334-e92d76fa-5a88-11e8-8fb9-ce378b96a12a.png)

**Comment by Lukewh** [comment]
This was previously fixed and has now been deployed to snapcraft.io
