### ISSUE TITLE
Screenshots carousel: No arrows needed with 2 screenshots

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#677]
Visiting a Snap page with 2 screenshots displays left / right arrows to navigate through but on a Desktop is not needed on the layout

![image.png](https://images.zenhubusercontent.com/56b0a0916caf56c9d38c2685/6adadc65-f64e-41b9-a77b-c8f1d09618b0)

**Comment by Lukewh** [comment]
With larger images this isn't an issue when you have 2 screenshots (as only 1 fits fully) but even with 1 image, the scroll arrows don't show!
