### ISSUE TITLE
Enable a more intellegent "install" button

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#679]
We can't provide a simple "install" button on snap detail pages because it is currently impossible to detect support for the `snap:.//` protocol - as [discussed on the forum](https://forum.snapcraft.io/t/no-more-install-button/4613). We have [now implemented](https://github.com/canonical-websites/snapcraft.io/issues/666) a fairly neat fallback.

Although [it will likely never be possible to directly detect support for `snap://`](https://stackoverflow.com/questions/2872090/how-to-check-if-a-custom-protocol-supported), another option is to *infer* support by detecting the OS version.

This also is not currently possible, but there may be avenues we could explore to make it possible -I'm creating this issue to track these explorations:

1. Canonical explicitly set the user-agent string in the official Firefox and Chromium packages in the Ubuntu sources (although not in the snaps). These currently say "Ubuntu", but it may be possible to expand this to include the OS version. This solution would only be partial (as not everyone will be using a browser from the official Ubuntu sources), and temporary (at some point these packages will likely be replaced by snaps) but it would allow us to at least detect users of Ubuntu default packages, which will likely be the majority, for the time being.
2. Ask Firefox and Chromium to include more information about the Linux distribution in the `Navigator` object - likely in the `oscpu` property. I've filed [a bug to ask Mozilla to add this to Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1463208) - we'll see how that goes.

**Comment by shivjoshi1996** [comment]
Achtung!

**Comment by nottrobin** [comment]
I emailed Chris Coulson and Olivier Tilloy to ask about the possibility of updating the user-agent string:

> Hello Chris and Olivier
> 
> I mentioned this to Will Cooke a while ago and he suggested you were the people to ask about the Firefox and Chromium Ubuntu packages respectively.
> 
> Background:
> 
> We're trying to find a way to provide an easy way to install snaps from http://snapcraft.io. If you look at e.g. https://snapcraft.io/lxd, you'll see that when you click "Install" it shows an overlay that explains your options. You then need to click "View in Desktop store" if you want to install through the Ubuntu Software application - which is a somewhat cumbersome, less than ideal, experience. If you aren't on a supported version of Ubuntu, clicking that button would result in an error saying snap:// isn't a recognised protocol.
> 
> The ideal would be to detect with absolute certainty that a user's browser has support for the "snap://" protocol to install a snap from a desktop application (e.g. the Ubuntu Software app), and then provide an obvious "Install" button that would simply open the snap in that app for installation.
> 
> Direct detection of third-party protocols is not supported in any browser, and likely will never be, because of security implications e.g. fingerprinting. The alternative is to instead detect which OS version a user is running, and then provide a nice "install" experience if we know the OS has snap:// support by default - e.g. "Ubuntu 18.04". This would allow us to provide a nice, accurate experience for the vast majority of snap-supporting systems, and the vast majority of non-supporting systems. Unfortunately, all that browsers expose by default is "Linux", and Mozilla at least don't seem receptive to providing more information through standard APIs.
>
> *The point:*
>
> I noticed that in the Firefox and Chromium packages that come from Ubuntu sources, the user-agent string has been changed to include "Ubuntu", but this in itself is not enough to infer snap support. I believe in the past it used to contain the Ubuntu version as well (e.g. "Ubuntu 12.04"), which would allow us to infer support.
> 
> Is there any chance it would be possible to go back to including the version of Ubuntu in the user-agent string for the Firefox and Chromium packages? Or to otherwise include something in the user-agent string that would allow us to detect a snap-supporting system from https://snapcraft.io? This would then mean that we could at least infer snap support for Ubuntu users using these core packages, which would be the majority of snap users.

**Comment by therealjuan** [comment]
From: Oliver Tilloy
> That certainly looks acceptable to me, and easy enough to implement.
The UA string already includes a "Linux" token:
>
>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
Ubuntu Chromium/67.0.3396.99 Chrome/67.0.3396.99 Safari/537.36
>
>so do we want to be redundant with "Linux snap" (in place of
"Chromium"), or is "snap" alone sufficient?
From: Robin Winslow
> From my side, just "snap" would be fine, since Linux is already there.

From: Oliver Tilloy
> Sorry for the lack of feedback. I haven't forgotten about this, but I
have been busy with higher priority tasks. I have created a card in
our team's trello board to track the task:
https://trello.com/c/Hyrd2pqj/177-add-snap-identifier-to-chromium-snaps-ua-string,
and I will get to it as soon as I can.

The work can be tracked here:
https://trello.com/c/Hyrd2pqj/177-add-snap-identifier-to-chromium-snaps-ua-string
