### ISSUE TITLE
Some Apps Doesn't Support Some Languages

### ISSUE THREAD

**Issue by okanakinci** [canonical-websites/snapcraft.io#692]
Some Snap Apps support either only English or a few languages.

For Example, Libreoffice and VLC doesn't support Turkish.

I want use this apps in my native language. Can you add Turkish language support?

**Comment by Lukewh** [comment]
Hi @okanakinci,

You'll need to get in touch with the app developers to request additional language support.

You can contact Libreoffice [here](http://www.libreoffice.org/get-help/community-support/) and VLC [here](https://www.videolan.org/support/).

I hope this helps.
