### ISSUE TITLE
You should check a little bit what is published

### ISSUE THREAD

**Issue by mvvvv** [canonical-websites/snapcraft.io#704]
### Expected behaviour
Blender from Gustavo Niemeyer with bad icon and very bad licence ... a stable version of an early alpha version (2.80 !!!)

### Steps to reproduce the problem
Open Ubuntu Software and see that version recommended ??!!!
### Specs

- _URL:_ https://snapcraft.io/blender
- _Operating system:_ Ubuntu 18.04
- _Browser:_ firefox

**Comment by therealjuan** [comment]
Hello,

Thanks for bringing this into our attention. We are working on ways to help identify verified publishers so we will take your feedback into account.
