### ISSUE TITLE
new account/snaps page lists released snap as never-pushed-to

### ISSUE THREAD

**Issue by chipaca** [canonical-websites/snapcraft.io#716]
If I go to https://snapcraft.io/account/snaps I'll get, at the bottom of the page, a “Names you own but have not pushed a snap to” list, and it includes `xbill-xaw` (and this snap is not listed in the table above this message).

This snap has been pushed to, and released, and is used by people all over as you can see if you go to https://snapcraft.io/account/snaps/xbill-xaw/metrics.

If I had to guess I'd say this might be related to it being the only snap whose title I've edited to be different to its name. But it might be something else :-) so fortunately I don't have to guess.

Over to you.

**Comment by cprov** [comment]
There were 2 name records in revoked state 'clobbering' the API results. They are now removed and an active xbill-xaw entry should be displayed in your account page.

See https://bugs.launchpad.net/snapstore/+bug/1763721 for more information.

**Comment by therealjuan** [comment]
Closing this issue as it seems fixed from a snapcraft.io POV but the underlying issue needs addressing.
