### ISSUE TITLE
Email for "Provide instructions..." marked as potentially phishing

### ISSUE THREAD

**Issue by Saviq** [canonical-websites/snapcraft.io#729]
### Expected behaviour
"Provide instructions..." emails in Thunderbird are not flagged.

### Steps to reproduce the problem
Publish a snap in `stable` channel, wait for the email.

The reason is that the http://snapcraft.io/subsurface/ link actually points to http://mkto...

### Specs

- _URL:_ http://mkto-g0030.com/v/E0h0E2HmORg0f05V0t02V08
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Thunderbird

**Comment by therealjuan** [comment]
Thanks for bringing this into our attention. We are currently improving our email messaging to avoid use cases like this and avoid mixed content errors on it.
