### ISSUE TITLE
"Provide instructions..." web view not fully encrypted

### ISSUE THREAD

**Issue by Saviq** [canonical-websites/snapcraft.io#730]
### Expected behaviour
Green padlock on the address bar.

### Steps to reproduce the problem
Publish an app in the `stable` channel, wait for the email and click on "To view this email as a web page, click here".

### Specs

- _URL:_ http://mkto-g0030.com/v/E0h0E2HmORg0f05V0t02V08
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

**Comment by therealjuan** [comment]
Thanks for bringing this into our attention. We are currently improving our email messaging to avoid use cases like this and avoid mixed content errors on it.
