### ISSUE TITLE
My published snaps - public vs. private

### ISSUE THREAD

**Issue by ralight** [canonical-websites/snapcraft.io#769]
### Expected behaviour

On the page https://snapcraft.io/account/snaps , I have a list of my published snaps. There is a Privacy column. I would expect this to reflect the public/private state of the snap. I have one snap currently set to private where this column still says public. When I click on the snap to get to https://snapcraft.io/account/snaps/mosquitto-simple/listing the snap is listed as private as expected.

### Steps to reproduce the problem

Go to https://snapcraft.io/account/snaps with a private snap. I haven't tried to change the status of the snap to see if it fixes itself.

### Specs

- https://snapcraft.io/account/snaps
- https://snapcraft.io/account/snaps/mosquitto-simple/listing
- Chrome

**Comment by Lukewh** [comment]
Hi @ralight,

Sorry about the issue. A few months ago there was a bug with the API ([launchpad bug](https://bugs.launchpad.net/snapstore/+bug/1766835)) that should have been fixed.

Have you recently set the snap to private or has it been private for some time? If so you might need to flip between private and public to propogates the change. If that doesn't work, let us know and we'll investigate further.
