### ISSUE TITLE
Blacklist & Whitelist on publisher pages

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#784]
As a snap publisher I want to be able to black and white list different countries to distribute my snaps on relevant regions.

Users will be able to CRUD (create, read, update and delete) information about countries / regions where a snap is being able to be distributed.

This functionality is already present at dashboard.snapcraft.io

![image](https://user-images.githubusercontent.com/8167677/41662037-753b6ac2-74a0-11e8-83e6-c7959b7efdf8.png)

**Comment by Greggless** [comment]
Dashboard allows a user to define both a blacklist _and_ a whitelist for their software. I don't think this makes sense. Hence I've made it a binary choice to black or whitelist. 

In Snapcraft a user will be able to 'turn on' distribution list, choosing whether to black or whitelist specific countries. The distribution list is switched off by default meaning the software is freely distributable to all countries

For `Blacklist` and `Whitelist` UI I would recommend using [this multiple search and select](https://semantic-ui.com/modules/dropdown.html#multiple-search-selection) pattern. 

### Distribution list - OFF
![image](https://user-images.githubusercontent.com/23459065/42037657-dff40572-7ae0-11e8-9064-b0a0eb5a8ee9.png)

### Distribution list - ON - Whitelist
![image](https://user-images.githubusercontent.com/23459065/42038356-a6b32192-7ae2-11e8-9e07-12136b0c30fa.png)


### Distribution list - ON - Blacklist - Drop down
![image](https://user-images.githubusercontent.com/23459065/42038078-f1271658-7ae1-11e8-8540-6e31836f5c97.png)

### Distribution list - ON - Blacklist - Drop down
![image](https://user-images.githubusercontent.com/23459065/42038233-53a6b02c-7ae2-11e8-8352-a94794148884.png)


### Distribution list - ON - Blacklist - Drop down - Selection made
![image](https://user-images.githubusercontent.com/23459065/42038197-413ab9ce-7ae2-11e8-9f00-986bf4ef7bfc.png)

**Comment by therealjuan** [comment]
I believe that in some use cases it is easier to provide both controls to publishers as it might happen that you are operating with a certain technology or set of business rules that can be obsolete due to new legislation and that could be quite tricky to achieve with a simple binary choice.

On the other hand, what you propose can be achieved if we allow publishers to decide when a country is either black or whitelisted within the country list and is able to see a summary of white and blacklisted countries working as tag clouds as you envisioned.

Thoughts?

**Comment by Greggless** [comment]
Maybe I'm misunderstanding what it is to black or whitelist, but I thought they were mutually exclusive. 

So I couldn't have BOTH a blacklist AND whitelist as they contradict eachother?

**Comment by matthewpaulthomas** [comment]
A switch, that enables/disables a pair of radio buttons, can be simplified to three radio buttons:
```
This snap should be available in:

(*) All territories

( ) All territories except these ones:
    [_________________________________________]

( ) Only these territories:
    [_________________________________________]
```

That would also remove the need for publishers to learn and remember what “distribution list”, “whitelist”, and “blacklist” mean in this context.

**Comment by Greggless** [comment]
@matthewpaulthomas I just updated the my first comment upon realising that!

**Comment by matthewpaulthomas** [comment]
Using the same field for entering the whitelist as for entering the blacklist is visually simpler. It feels a bit weird to me, though … A more specific complaint is that it’s more error-prone. Consider what happens if you change the radio button selection by mistake, from “except” to “only” or vice versa. Either way:
- With a single field, your snap ends up available for precisely, and only, the territories that you _didn’t_ want it available for. Aaaargh.
- With two fields, you’re blocked from submitting the form because the necessary field is empty. Phew.

(If you stay with a single field, though, don’t indent it — because that would imply it’s dependent on the single radio button above it, when it’s actually dependent on two of them.)

**Comment by therealjuan** [comment]
Good point @matthewpaulthomas. 

One option to avoid error or mistakes we can have the radio buttons disabled and include an additional link to allow changes to the list. Something like this:

```
This snap should be available in:

(*) All territories

( ) All territories except these ones:
    [_________________________________________]

( ) Only these territories:
    [_________________________________________]

[Make changes to snap distribution list]
```

It can behave similar to the lock functionality like in the system preferences of Mac OSX:

![image](https://user-images.githubusercontent.com/8167677/42081459-63319958-7b7d-11e8-92ff-ced89822f9aa.png)

**Comment by Greggless** [comment]
The design doesn't show, but selecting an option would invoke the tags field underneath the respective option. Hopefully the UI will be smart enough to remember any previously defined tags so if I accidentally click on a different option, the tags will still be there.

**Comment by matthewpaulthomas** [comment]
Ah, ok. So you aren’t reusing the same field, you’re just hiding whichever field is currently inapplicable.

The question of [whether to disable or hide a control](https://docs.google.com/document/d/1rzP9dEeo9gLngSM3BcMNDIOcxrQ1g3I4W8jPGXMVqSk/edit#heading=h.gmdm15yiynuw) is a subjective one. In this case I’d go for disabling, rather than hiding, for a couple of reasons. Less importantly, it’s a single-line text field on a scrolling Web page, so hiding it saves very little space or attention. More importantly, if “All…” was selected and you clicked “…only”, that radio button you had just clicked would jump upwards as the field above it disappeared!

**Comment by Greggless** [comment]
I'd prefer hiding as it reduces the number of elements on page. Also, if the '...all' field had a bunch of tags in it, then you selected the '...only' field there would be two fields with a tags in them, even in a disabled state, that might look a bit - meh - 😐. 

# Introducing the ADMIN page 🎉 
![image](https://user-images.githubusercontent.com/23459065/42087359-d434471c-7b8d-11e8-87c5-d7873ea6be7b.png)

**Comment by therealjuan** [comment]
LGTM

**Comment by Greggless** [comment]
@therealjuan 🐺 thanks, @lyubomir-popov WDYT?

**Comment by lyubomir-popov** [comment]
@therealjuan @Greggless As @matthewpaulthomas  mentioned, things will jump if you show / hide 2 token input fields. Reusing the same field sound better to me.

I've seen the following done, would something like this work if we take extra care to make it obvious what's going on? Maybe we could have the map underneath light up to indicate the current selection? This way, it would be impossible to confuse 3% covered with 97% covered when you tick the checkbox.

```

( • ) All
(   ) Custom:
       [____________________________]
       [ √ ] Exclude selected countries

```

**Comment by Greggless** [comment]
I like the custom option. But he `[ √ ] Exclude...' infers that the list is an include, I feel like making it explicit for each choice is possibly better. But we may be splitting hairs. How about the following as a best-of-both solution? 

```
This snap should be available in:
(   ) All territories
( • ) Custom list:
       ( • ) Only these territories
       (   ) Exclude these territories     
       [____________________________]

```

**Comment by matthewpaulthomas** [comment]
```
What would you like for dinner?
( ) Chicken
(•) Something else:
    (•) Burger with these fillings
    ( ) Pizza with these toppings
    [____________________________]
```
Having four radio buttons rather than three, requiring (slightly) more clicks on average, and using one text field for two very different purposes … all seems like a high price to pay, just to avoid having two text fields.

**Comment by Greggless** [comment]
I think that's missing some context:

```
What would you like for dinner?
( ) Everything on the menu
(•) A selection:
    (•) These dishes
    ( ) Not these dishes
    [____________________________]
```

If we think about what it will look like on the page. By default it would look like this:

```
What would you like for dinner?
(•) Everything on the menu
( ) A selection...
```

I would like to see usage statistics for if people use the white/blacklisting to back up this. If 95% of publishers don't bother and distribute their software freely then it may influence the design.

**Comment by lyubomir-popov** [comment]
@Greggless @matthewpaulthomas the last version by Greg above looks good to me.

**Comment by Greggless** [comment]
So to sign this off:
### Option A:
Two tag fields, one disabled based on selection
```
This snap should be available in:
(   ) All territories
( • ) Custom list:
       ( • ) Only these territories
       [____________________________]
       (   ) Exclude these territories     
       [____________________________]

```

### Option B:
A single tag field, based on selection
```
This snap should be available in:
(   ) All territories
( • ) Custom list:
       ( • ) Only these territories
       [____________________________]
       (   ) Exclude these territories     

```

### Option C:
One tag field for both selections
```
This snap should be available in:
(   ) All territories
( • ) Custom list:
       (   ) Only these territories
       ( • ) Exclude these territories     
       [____________________________]

```

**Comment by matthewpaulthomas** [comment]
> If we think about what it will look like on the page. By default it would look like this:
>
> ```
> What would you like for dinner?
> (•) Everything on the menu
> ( ) A selection...
> ```

I didn’t know that the whitelist+blacklist controls would be absent when “All territories” is selected. Unfortunately, that doesn’t address any of [those three drawbacks](#issuecomment-402681546). It does, however, add three _more_ drawbacks:
- “Custom list:” followed by nothing, until the next divider, could make people think the form hadn’t loaded properly.
- As soon as someone clicked “Custom list”, everything below it on the page would jump downward.
- As soon as someone clicked “All territories”, everything below it on the page would jump upward.

Out of A B and C, I think A is least bad, because it has less visual variation than B, and it’s much less error-prone than C.

**Comment by Greggless** [comment]
We have our solution

# A 🎉 🎆 💥
