### ISSUE TITLE
Keywords on publisher pages

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#785]
As a snap publisher I would like to add relevant keywords to my published snaps to help when searching for new snaps to install from snapcraft.io and other relevant channels.

This is functionality already present at dashboard.snapcraft.io 

![image](https://user-images.githubusercontent.com/8167677/41662010-60170638-74a0-11e8-8ec3-7c414b35c394.png)

**Comment by Greggless** [comment]
There is no limitation on the amount of keywords a publisher can submit for their software. This could lead to people spamming key terms in order for it to show up in more searches. I recommend using a maximum of 5 (used mixcloud.com as an example).

### Keywords 
![image](https://user-images.githubusercontent.com/23459065/42042184-827eecbc-7aeb-11e8-8158-ceb1520223fa.png)

### Keywords - added
![image](https://user-images.githubusercontent.com/23459065/42042189-85955f62-7aeb-11e8-8646-78ca1fddc2aa.png)

**Comment by therealjuan** [comment]
👍 

Perhaps in a next phase we can include some form of intelligence to include suggestions based on: keywords from  snaps with a similar name, keywords related to other keywords you entered in the input field...

**Comment by Greggless** [comment]
Yes, my thoughts exactly. We did some exploration around something category tags with a 'type-ahead' style interaction. Happy to explore in the coming iteration.
