### ISSUE TITLE
Link to "Developer Website" is actually a mailto link

### ISSUE THREAD

**Issue by popey** [canonical-websites/snapcraft.io#80]
Via https://forum.snapcraft.io/t/first-signs-of-a-storefront/2316 I discovered https://snapcraft.io/ohmygiraffe/ (a snap I uploaded) which has the text "Developer Website". 

![image](https://user-images.githubusercontent.com/1841272/31047020-0f2ac3c0-a5d1-11e7-956c-8fc97eff4f92.png)

This should probably say something else, because the store allows both websites and mailto links.

![image](https://user-images.githubusercontent.com/1841272/31047013-f47f5bc6-a5d0-11e7-893a-7d9cef4acbc4.png)

**Comment by Lukewh** [comment]
This should now be fixed
