### ISSUE TITLE
Spotify logo looks blury

### ISSUE THREAD

**Issue by 8none1** [canonical-websites/snapcraft.io#831]
On the home page of snapcraft.io there are a number of software vendor logos.  The Spotify one looks blury while the others are clear.  The icon appears to be a PNG embedded in an SVG.

https://assets.ubuntu.com/v1/e44026ff-Spotify_Logo_RGB_Green+Copy.svg

**Comment by therealjuan** [comment]
That SVG has an embedded PNG. Here you can find one with proper vector capabilities:

https://assets.ubuntu.com/v1/2400d5a7-Spotify_logo_with_text.svg

**Comment by therealjuan** [comment]
That SVG has an embedded PNG. Also, there is an issue with the baseline of the amazon logo.

Here you can find amazon and spotify logos as SVG and aligned baselines:

https://assets.ubuntu.com/v1/f89725e5-logo-spotify.svg
https://assets.ubuntu.com/v1/982d0fe8-logo-amazon.svg

**Comment by therealjuan** [comment]
@lyubomir-popov will do some work aligning all logos

**Comment by lyubomir-popov** [comment]
All logos need to be replaced as they are note resized to look well next to each (using our logo alignment template).

I've uploaded them here:
https://manager.assets.ubuntu.com/?q=snapcraft.io-homepage
