### ISSUE TITLE
 I can't find many snap packages like ( firefox , VLC )

### ISSUE THREAD

**Issue by YousefSaber** [canonical-websites/snapcraft.io#832]
can't find or install snaps

https://snapcraft.io/firefox

https://snapcraft.io/vlc

```
yousef@yousef-G31M-ES2L:~$ sudo apt install snapd
[sudo] password for yousef:
Reading package lists... Done
Building dependency tree
Reading state information... Done
snapd is already the newest version (2.32.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
yousef@yousef-G31M-ES2L:~$ sudo snap install vlc
error: snap "vlc" not found
yousef@yousef-G31M-ES2L:~$ sudo snap install firefox
error: snap "firefox" not found
```

I don't think that this issue is related to my 32 bit OS
because I can successfully install and find telegram desktop and gnome calculator which only have amd64 variant like firebox and VLC

**Comment by therealjuan** [comment]
In the specific cases of [Firefox](https://snapcraft.io/firefox) & [VLC](https://snapcraft.io/vlc), these snaps are only available for amd64 architecture. You can see this information on [snapcraft.io](http://snapcraft.io) if you click on *All versions* and open the Architecture dropdown. Currently, there are no versions available for 32-bit architectures for these snaps.

We are working on improving the messaging for snaps not available for a given architecture to avoid use cases like yours, so we can prompt you when a snap is available for certain architectures apart from the one you ran `snap install` from.

Thanks for bringing this to our attention 👍
