### ISSUE TITLE
Clicking screenshot checkbox twice quickly enlarges the screenshot

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#848]
1\. Go to the Listing page for a snap that you publish.
2\. If the snap doesn’t have at least one screenshot, upload one.
3\. Mouse over (or Tab to) a screenshot so that a checkbox appears over it.
4\. Click the checkbox twice quickly.

What happens: The screenshot enlarges to fill the viewport.

What should happen: Nothing. The checkbox should check and uncheck.

The enlarging-on-double-click behavior is implemented for the entire thumbnail. The checkbox should override it.

**Comment by Lukewh** [comment]
We don't have a lightbox on the listing page anymore so this issue is no longer relevant.
