### ISSUE TITLE
/account/register-name: No way to file dispute here.

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-websites/snapcraft.io#852]
### Steps to reproduce the problem
1. Browse /account/register-name
2. Attempt to register a reserved name

### Current behaviour
The attempt failed with `'_snap_name_' is a reserved name. `, no interface to file a dispute in order to take over the name

### Specs

- _URL:_https://snapcraft.io/account/register-name
- _Operating system:_KDE neon 5.13
- _Browser:_ Mozilla Firefox 60.0.2

**Comment by Lukewh** [comment]
Hi @Lin-Buo-Ren 

I've tried reproducing the problem by registering firefox, I receive the following:
![screenshot_2018-07-06 snapcraft - snaps are universal linux packages 1](https://user-images.githubusercontent.com/479384/42369618-6eab5280-8102-11e8-99ea-c3ac7efefa7b.png)

The notification at the top provides a link to https://dashboard.snapcraft.io/register-snap/, is this not the case for you?

If not can you let me know what name you tried to register (if it's sensitive you can reach me on freenode: Lukewh)

**Comment by popey** [comment]
Actually it doesn't work for blacklisted "reserved" names. Try repeating the process with "fd" which is a reserved name, not a registered one. I found this out via developer trying to [register](https://github.com/sharkdp/fd/pull/361) their own app name "fd". You do *not* get a link to the other register page.

![image](https://user-images.githubusercontent.com/1841272/49247068-4c341000-f40e-11e8-825c-734ac658dede.png)

**Comment by bartaz** [comment]
Can reserved names be disputed? As far as I understand reserved names cannot be registered by anyone. But probably we should explain it better on the page.

/cc @therealjuan

**Comment by Lin-Buo-Ren** [comment]
> Can reserved names be disputed?

Yes, those can: [Fork-and-rename-me: What to do when the "preferred upstream name" is already taken? - store - snapcraft.io](https://forum.snapcraft.io/t/fork-and-rename-me-what-to-do-when-the-preferred-upstream-name-is-already-taken/5866/3)

This article might need some update though: [Registering your app name - doc - snapcraft.io](https://forum.snapcraft.io/t/registering-your-app-name/6793)

**Comment by popey** [comment]
Yes. They can. Reserved names are just to prevent the land-grab headache of people registering snaps for common Linux executables. There's a pre-defined hard-wired [list](https://bazaar.launchpad.net/%7Eubuntuone-pqm-team/software-center-agent/trunk/view/head%3A/reserved-snap-names.txt) of around 90K binary names the store knows of, which was pre-seeded back at the start of the store.
