### ISSUE TITLE
Logo list not looking ideal on mobile 

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/snapcraft.io#854]
### Expected behaviour
On mobile, one logo is under the rest. It should be at least centered:
![image](https://user-images.githubusercontent.com/2741678/42288755-149f548e-7fb4-11e8-9b6a-464c3b86eef7.png)

### Steps to reproduce the problem
Inspect snapcraft.io homepage on mobile.
### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by Lukewh** [comment]
Fixed as part of https://github.com/canonical-websites/snapcraft.io/pull/845

![screenshot_2018-07-06 snapcraft - snaps are universal linux packages](https://user-images.githubusercontent.com/479384/42369369-a6280e8e-8101-11e8-94b5-fc48b0b76ab9.png)
