### ISSUE TITLE
Featured snaps on front page with verified developers badges

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#876]
Can we please make the featured snaps section on the front page of snapcraft.io consistent with snapcraft.io/store. I think bringing the verified developers badges and developer names to the front page featured snaps section would be a worthwhile addition. 

![79b1a57a-31a9-4d6b-8e15-27d9399cb3da](https://user-images.githubusercontent.com/1523179/42448285-a8e567d2-8374-11e8-82a5-50b6fdaf4808.png)
![31e1e77d-65e2-4bad-a719-d94378722659](https://user-images.githubusercontent.com/1523179/42448286-a8ff0c82-8374-11e8-9353-7a45e14dd75f.png)

**Comment by Greggless** [comment]
Relevant: https://github.com/CanonicalLtd/snapcraft-design/issues/486

**Comment by evandandrea** [comment]
This is fixed. Thanks all!
