### ISSUE TITLE
armhf-only snaps aren’t returned in search results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#892]
On snapcraft.io/store:
1\. Search for “[rigado-factory-dnsmasq](https://snapcraft.io/search?category=&q=rigado-factory-dnsmasq)” or “[rigado](https://snapcraft.io/search?category=&q=rigado)”.
2\. Search for “[pi2-kernel](https://snapcraft.io/search?category=&q=pi2-kernel)”, or “[pi2](https://snapcraft.io/search?category=&q=pi2), or “[kernel](https://snapcraft.io/search?category=&q=kernel)”.

What happens:
1\. [rigado-factory-dnsmasq](https://snapcraft.io/rigado-factory-dnsmasq) is not included in the search results.
2\. [pi2-kernel](https://snapcraft.io/pi2-kernel) is not included in the search results.

What should happen:
1\. rigado-factory-dnsmasq _is_ included in the search results.
2\. pi2-kernel _is_ included in the search results (arguably, depending on whether you think search should include kernel snaps).

Both these snaps are armhf-only, so I suspect this issue is really “Non-amd64 snaps aren’t returned in search results”. This issue has been mentioned within the team, but it doesn’t seem to be reported at the moment.

**Comment by tbille** [comment]
I opened an issue on snapstore repo: https://bugs.launchpad.net/snapstore/+bug/1783295

**Comment by kasiag** [comment]
@tbille can you estimate this work please?

**Comment by shivjoshi1996** [comment]
@tbille The fix has been released on the snap store repo, can we close this card or do we need to do something else?

**Comment by bartaz** [comment]
The search doesn't seem to return these snaps yet. So maybe we need to update something on our side?

https://snapcraft.io/search?category=&q=pi2-kernel
