### ISSUE TITLE
Copy text shown when not finding matching snaps

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/snapcraft.io#899]
### Expected behaviour
It shouldn't tell me it found no snaps when it shows the featured snaps. Are there snaps or aren't there?

I also want it to help me identify typos in my search, by showing me what I searched for.

### Steps to reproduce the problem
1. Search for a term that has no hits, e.g. https://snapcraft.io/search?category=&q=afdfdsafdas

### Specs

- _URL:_  https://snapcraft.io/search?category=&q=afdfdsafdas
- _Operating system:_ Ubuntu 18.04 LTS
- _Browser:_ Firefox 61.0.1

**Comment by Greggless** [comment]
I'm having trouble reproducing the issue. I used your search term and found this:

![image](https://user-images.githubusercontent.com/23459065/42893839-4ce42a5a-8aad-11e8-8725-132b8cec6b58.png)

**Comment by Greggless** [comment]
> It shouldn't tell me it found no snaps when it shows the featured snaps. Are there snaps or aren't there?

That is a confusing situation. [Other ap](https://play.google.com/store/search?q=theorignalbutter)[p stores](https://flathub.org/apps/search/theorignalbutter) don't follow this behaviour and just show '0 results'. I think we should follow suit.

> I also want it to help me identify typos in my search, by showing me what I searched for.

This might be a change that would need to happen in snapd's search API as we would want consistent behaviour of the search. That is certainly something we can discuss for the future @therealjuan

**Comment by Greggless** [comment]
# Proposal (part 1)

When there are no search results:
- **do not** display any snaps
- **do** display this text:
> ### We couldn't find anything for your search - **`"This is my search query"`**.
> Try using different, or more general keywords.

**Comment by matthewpaulthomas** [comment]
There is no PR to review here.

Separately, I strongly suggest splitting out spelling suggestions into a separate issue. I don’t see any reason to delay the bug fix until that feature is implemented.

**Comment by Greggless** [comment]
PR created, [separate issue](https://github.com/CanonicalLtd/snapcraft-design/issues/512) created for part 2
