### ISSUE TITLE
no labeling in kmag-window

### ISSUE THREAD

**Issue by Rosika2** [canonical-websites/snapcraft.io#914]
### Specs

- _URL:_
- _Operating system:_ Linux/Lubuntu 16.04.5 LTS, 64 bit
- _Browser:_

Hi,

I installed kmag using the command

 sudo  snap install kmag --edge.

All went well and I got the following installed:

kde-frameworks-5  5.47.0          27    stable    kde        -
kmag              master+4796c6e  7     edge      kde        -

Kmag does work. However all labeling is missing in the opening window. I get just a few cryptic symbols but no letters whatsoever.

**Comment by Rosika2** [comment]
*****UPDATE*****

I found out the following:

There seems to be a missing dependency.

When installing **kmag** via apt _libqaccessibilityclient0 (version 0+git20140203-0ubuntu2)_ was installed in addition to kmag. 
This solved the issue.

**Comment by matthewpaulthomas** [comment]
This issue doesn’t seem to have anything to do with the snapcraft.io site.

For issues with kmag please contact the kmag developers.
