### ISSUE TITLE
cache content from store homepage and blog

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#916]
In order to improve performance on users visiting snapcraft.io, we must find a way to cache some of the content that is not changing as often. Currently the blog takes a long time to load and some of the featured content in the store page does not change quite often.

**Comment by nottrobin** [comment]
This will be largely solved centrally, by [canonicalwebteam.http providing asynchronous caching](https://github.com/canonical-webteam/http/issues/3) as part of the [asynchronous caching story](https://github.com/canonical-webteam/http/issues/3).

Once that work is done, there will be a small amount of work in this codebase to simply make appropriate use of that module to achieve asynchronous caching for all public API calls. I don't mind whether this issue stays open, waiting for that work to be done, or is closed and a new one created later.

**Comment by therealjuan** [comment]
Let's close this task and open a new one once async cache is completed and ready to work on.
