### ISSUE TITLE
Add "Powered by the Canonical Distribution of Kubernetes" to the footer

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#92]
Mark suggested that we mention our use of CDK on snapcraft.io. Would this be easy to design @matthewpaulthomas @carlaberkers ?

**Comment by carlaberkers** [comment]
Yeah we just add a line to the footer

"This side is deployed using (on?) <Canonical Kubernetes> (link to Kubernetes page on Ubuntu.com)" 

You can add it to the small print at the bottom of the page.

**Comment by nottrobin** [comment]
Can it simply be:

> Deployed with [the Canonical Distribution of Kubernetes](https://www.ubuntu.com/kubernetes)

**Comment by nottrobin** [comment]
Actually, "powered by" might be better. It's not just used for deployment, it's used for running it.

**Comment by carlaberkers** [comment]
Sounds good! Let's land it :-)

**Comment by nottrobin** [comment]
done! ^

**Comment by matthewpaulthomas** [comment]
(Specs updated: [publisher service](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.hctjdt68dor7), [directory](https://docs.google.com/document/d/1p0FOzR9boI35RmsCKPOn0HNRY_kbFAS-zXqpPLh2Ot4/edit#heading=h.lwnnpqh1bkdg).)
