### ISSUE TITLE
Timeout when loading revisions

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#935]
### Expected behaviour
1. Go to a [snap with lots of revisions](https://snapcraft.io/account/snaps/heroku/listing)
1. Click on [revisions / releases](https://snapcraft.io/account/snaps/heroku/listing)
2. Wait for the page to load
3. Quickly load the page with data
4. If data isn't that quick to fetch, use some placeholder content to alleviate the pain of having to wait:

![loading placeholders](https://user-images.githubusercontent.com/23459065/43191491-30faa030-8ff3-11e8-9e23-dbef607422cd.gif)
5. Also, to help, a `[Load more]` CTA could be used to call up older revisions

### Steps to reproduce the problem
1. Go to a snap with [lots of revisions](https://snapcraft.io/account/snaps/heroku/listing)
2. Wait for the page to load
3. Wait for the page to load... 
4. **500** FUUUUUUUUUU

![image](https://user-images.githubusercontent.com/23459065/43191507-3758f49a-8ff3-11e8-8c3e-0242dc82c93a.png)

**Comment by cprov** [comment]
This endpoint was optimized but it's not in use anymore, we are using `api/v2/snaps/<name>/releases`

**Comment by Greggless** [comment]
Thanks @cprov 

Closing as it doesn't seem to affect snaps with lots of revisions, like [core](https://snapcraft.io/account/snaps/core/release) or [heroku](https://snapcraft.io/account/snaps/heroku/release).
