### ISSUE TITLE
Deleted and then re-created snaps not displayed

### ISSUE THREAD

**Issue by luk3yx** [canonical-websites/snapcraft.io#937]
Hello,

My snap has two entries in dashboard.snapcraft.io, as shown below:

![screenshot_2018-07-26 your snaps](https://user-images.githubusercontent.com/3182651/43231813-07a30108-90c2-11e8-8c55-2ab53198d4bb.png)

I cannot find a way to delete the second (revoked) entry altogether. If revoking snaps is no longer supported, all revoked snaps should be automatically deleted.

However, strangely, in the new snap list, I see neither of these entries in the new "my snaps" page.

Manually going to https://snapcraft.io/account/snaps/minetest-luk3yx/listing allows me to view and modify the snap.

### Expected behaviour
The first (published) snap should be displayed under *my snaps*, and the second either displayed there or omitted entirely.

### Steps to reproduce the problem

- Create a snap and upload a .snap file to it, but **do not** publish it.
- Revoke the snap
- Create a snap under the same name and release it

### Specs

- _URL:_ https://snapcraft.io/account/snaps
- _Operating system:_ Ubuntu MATE 16.04 LTS
- _Browser:_ Firefox 61.0.1

**Comment by Lukewh** [comment]
Hi @luk3yx, just so you know, we're looking into this

**Comment by tbille** [comment]
Issue that was coming from the snapstore api is fixed.
