### ISSUE TITLE
Can we have a jobs page

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#939]
@therealjuan and I chatted about this at Europython. Can we have a we’re hiring page that takes you to the open snapcraft engineering position we have (and any snapd or store ones).

**Comment by evandandrea** [comment]
We should also take email addresses for future openings, e.g.
>Want to be kept in the loop for future openings? Sign up to our careers mailing list.

**Comment by matthewpaulthomas** [comment]
This might be a silly idea, but: If this is difficult to implement, an interim solution might be to link from the footer directly to the Greenhouse page for one position at a time.

**Comment by evandandrea** [comment]
Here's the API call for open positions on all snap-related teams:
https://boards-api.greenhouse.io/v1/boards/canonical/departments/44475

**Comment by evandandrea** [comment]
This is fixed. Thanks all!
