### ISSUE TITLE
Snap Store buttons 

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#942]
We should have a place on snapcraft.io to demonstrate how you can add a Snap Store button to your website (listing page?).

/cc @flexiondotorg @therealjuan

**Comment by Greggless** [comment]
[Wireframe and UX work](https://github.com/CanonicalLtd/snapcraft-design/issues/314#issuecomment-382688488)

Alternately we can host this on the Public Snapcraft.io and link to from  Publisher /listing
