### ISSUE TITLE
Implement new home page

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#96]
TODO: 

- [x] update languages icons
- [x] logos responsive styles code more like Vanilla pattern
- [x] copy text review and updates
- [x] decide on 'Get started with GitHub' button text (comments in copy doc)
- [ ] footer design

**Comment by carlaberkers** [comment]
Design review actions:

Footer: ask Ant about the Yocto notification - ideally replace with generic notification if required (PR:canonical-webteam-archive/snapcraft.io-static-pages#162)
Footer: disable the wrapping rule in the footer
Footer: make footer design in line with other footers
Remove grey background on quotes
Remove "or" between buttons in the header

We have suggestions from @evandandrea, which we will address in the next iteration.

**Comment by Greggless** [comment]
### Re: Yocto footer

From Ant:

> Simon Fels asked for it
> 
> 
> [12:08] 
> As we now support Yocto/OpenEmbedded with snaps (https://github.com/morphis/meta-snappy) we should list both on the snapcraft.io page.
> 
> OpenEmbedded logo is available as SVG at http://git.openembedded.org/openembedded/tree/contrib/artwork/oe.svg
> 
> Yocto log is available at https://www.yoctoproject.org/bulk/YoctoProject_StyleGuide.pdf
> 
> For Yocto we need to follow the trademark rules: https://www.yoctoproject.org/about/trademark-policy

Yocto trademark rules state:

> You must have the following disclaimer on every page (in the footer is fine): "Yocto Project and all related marks and logos are trademarks of The Linux Foundation. This website is not, in any way, endorsed by the Yocto Project or The Linux Foundation."

**Comment by bartaz** [comment]
Footer changes and home page updates to be continued next iteration as part of https://github.com/CanonicalLtd/snappy-design-squad/issues/254 and https://github.com/CanonicalLtd/snappy-design-squad/issues/255
