### ISSUE TITLE
Page for edge-only snap says “Other versions” when there’s only one

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#975]
1\. Go to [the directory page for test-hello-dbus](https://snapcraft.io/test-hello-dbus).

What you see: A menubutton labelled “Other versions”.

![snapcraft io-other-versions](https://user-images.githubusercontent.com/19801137/43649153-4e234bf6-9734-11e8-99b4-2f2141aa9bc2.png)

What’s wrong with this: It’s not “other” than anything. No other version is mentioned anywhere, because there is none.

A simple way of fixing this would be to change “Other versions” to “All versions”. (This would also address two of the issues I flagged when reviewing #897.)

**Comment by matthewpaulthomas** [comment]
A new, and much higher-profile, example of this bug is [Plex Media Server](https://snapcraft.io/plexmediaserver).

**Comment by Lukewh** [comment]
This has been fixed and deployed
