### ISSUE TITLE
Measure what fraction of interested developers end up publishing a snap

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#982]
We should measure what proportion of people, who click the “Get started” button on [snapcraft.io/](https://snapcraft.io/), end up with a snap published in the store one month later.

This is so that we can measure the initial effect of the first-snap flow, and (later) measure the effect of any changes to it.

**Comment by matthewpaulthomas** [comment]
Something roughly like this:
- Set a unique cookie when someone clicks the button.
- If/when someone signs in, and the cookie is set, _and_ they don’t have any released snaps already, set a timer for one month starting from when the cookie was set.
- When the timer goes off, record whether they have any released snaps.

This makes me wonder whether it would be more informative (and no harder) to measure “time to first snap release” rather than just “snap release after a month, yes/no”. Then we could graph the curve (Y₁% of interested developers have a release after a week, Y₂% after two weeks, Y₃% after three weeks…).

**Comment by therealjuan** [comment]
The main objective will be to tie this piece of work with our current data strategy which includes Marketo & GA:

- [ ] Establish data collection criteria with David Callé
- [ ] Understand how to work out this within our Marketo framework
- [ ] Include this data as part of any of our data Dashboards with the ability to showcase a funnel of the flow

**Comment by matthewpaulthomas** [comment]
> Understand how to work out this within our Marketo framework

That raises a good point: none of the Marketo messages we’d normally send are appropriate in this process. I’ve reported #993 for that.

> Include this data as part of any of our data Dashboards with the ability to showcase a funnel of the flow

[In #55](https://github.com/CanonicalLtd/snap-squad/issues/55#issuecomment-319026573) I sketched how we could present a funnel of the two main ways of creating real snaps. Presenting a single first-snap flow would be simpler, but the visualization design might still be useful.
